### PR TITLE
Removed old or unwanted Streamlink Plugins

### PR DESCRIPTION
**Pull request by back-to**
They can still be used if they are not broken.

https://streamlink.github.io/cli.html#sideloading-plugins

If they are broken and someone wants to fix it,
it can be readded if they match

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

closes https://github.com/streamlink/streamlink/issues/1997

---

Added a script to create empty files only for the windows installer,
instead of creating empty files in this repo

used `touch` for it, there might be also a better solution.

If a plugin gets deleted, it must be added to this list.

closes https://github.com/streamlink/streamlink/issues/1223 as this is a workaround for this issue.

The list can be cleaned up after 2 or 3 releases.

---

Removed plugins

closes https://github.com/streamlink/streamlink/issues/1967
closes https://github.com/streamlink/streamlink/issues/1475
closes https://github.com/streamlink/streamlink/issues/1243
closes https://github.com/streamlink/streamlink/issues/1627
closes https://github.com/streamlink/streamlink/issues/1261

### CODE REVIEW

**Comment by gravyboat** [comment]
This looks good to me. I'll leave this open for a bit before merging in case other people have feedback that wasn't already provided on #1997.

**Comment by karlo2105** [comment]
I have one suggestion to do.
Why not create one branch folder https://github.com/streamlink/unmaintained_plugins where you put all removed plugins for streamlink. Streamlink itself would be provided with updated plugins and if someone becomes interested to fix unmaintained plugins they will go again to root folder. In that way there would not be any further questions about such plugins in future.

**Comment by beardypig** [comment]
@back-to how come you closed this? :)

**Comment by gravyboat** [comment]
I still want to merge this in, I was hoping for more comments then forgot to just merge it.

**Comment by gravyboat** [comment]
I'm going to reopen and merge this as soon as the tests pass again. People can fork and revert to the previous commit if they want those plugins.

**Comment by Enelar** [comment]
chaturbate works just tried

**Comment by gravyboat** [comment]
We haven't done a release since this was merged in so the plugins still exist in the stable version.

**Pull request merged**
