### PR TITLE
[AfreecaTV] Plugin update, login for +19 streams and removed buffer countdown

### PR DESCRIPTION
**Pull request by back-to**
- git patch from @schrobby https://github.com/streamlink/streamlink/issues/837#issuecomment-330091543 - Fixed https://github.com/streamlink/streamlink/issues/837
- Login for +19 streams - Fixed https://github.com/streamlink/streamlink/issues/926
  --afreeca-username
  --afreeca-password
- Removed 15 sec countdown - Fixed https://github.com/streamlink/streamlink/issues/1099
- Some error messages
- Removed old Global AfreecaTV plugin
   - http://www.afreecatv.com.tw
   - http://www.afreecatv.jp
- Added url tests

### CODE REVIEW

**Comment by back-to** [comment]
Don't merge, the `AfreecaTVHLSStream` can be fully removed with streamlink/streamlink#1432

**Comment by gravyboat** [comment]
I'll close this once #1432 is merged.

**Comment by gravyboat** [comment]
Closing since the associated PR is merged.

**Comment by back-to** [comment]
The Plugin is still broken

`--hls-segment-ignore-names` does not fix it, it will only make this **pr easier**.

---

**Reopened** and rebased / updated branch.

The Plugin should work now.

**Comment by gravyboat** [comment]
Thanks @back-to!

**Pull request merged**
