### PR TITLE
Reworked picarto.tv plugin to deal with website changes.

### LINKED ISSUE #1354: picarto.tv plugin broken
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Picarto.tv plugin erroneously reports channel offline

### Expected / Actual behavior

Command: streamlink https://picarto.tv/RedAxis best
causes player to open, stream to start in it.

Actually reports [plugin.picarto][error] The channel RedAxis is currently offline

When channel physically online and can be viewed in browser.

### Reproduction steps / Explicit stream URLs to test

1. Try open any picarto.tv stream
2. Fail
3. Check that stream works in browser

### Environment details

Operating system and version: Windows 7, OpenSUSE Tumbleweed
Streamlink and Python version: streamlink-script.py 0.8.1 for windows, streamlink 0.9.0 for Linux, Python 3.6

### Comments, logs, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by zootboy**
This should fix #1354 

I tried to make the plugin a bit more robust, but it is still reliant on regex scraping the page to determine online/offline status. If anyone has any suggestions on how to do this in a more robust way, let me know.

### CODE REVIEW

**Comment by zootboy** [comment]
Hmm, I just noticed a small case-sensitivity bug in this code. I'll push another commit to fix that soon.

**Comment by zootboy** [comment]
I reworked the plugin some more to use the official APIs (thanks @wjtk4444 for pointing these out). It seems to work fine for the regular livestreams, but the VODs API seems to be malfunctioning / broken, so that is still using regex html scraping.

Still, a big durability improvement for the main use case.

**Comment by NHOrus** [comment]
Tested this pull request, appears to be working.

**Comment by gravyboat** [comment]
Thanks @zootboy!

**Pull request merged**
