### PR TITLE
Remove faraday from travis run

### LINKED ISSUE #44: Remove faraday gem from travis.yml
Just noticed that the [travis.yml](https://github.com/streamlink/streamlink/blob/master/.travis.yml#L16) installs a random Ruby gem. I grepped thought the repo content but I couldn't find any mention of `faraday`, `ruby` or `rb`. Is this a leftover from livestreamer or doe anyone know what it does?

### PR DESCRIPTION
**Pull request by gravyboat**
Fixes #44.

### CODE REVIEW

**Comment by sbstp** [comment]
I included this in [#27](https://github.com/streamlink/streamlink/pull/27/commits/9f9c9145b413e6725c334301e4aec8c7a32957df), but idk when it'll get merged.

**Comment by gravyboat** [comment]
@sbstp Do you want to back that out from your PR so the feature stays exclusive to the install script?

**Comment by sbstp** [comment]
> feature stays exclusive to the install script?

I'm not sure what you mean by this, but I can just rebase my PR after we merge this.

**Comment by gravyboat** [comment]
@sbstp I just meant keeping the install script PR solely for the install script so it isn't rolling in a bunch of other changes. Sorry poor wording on my part.

**Comment by sbstp** [comment]
Ok sounds good. I initially included it because it was part of the old build system, and so the new build system would remove it.

**Pull request merged**
