### PR TITLE
Update requests version after bug fix

### PR DESCRIPTION
**Pull request by gravyboat**

### CODE REVIEW

**Comment by gravyboat** [comment]
This is simply a modification back to the older setup since https://github.com/kennethreitz/requests/issues/3683 is resolved.

**Comment by gravyboat** [comment]
Good point, I've updated my PR with the suggested changes, thanks!

**Comment by beardypig** [comment]
Sorry, I made a mistake it should be 2.12.0 and 2.12.1 :-)

**Comment by beardypig** [comment]
I tested on a VM (with ssh on my phone ;-)) and it worked excluding those versions, but I had to update pip for it to work correctly. I'm not sure which version of pip is required for version exclusions to work :-)

**Comment by gravyboat** [comment]
@beardypig Get outta here with your contributions, enjoy your vacation!

**Comment by beardypig** [comment]
I tried to leave it alone... But, I'm back now :p Doing this a45822b6379ef46e7f2f5e548e66e37501608e05 works :)

**Comment by gravyboat** [comment]
I'll update it later tonight.

**Comment by gravyboat** [comment]
@beardypig Oh man I was confused by your tree there for a second and thought you pushed straight to master there for a second. I've updated it with the proper versions (not sure how I missed that in the first place but whatever), and I also formatted it like in a45822b so the versions are ascending.

**Pull request merged**
