### PR TITLE
Add the README file to the Python package

### PR DESCRIPTION
**Pull request by beardypig**
Now that PyPI is migrating to their new version (warehouse, I think) we have the ability to include the README as Markdown instead of converting it to RST.

This will make the project page on PyPI look much nicer. You just have to check https://pypi.org/project/streamlink/0.12.1/ to see how great it looks right now 😉 

I also updated the classifiers while I was in `setup.py`...

### CODE REVIEW

**Comment by gravyboat** [comment]
Nice @beardypig, more good changes here!

**Comment by back-to** [comment]
here are some additional options, that can be used.

```py
python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <4',
```

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

and

```py
project_urls={
    'Documentation': 'https://streamlink.github.io/',
    'Tracker': 'https://github.com/streamlink/streamlink/issues',
},
```


https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls

**Comment by beardypig** [comment]
@gravyboat I think this is good to merge.

**Comment by gravyboat** [comment]
Cool, thanks @beardypig!

**Pull request merged**
