### PR TITLE
plugins.nhltv: new plugin for NHL.tv

### PR DESCRIPTION
**Pull request by pmrowla**
- Login required to view any live game or archived game (VOD).
  `--nhltv-email`, `--nhltv-password` and `--nhltv-purge-credentials` options can be used to specify login credentials/behavior.
- Valid subscription is required to view most games, but accounts without a subscription can watch specially designated free games
- `--nhltv-prefer-french` and `--nhltv-prefer-team=TEAM` options can be used to give priority to French language broadcasts or a specific team's home/away broadcasts when determining "best" quality stream.
  By default, priority is given in the following order:

    1. National (English)
    2. Home
    3. Away
    4. National (French)

For testing this PR, https://www.nhl.com/tv/2019020038 is a valid free VOD.
https://www.nhl.com/news/nhltv-free-games/c-291516040 has a list of upcoming free live games that can also be used to test it (either live or as a VOD after a game is concluded).

You will still have to create an account through nhl.com to watch any of the free games - visiting linked VOD in a browser should prompt you to create an account.

### CODE REVIEW

**Comment by pmrowla** [comment]
Also, I know #2587 was closed recently, but AFAIK mlb.tv and nhl.tv use the same backend (both are run by MLB Advanced Media), so making a working plugin for mlb.tv probably just requires tweaking the API url's from this plugin.

**Comment by pmrowla** [comment]
In 0f799a3 plugin is changed to not parameter `name_prefix` because of #2703

It's a one liner fix to hls.py for that issue, but I wasn't sure if that was a change that should be made in a plugin related PR.

**Comment by back-to** [comment]
basically impossible to test this without an account and geoblocking
or some other user who could/would use this plugin.

**Comment by beardypig** [comment]
Worked for me on the free VOD.

**Comment by pmrowla** [comment]
Closing due to lack of interest, for future reference the plugin will just be maintained at https://github.com/pmrowla/streamlink-plugins

**Pull request closed without merging**
