### PR TITLE
EOL Python 3.3

### LINKED ISSUE #1348: Drop support for EOL Python 3.3
### Checklist

- [x] This is a bug report.

### Description

**pytest** dropped support for python 3.3 pytest-dev/py#165

**appveyor** builds are failing because of that streamlink/streamlink#1345

https://ci.appveyor.com/project/beardypig/streamlink-4m1xi/build/1.0.1191

---

[Python 3.3.x has reached end-of-life.](https://www.python.org/downloads/release/python-337/) (2017-09-29)

maybe drop 3.3 support for **streamlink** aswell

### PR DESCRIPTION
**Pull request by beardypig**
Remove Python 3.3 from the automated testing on travis and appveyor.

fixes #1348 and the build issues with #1345

### CODE REVIEW

**Comment by back-to** [comment]
maybe remove Python 3.3 from **setup.py**

https://github.com/streamlink/streamlink/blob/master/setup.py#L85-L87

and add

```
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
Programming Language :: Python :: 3.7
```
https://pypi.python.org/pypi?%3Aaction=list_classifiers

**Comment by gravyboat** [comment]
This will also fix https://github.com/streamlink/streamlink/pull/1353, and https://github.com/streamlink/streamlink/pull/1351.

**Comment by beardypig** [comment]
@back-to made a good point - should have added the Python 3.5/6/7 classifiers :)

**Comment by gravyboat** [comment]
@beardypig It would be nice to have those changes for sure but I wanted to git this merged so those other PRs could be fixed.

**Pull request merged**
