### PR TITLE
Create arconai.py

### PR DESCRIPTION
**Pull request by cirrusUK**
author is user @intact who originally wrote the plugin for livestreamer, i only did the easy part by editing 4 lines and creating the PR.

### CODE REVIEW

**Comment by cirrusUK** [comment]
edit typo in name arconai.py

**Comment by saki4u** [comment]
how to watch https://www.arconaitv.me/usan/
i cant play this with streamlink...

**Comment by gravyboat** [comment]
@saki4u The plugin isn't merged yet so it's not yet available directly inside of Streamlink.

**Comment by gravyboat** [comment]
@cirrusUK Can you add this to the list like it was done in this PR: https://github.com/streamlink/streamlink/pull/977 please? Tests would be nice but aren't absolutely required.

**Comment by cirrusUK** [comment]
gravyboat  forgive me i am not sure what you are asking me to do :/  i use this plugin daily on a couple of machines, i can confirm it works as expected.

**Comment by saki4u** [comment]
cirrusuk  how you play arconaitv
pls share .

**Comment by gravyboat** [comment]
@cirrusUK No worries, in #977 there's a file called `docs/plugin_matrix.rst`. This file contains all the supported players (https://github.com/streamlink/streamlink/pull/977/files#diff-3035fc23a79b08afdeb9ed4106c4dc17R209 as an example of adding it from that PR). I'm just asking if you can add the plugin to that file so people know it is supported. If look at the raw version of the file on the master branch (https://raw.githubusercontent.com/streamlink/streamlink/master/docs/plugin_matrix.rst) you can see it's just a huge listing of all the plugins sorted alphabetically, so just add a new line for arconai in the proper location there. Does that make more sense?

**Comment by cirrusUK** [comment]
@gravyboat  lol nope,  i tried to edit the plugin_matrix.rst file it says, i must be on a branch to edit the file, i dont know how to edit it sorry.

**Comment by cirrusUK** [comment]
@saki4u  if you can't wait until the plugin is merged  you can add it yourself to your streamlink plugins directory https://github.com/streamlink/streamlink/pull/970/files
and use like you would any other streamlink plugin.  good luck.

**Comment by cirrusUK** [comment]
@gravyboat  I think i have managed to do it correctly.

**Comment by gravyboat** [comment]
@cirrusUK Thanks!

**Comment by saki4u** [comment]
for me its not working.
streamlink "https://www.arconaitv.me/usan/" best
streamlink https://www.arconaitv.me/usan/ best

**Comment by cirrusUK** [comment]
@saki4u  I just tested your command, it works fine, have you got the actual arconai.py  plugin in your streamlink plugins directory ?  it has been merged so a git clone of  streamlink will suffice.

**Comment by cirrusUK** [comment]
@saki4u  if you familiar with shell functions, this also works

 arconai(){
command livestreamer --player-passthrough=hls --player "mpv" hls://$(curl  "$*" | grep m3u8 | cut -d '"' -f 14 | sed 's/\\//g') best
}

**Comment by saki4u** [comment]
ys i update stream link and i can see arconai.py in plugins. wen i run
streamlink https://www.arconaitv.me/usan/ best
i get this error
error: No plugin can handle URL: https://www.arconaitv.me/usan/

**Comment by cirrusUK** [comment]
@saki4u  something is clearly wrong ? are you using windows ? if using linux or osx plz post the full path of the arconai.py file.

**Comment by saki4u** [comment]
i m using windows7
thats the path of plugins
C:\streamlink\Releases\Streamlink\streamlink\plugins
i updated with windows portable exe .

**Comment by saki4u** [comment]
sorted now....ty cirrusuk

**Pull request merged**
