### PR TITLE
Add a record option

### PR DESCRIPTION
**Pull request by grazzolini**
Add a record option for recording a stream while also playing it.

### CODE REVIEW

**Comment by bastimeyer** [comment]
Is a new parameter really required for viewing and recording at the same time?
We had the same question a few months ago in #105. See my answer of how to record streams while watching at the same time [here](https://github.com/streamlink/streamlink/issues/105#issuecomment-256678800).

It also looks like your implementation breaks the `-O` parameter while using `-R`.

**Comment by grazzolini** [comment]
I used to use tee, but tee adjusts the buffer of stdin (see stdbuf man page or tee source code). Therefore, it introduces a lot of buffering and, while the record works, it makes the player to buffer a lot and the playback cuts when this happens. With the recording happening within streamlink itself, that doesn't happen.

I'm the author of that pull request against old livestreamer and I was able to adapt it to streamlink. As for the -O option, I'll check what is happening. It worked on the livestream PR.

**Comment by grazzolini** [comment]
I confirm that using -O while also using -R breaks -O behaviour. I'm not quite sure what should it do in this case, I guess that outright ignoring the -R option should be enough.

**Comment by fishscene** [comment]
If an option to record and view simultaneously can be built in so that it works on all of our supported platforms, I say let's do it.

**Comment by grazzolini** [comment]
@fishscene 
I haven't tested on any other platform than linux. But I don't see why this option wouldn't work on them. I still haven't had time to fix the bad interaction with -O, but I plan on doing it still this week, so this PR can be merged.

**Comment by gravyboat** [comment]
Any further feedback for @grazzolini @bastimeyer? I would like to finish up discussion so we can come to a conclusion on this one.

**Comment by grazzolini** [comment]
@gravyboat 
I was quite busy for the past month, and I haven't had a chance to finish this. If you guys want, close this PR. I'll resubmit it when I have a chance. I didn't even tested this patch against latest streamlink yet. But I'm still packaging it for Archlinux, don't worry.

**Comment by gravyboat** [comment]
@grazzolini Okay thanks, I'm going to close it for now then just so we keep the queue cleared up, I'll try to remember to link this when you open the new one, thanks for understanding!

**Comment by grazzolini** [comment]
@gravyboat 
No problem at all. I hopefully will have more time pretty soon and I'll dig again on streamlink code. And I'm keeping the package on archlinux up to date as fast as I can.

**Comment by gravyboat** [comment]
Thanks for your continued support @grazzolini. Do you want me to add you to the org?

**Comment by grazzolini** [comment]
@gravyboat
I don't know what you mean by that, hehehehe.

**Comment by gravyboat** [comment]
@grazzolini It's just slightly elevated access and the ability to be part of the organization so you can publicly display it on your GitHub profile if you want. I sent you an invite.

**Pull request closed without merging**
