### PR TITLE
Add plugin for olympicchannel.com

### PR DESCRIPTION
**Pull request by xela722**
This plugin works for both non-premium live streams, and vods on the site. I'm kinda new to this so if the naming conventions or other things like that are off let me know and I'll do my best to fix them,

### CODE REVIEW

**Comment by gravyboat** [comment]
Can you please rebase? #1349 is merged. Also would you mind adding some tests for this plugin if possible?

**Comment by xela722** [comment]
Sorry, I'm a little new at git and everything. Also, I'm not quite sure how the test plugins work so I'm not sure I could apply one reliably.

**Comment by gravyboat** [comment]
@xela722 No worries, if you feel like doing tests there are a couple ways, you can do something more thorough like https://github.com/streamlink/streamlink/blob/master/tests/test_plugin_adultswim.py, or something simple like https://github.com/streamlink/streamlink/blob/master/tests/test_plugin_bloomberg.py where you just feed urls to the functions and assert that they are true/false.

**Comment by gravyboat** [comment]
Looks good to me! Thanks @xela722! I appreciate you adding tests as well.

**Pull request merged**
