### PR TITLE
docs: add a note about socks4 and socks5 vs socks4a and socks5h

### LINKED ISSUE #1654: Need a option for DNS through proxy
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Steamlink can't resolve hostnames through the proxy server. If you receive a incorrect ip of the host via DNS spoofing, the option --http-proxy and --https-proxy may not work correctly.

### Expected / Actual behavior
Expected: Steamkink connect to youtube server through proxy and work fine.
Actual: Read timed out.

### Reproduction steps / Explicit stream URLs to test
1. Run a socks5 proxy server on port 1080
2. streamlink --hls-live-restart --http-proxy "socks5://127.0.0.1:1080" --https-proxy "socks5://127.0.0.1:1080" https://www.youtube.com/watch?v=fO8x9MZ8m9g

### Logs
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.12.1
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=fO8x9MZ8m9g
error: Unable to open URL: https://youtube.com/get_video_info (SOCKSHTTPSConnectionPool(host='youtube.com', port=443): Read timed out. (read timeout=20.0))

### Comments, screenshots, etc.
This is the log of my socks5 proxy when I run the step 2:
[2018-05-15 21:26:52] connect to 8.7.198.45:443

And this is the log when I visit https://youtube.com on firefox(Use the same socks5 proxy and it works fine)
[2018-05-15 21:28:51] connect to youtube.com:443

And this is the ping log to youtube.com on my pc
Pinging youtube.com [8.7.198.45] with 32 bytes of data:
Request timed out.
Request timed out.

Stramlink resolve the hostname 'youtube.com' direct and receive the incorrect ip '8.7.198.45' via DNS spoofing. Firefox works fine because it send the DNS request through the proxy.

### PR DESCRIPTION
**Pull request by beardypig**
Fixes #1654 by updating the docs to include a note detailing the difference in DNS lookup handling for the different socks scheme.

### CODE REVIEW

**Comment by gravyboat** [comment]
@beardypig This is a good addition, what do you think about adding an example of `socks4a` or `socks5h` just in case there are any language barriers that could result in confusion:

```
.. code-block:: console
 
     $ streamlink --http-proxy "socks5h://10.10.1.10:3128/" --https-proxy "socks5h://10.10.1.10:1242"
```

**Comment by beardypig** [comment]
Could add another example :) Where do you suggest? After the note? Or do we remove the note and just expand the socks explanation?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gravyboat** [comment]
@beardypig I think keeping the note is important for clarity, so I'd say just after the note.

**Comment by beardypig** [comment]
I moved the note to above the examples, and added an example for `socks5h/socks4a`.

socks-docs-preview

**Comment by bastimeyer** [comment]
Is there a requests doc site other than
https://github.com/requests/requests/blob/master/docs/user/advanced.rst#socks
which could be added here as an additional source of information?
Their external docs site is served via regular http and doesn't contain any information about the socks proxy usage :unamused:

**Comment by gravyboat** [comment]
@bastimeyer I took a look and couldn't find anything so I'm going to merge this. If we discover something later we can add it. Thanks @beardypig!

**Pull request merged**
