### PR TITLE
[zengatv] New Plugin for zengatv.com

### PR DESCRIPTION
**Pull request by back-to**
Fixed streamlink/streamlink#890

### CODE REVIEW

**Comment by gravyboat** [comment]
@back-to I don't want to merge this if you're okay with it, that site is just a bunch of stolen content and broadcasts, sorry I never looked closely on the original request.

**Comment by back-to** [comment]
the website looks very old, but the content looks legit

most of the channel will have most likely there own website,
so it won't be important if it's added or not

---

https://en.wikipedia.org/wiki/Zenga_TV
```
Zenga TV is India's largest OTT player and digital video company,
a brand of Zenga Media Pte Ltd. Zenga received the rights
to telecast the 2012 tour of the Indian cricket team in Sri Lanka.[2]
```


http://blogs.dw.com/insider/tag/zengatv/ Date 2014-08-04 
```
DW has a new web TV partner in India. Zenga TV,
one of India’s leading portals for TV live streams will now carry the English-language
channel, DW. The channel is also available via Zenga on mobile devices.
The service currently has 21 million registered subscribers.
```

https://www.sportskeeda.com/tennis/zenga-tv-to-stream-us-open-on-mobiles 27 Aug 2013
```
Mobile TV channel Zenga TV Tuesday bagged the exclusive rights for the final
tennis major of the year, US Open, which is currently being played in New York.
```

**Comment by gravyboat** [comment]
Weird, the first thing I saw when I went on their streaming section was Cartoon Network and a few other stolen broadcasts, let's see if anyone else familiar with the site can weigh in. It's funny to mi that the largest video player company in India doesn't even use an SSL certificate for their site...

**Comment by back-to** [comment]
they have the rights for this channels,
the design of this website is just very old, their main focus is most likely the mobile app

https://economictimes.indiatimes.com/industry/media/entertainment/zengatv-inks-pact-with-turner-broadcasting-system/articleshow/14432146.cms

```
Jun 27, 2012
NEW DELHI: Mobile TV provider ZengaTV today said it has entered into a partnership with
Turner Broadcasting System, under which it will offer some of the latter's TV
channels on its platform.

Under the partnership, CNN, POGO and Cartoon Network are now available free
to mobile phone on ZengaTV's mobile TV service, ZengaTV said in a statement. 
```

**Comment by gravyboat** [comment]
@back-to Nice, good find!

**Pull request merged**
