### PR TITLE
[Pandatv] use http instead of https

### PR DESCRIPTION
**Pull request by steven7851**
Use http instead of https, because the SSL certificate is self-signed by third party. [ref: PEP 476](https://www.python.org/dev/peps/pep-0476/)
[Check pl30.live.panda.tv SSL Certificate Verify](https://sslanalyzer.comodoca.com/?url=pl30.live.panda.tv)
[Check pl29.live.panda.tv SSL Certificate Verify](https://sslanalyzer.comodoca.com/?url=pl29.live.panda.tv)
```
[cli][info] Found matching plugin pandatv for URL https://www.panda.tv/35723
[cli][info] Available streams: hq (worst), ehq (best)
[cli][info] Opening stream: ehq (http)
[cli][error] Try 1/1: Could not open stream <HTTPStream('https://pl30.live.panda.tv/live_panda/98136e97f549e01b24095ad85bbeb12f.flv?sign=8d00a9bbbf6a30738cf3f15aba5cd3a8&ts=5a3e6f6e&rid=-8654221')> (Could not open stream: Unable to open URL: https://pl30.live.panda.tv/live_panda/98136e97f549e01b24095ad85bbeb12f.flv?sign=8d00a9bbbf6a30738cf3f15aba5cd3a8&ts=5a3e6f6e&rid=-8654221 ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)))
error: Could not open stream <HTTPStream('https://pl30.live.panda.tv/live_panda/98136e97f549e01b24095ad85bbeb12f.flv?sign=8d00a9bbbf6a30738cf3f15aba5cd3a8&ts=5a3e6f6e&rid=-8654221')>, tried 1 times, exiting
pipe:: could not find codec parameters
```

### CODE REVIEW

**Comment by back-to** [comment]
Are you sure it has noting to do with your connection / pc settings?

I don't get any ssl errors on random streams.
_(with Python 3.6.3)_
```
$ streamlink https://www.panda.tv/76585 best
[cli][info] Found matching plugin pandatv for URL https://www.panda.tv/76585
[cli][info] Available streams: hq (worst), ehq (best)
[cli][info] Opening stream: ehq (http)
[cli][info] Starting player: /usr/bin/mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

$ streamlink https://www.panda.tv/824109 best
[cli][info] Found matching plugin pandatv for URL https://www.panda.tv/824109
[cli][info] Available streams: hq (worst), ehq (best)
[cli][info] Opening stream: ehq (http)
[cli][info] Starting player: /usr/bin/mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

**Comment by steven7851** [comment]
Only ```pl30.live.panda.tv``` and ```pl29.live.panda.tv``` has this problem, it's very seldom used.

**Comment by back-to** [comment]
ok i see it now, i got only `pl3` and `pl4` all the time.

---

`pl29` `pl30` works with this patch.

**Comment by gravyboat** [comment]
Do we really want to ignore verifying the SSL certificate? Why is their certificate failing in the first place?

**Comment by steven7851** [comment]
@gravyboat Because the servers is self-signed.
https://www.python.org/dev/peps/pep-0476/ FYR.

**Comment by gravyboat** [comment]
@steven7851 Have they explained why they are serving self-signed public facing servers?? That's a terrible practice.

**Comment by steven7851** [comment]
@gravyboat See here for more explanation. https://access.redhat.com/articles/2039753

**Comment by gravyboat** [comment]
@steven7851 Maybe I am not explaining myself properly. I understand what the issue is, but I do not understand why we would want to support a service which has broken or self signed certificates by bypassing the certificate verification. That is a failing on their end, and bypassing the check without explicit permission from the end user seems bad to me as there is no guarantee they are pulling the content down over a secure connection which cannot be intercepted by various agencies or their ISP. Why would we implement this instead of telling PandaTV that some of their servers have self signed certificates which they should fix?

**Comment by steven7851** [comment]
@gravyboat OK, I understand..

**Comment by gravyboat** [comment]
@steven7851 Can we contact them and notify them that some of their certificates are invalid or something? I didn't mean to completely end the discussion on this and apologize if it came across that way since you closed the PR.

**Pull request closed without merging**
