### PR TITLE
[douyu] temporary fix by revert to previously commit

### PR DESCRIPTION
**Pull request by steven7851**
#1004 
There is a better API in https://coapi.douyucdn.cn/front/document/wiki/140, but I don't have any account to login.
If someone can login, plz provide the API infomation, very thanks.

### CODE REVIEW

**Comment by beardypig** [comment]
@steven7851 the previous build probably failed due to a build issue, if you rebase on master your build should be successful.

**Comment by fozzysec** [comment]
The previous version failed today, douyu changed the API that used when checking online status. comment the lines of checking online status will temporarily works.
#1004

**Comment by steven7851** [comment]
@fozzysec Thanks.

**Comment by gravyboat** [comment]
@steven7851 Do you want to squash these commits real quick before I merge?

**Pull request merged**
