### PR TITLE
Update the documentation

### PR DESCRIPTION
**Pull request by sbstp**

### CODE REVIEW

**Comment by sbstp** [comment]
Is the coveralls bot supposed to post 3 times?

**Comment by cdrage** [comment]
@sbstp it'll post each-time you rebase / update the commit. It's a known issue.

Otherwise, PR LGTM!

**Comment by sbstp** [comment]
Once this is merged I'll create a streamlink.github.io repo and push the docs there. We'll have a basic website setup.

**Comment by sbstp** [comment]
Turns out I don't have the access right to make a new repository in the org. Can you create `streamlink.github.io` and give me push access?

**Comment by cdrage** [comment]
@sbstp done! gave everyone admin access for `streamlink.github.io`, have at it! don't worry about getting an ACK / for every PR and all for streamlink.github.io, just merge it in so we can at least get started with a base site.

**Pull request merged**
