### PR TITLE
plugins.canlitv: fix URLs

### PR DESCRIPTION
**Pull request by emraher**

### CODE REVIEW

**Comment by gravyboat** [comment]
The tests associated with the plugin failed, can you please take a look and fix the errors?

```
=================================== FAILURES ===================================

____________________ TestPluginCanlitv.test_can_handle_url _____________________

self = <tests.test_plugin_canlitv.TestPluginCanlitv testMethod=test_can_handle_url>

def test_can_handle_url(self):

# should match

self.assertTrue(Canlitv.can_handle_url("http://www.canlitv.com/channel"))

>       self.assertTrue(Canlitv.can_handle_url("http://www.canlitv.life/channel"))

E AssertionError: None is not true

tests/test_plugin_canlitv.py:24: AssertionError

=============== 1 failed, 395 passed, 5 skipped in 13.03 seconds ===============

The command "python -m pytest tests/" exited with 1.
```

**Comment by gravyboat** [comment]
These test changes don't do a check against `canlitv.plus` and simply remove life. You should just be able to add another assert true for the new URL.

**Comment by emraher** [comment]
Tried to make `test_plugin_canlitv.py` look like the original one. I hope this time it's OK.

**Comment by gravyboat** [comment]
@emraher Yep looks good to me! Sorry about the delay and thanks for the contribution.

**Comment by fener06** [comment]
is not working..

**Comment by gravyboat** [comment]
@fener06 Then file a new issue with detailed output regarding the command and the error output please. (or upgrade to the latest Streamlink release if you aren't already on it)

**Pull request merged**
