### PR TITLE
plugins.pluzz : Hide bugged streams

### PR DESCRIPTION
**Pull request by Urgau**
This fix hide temporary bugged streams

### CODE REVIEW

**Comment by Urgau** [comment]
The problem is that the video stream takes 5 seconds to start and then a few seconds later nothing more. I have a closer look and I think the problem comes from the website and not from streamlink.

**Comment by back-to** [comment]
this could be a streamlink issue rather than a plugin issue

only the init video will be played,
everything else will be downloaded in the background but won't be played.

it works in the webbrowser

https://www.france.tv/france-3/direct.html
https://gist.github.com/back-to/31e8367af1b9a177054e28de72bc59f4/revisions

**Comment by Urgau** [comment]
Okay, however, if it's a streamlink problem I don't have enough knowledge to fix it or even find it.
However, I recommend that you accept my pull request until you find and fix the problem.

What are you going to do to fix the problem?

**Comment by back-to** [comment]
I don't know how much work it is to fix the dash stream,
but if you want it removed temporarily,
you should remove all related dash code

see when it was added https://github.com/streamlink/streamlink/commit/84a2f90c8c9ff93b876c1f9bb04a586de8b146ea#diff-57d44e5f969dec7c7a4f48de4c3f2c8b

**or** you can ignore the dash streams with `--stream-types hls,hds`

https://streamlink.github.io/cli.html#cmdoption-stream-types

---

also the issue is related to

https://github.com/streamlink/streamlink/blob/cac78e43e0f1ab632cb6796a758c10d876e36ed5/src/streamlink/stream/dash.py#L245-L246

when the audio and video gets muxed

---

when `self.video_representation` or `self.audio_representation` gets played alone,
without calling `open` on the other type, they work.

https://github.com/streamlink/streamlink/blob/cac78e43e0f1ab632cb6796a758c10d876e36ed5/src/streamlink/stream/dash.py#L237-L243

https://github.com/streamlink/streamlink/blob/cac78e43e0f1ab632cb6796a758c10d876e36ed5/src/streamlink/stream/dash.py#L247-L250

**Pull request closed without merging**
