### PR TITLE
Fix zdf_mediathek TypeError

### PR DESCRIPTION
**Pull request by tam1m**
File "C:\Python35\lib\site-packages\streamlink-0.0.2-py3.5.egg\streamlink\plugins\zdf_mediathek.py", line 95, in _get_streams
    formatList = res["priorityList"]["formitaeten"]
TypeError: list indices must be integers or slices, not str

### CODE REVIEW

**Comment by lawli3t** [comment]
Seems good, I dont know how i missed that one - what a fuckup. im sorry @skulblakka.

**Comment by tam1m** [comment]
For me all the different quality settings are working. Am I missing something?

**Comment by lawli3t** [comment]
The priorityList has several entries, and you are taking only the first one. I get more qualities when using all of them:

`[cli][info] Available streams: 96k (worst), 219k, 140p, 468k, 176p, 272p, 769k, 364p, 480p, 1486k, 576p, 720p, 2286k, 3281k (best)`

I submitted a pull request to your repository to fix that, also flattened the whole loop / if structure (which is unrelated to you).

**Comment by tam1m** [comment]
Now it makes sense to me why it is a list in the first place. Thought it was weired since "all" the qualities were in the first one..

**Comment by lawli3t** [comment]
Yeah, dont worry. I missed something here too. Thanks for uncovering my mistake before the release! Saved me from bigger embarassment, ha!

**Comment by skulblakka** [comment]
> what a fuckup. im sorry @skulblakka.

@lawli3t Looks like I messed up too. Before I merged your commit (and made my PR) I wanted to test your code but ran the code from the wrong folder which contained only my changes to the original streamlink repo not your changes to my fork.

**Pull request merged**
