### PR TITLE
Improve NSIS installer script

### PR DESCRIPTION
**Pull request by bastimeyer**
- Remove unnecessary start menu shortcut creation
- Don't automatically close the copy/remove file section
- Add checkbox for opening the documentation in the web browser
- Add checkbox for editing the config file

### CODE REVIEW

**Comment by bastimeyer** [comment]
Publisher data for the uninstaller info in the Windows control center is still missing, as I mentioned here: https://github.com/streamlink/streamlink/issues/116#issuecomment-261114313

The installer file does have the default nsis icon right now. This should be changed once we have an icon for streamlink.

**Comment by gravyboat** [comment]
This looks good to me! Any other input @sbstp, @beardypig?

**Comment by beardypig** [comment]
Looks good, but I haven't had chance to test it out yet.

**Comment by sbstp** [comment]
I just tested it, works well (Windows 10). The copy/remove window automatically closing really bothered me, thanks for fixing this. Nothing blocking a merge from my side.

**Comment by gravyboat** [comment]
I'm going to merge this in. I think with this and https://github.com/streamlink/streamlink/pull/178 we're ready for the 0.0.3 release.

**Comment by sbstp** [comment]
Yep I agree. We should setup a milestone for 0.0.4

**Comment by gravyboat** [comment]
@sbstp You mean for 0.0.3? Or you want to create a new milestone for 0.0.4?

**Comment by beardypig** [comment]
I also tested it out just now :) Worked fine for me too (Windows 10 VM). 
Uninstalling also removed the shortcut that was created by the current installer :)

**Comment by bastimeyer** [comment]
> Uninstalling also removed the shortcut that was created by the current installer :)

Yep, the `uninstall_shortcuts` block also needs to be replaced with an empty one.
Is this negligible or do you want another PR?

**Comment by beardypig** [comment]
I think removing the shortcut is suitable, I wonder if it could be removed at install time.

**Comment by bastimeyer** [comment]
> I wonder if it could be removed at install time

Shortcuts are not being created anymore by the installer, so why do you want to remove shortcuts at install time?

**Comment by beardypig** [comment]
When upgrading, at least it should remove the shortcut from an old install. Otherwise you might have an orphan shortcut.

**Comment by bastimeyer** [comment]
Is it really the job of a newer installer to remove obsolete stuff from previous releases? I'd say that this is what the uninstaller of older releases is for. Removing stuff during the installation is a bit unexpected IMO. 

The startmenu shortcut could also be used-created and could have custom parameters, so that is actually useful. Upgrading would then always delete it.

**Comment by gravyboat** [comment]
@bastimeyer I think the issue is that many users won't remove the old version before installing the new version. What does it look like if I do an installation of 0.0.3, then simply install 0.0.4? Will the old release and the associated content be removed? After a bunch of releases it would be a bummer if old stuff wasn't removed (similar to the trash that Nvidia does with their installer).

**Pull request merged**
