### PR TITLE
Add a single newline at the end of the file.

### PR DESCRIPTION
**Pull request by ficofabrid**

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks like the tests failed, restarted them, I'm fine with this since it's a pep8 support thing, any concerns @beardypig?

**Comment by beardypig** [comment]
Pretty good commit for Hacktoberfest :-) I don't see any problems with it.

**Comment by gravyboat** [comment]
@beardypig It's too old for that sadly. @ficofabrid Are you participating in Digital Ocean's Hactoberfest: (https://hacktoberfest.digitalocean.com/)? If so do you want to close this PR and open a new one so you get credit for October for the shirt?

**Comment by beardypig** [comment]
Ah yeah :-)

**Comment by ficofabrid** [comment]
Don't care about this. Just merge it.

**Comment by beardypig** [comment]
Thanks @ficofabrid :)

**Pull request merged**
