### PR TITLE
Add changelog and twitch_oauth to index.rst

### PR DESCRIPTION
**Pull request by mmetak**

### CODE REVIEW

**Comment by beardypig** [comment]
@mmetak these might be better as two separate PRs, best to keep the changes separated. One for docs change and one for plugin fix :-)

Also, you could rebate on master to get rid of that merge commit :-)

**Comment by mmetak** [comment]
@beardypig Sorr 'bout that. I made a new one, should be fixed.

**Comment by beardypig** [comment]
Cool. It's better and easier for you, if you make a new branch on your local repo, and then submit that as a PR. That way you can have multiple different changes that can be merged independently :-)

Do you want to close this one, now that you made the other one?

**Comment by mmetak** [comment]
Sure. Thanks. ;-)

**Pull request closed without merging**
