### PR TITLE
0.12.0 Release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by Conjuro** [comment]
Was about to update the Chocolatey package (streamlink/streamlink-chocolatey#27), when I realized there's no Windows installer?

**Comment by cdrage** [comment]
@Conjuro Uh oh. Looks like I released it before doing a merge of the PR: https://github.com/streamlink/streamlink/pull/1643 ... So it's not generating.

I have to do a 0.12.1 release since Pip doesn't allow removing old versions..

**Comment by cdrage** [comment]
It should generate now. Sorry about that guys.. I put like.. 2 big warnings to merge the PR before I continue the release script but nope! 0.12.1 has been released.

**Comment by bastimeyer** [comment]
And I thought the reordering of the release assets was a [refined-github](https://github.com/sindresorhus/refined-github) feature. If it's the default github layout now, then the notes should be changed on the next release, maybe even to a more neutral text. :)

**Pull request merged**
