### PR TITLE
plugins.bfmtv: fix/find Brightcove video data in JS

### LINKED ISSUE #3660: plugins.bfmtv: No playable streams found
Hello. for few days, the plugin isn't working anymore

/usr/local/bin/streamlink --loglevel debug  https://rmcdecouverte.bfmtv.com/mediaplayer-direct/ best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bfmtv for URL https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
error: No playable streams found on this URL: https://rmcdecouverte.bfmtv.com/mediaplayer-direct/

### PR DESCRIPTION
**Pull request by mkbloke**
WIP:
- [ ] Check all supported sites to remove any possibly redundant code

closes #3660

### CODE REVIEW

**Review by bastimeyer — COMMENTED** [review]
The brightcove JS regex looks a bit dirty, but I can't see any other way of finding the video ID and account ID. Same old issue with stream parameters hidden in minified JS code.

What is the reason for changing the if/else block logic? The consecutive regexes don't seem to be necessary. You're yielding the resolved streams instead of returning them, which means the generator will continue executing.

The duplicate code of the JS match stuff could also be reduced by re-using the code from the first if block.

**Comment by mkbloke** [comment]
Yes, the regex isn't ideal.  Hopefully it's anchored well enough without being too inflexible...

I suppose the original thought with the structure was that I would just append the latest code to the end in a fall-through system.  I could go back to if/else and put the new code in a sub-if-else of the original Brightcove code?

I'd already eliminated the duplicate code a little time before your review, but I haven't pushed it to GH yet.

Cheers.

**Comment by campones** [comment]
Hi 

I don't know if this issue was fixed. I actually update to the last version and curiously, rmc story works, but not rmc decouverte

 /usr/local/bin/streamlink --loglevel debug  https://rmcdecouverte.bfmtv.com/mediaplayer-direct/ best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-73-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bfmtv for URL https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
error: No playable streams found on this URL: https://rmcdecouverte.bfmtv.com/mediaplayer-direct/


 /usr/local/bin/streamlink --loglevel debug  "https://rmcstory.bfmtv.com/mediaplayer-direct" best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-73-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://rmcstory.bfmtv.com/mediaplayer-direct
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bfmtv for URL https://rmcstory.bfmtv.com/mediaplayer-direct
[plugins.bfmtv][debug] Account ID: 5817780576001
[plugins.bfmtv][debug] Video ID: 5819523494001
[plugins.brightcove][debug] Creating player for account 5817780576001 (player_id=default_default)
[plugins.brightcove][debug] Finding streams for video: 5819523494001
[plugins.brightcove][debug] Found policy key: BCpkADawqM0Vf5bBynj38NWF6WWHlEyvp-xFG61CaAN2057UG8tkVjOU4ys6Q7uuAzTuZ1M0pfffgaMv2YMFyjKdrtXt2yFEyeguaDJ-3Feu1GrBk53A2mI36NznZ1ZsDSrSydN77DC61nkQ
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 180p_alt (worst), 180p, 270p_alt, 270p, 480p_alt, 480p (best)
[cli][info] Opening stream: 480p (hls)
[stream.hls][debug] Reloading playlist

**Comment by campones** [comment]
Hi
It seems something is wrong 

streamlink -l debug  "https://rmcstory.bfmtv.com/mediaplayer-direct" best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://rmcstory.bfmtv.com/mediaplayer-direct
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bfmtv for URL https://rmcstory.bfmtv.com/mediaplayer-direct
error: Unable to open URL: https://rmcstory.bfmtv.com/mediaplayer-direct (HTTPSConnectionPool(host='rmcstory.bfmtv.com', port=443): Max retries exceeded with url: /mediaplayer-direct (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls12_check_peer_sigalg', 'wrong signature type')])"))))

**Comment by bastimeyer** [comment]
Don't comment on merged PRs with plugin issues and use the **latest development** version.

> SSLError("bad handshake: Error([('SSL routines', 'tls12_check_peer_sigalg', 'wrong signature type')])")

Not a Streamlink problem. You'll have to fix your SSL/TLS issues.

Apart from that, the plugin is working fine with a French IP address:

```
$ streamlink -l debug --http-proxy 'socks5://localhost:1920' 'https://rmcstory.bfmtv.com/mediaplayer-direct' best
[cli][debug] OS:         Linux-5.12.10-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.1.2+35.g6cdc3eb
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://rmcstory.bfmtv.com/mediaplayer-direct
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --http-proxy=socks5://localhost:1920
[cli][info] Found matching plugin bfmtv for URL https://rmcstory.bfmtv.com/mediaplayer-direct
[plugins.bfmtv][debug] Account ID: 5817780576001
[plugins.bfmtv][debug] Video ID: 5819523494001
[plugins.brightcove][debug] Creating player for account 5817780576001 (player_id=default_default)
[plugins.brightcove][debug] Finding streams for video: 5819523494001
[plugins.brightcove][debug] Found policy key: BCpkADawqM0Vf5bBynj38NWF6WWHlEyvp-xFG61CaAN2057UG8tkVjOU4ys6Q7uuAzTuZ1M0pfffgaMv2YMFyjKdrtXt2yFEyeguaDJ-3Feu1GrBk53A2mI36NznZ1ZsDSrSydN77DC61nkQ
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 180p_alt (worst), 180p, 270p_alt, 270p, 480p_alt, 480p (best)
[cli][info] Opening stream: 480p (hls)
```

**Pull request merged**
