### PR TITLE
plugins.lrt: add support for Lithuanian National Television

### LINKED ISSUE #1812: [plugn request] lrt.lt
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Would it be possible to add a plugin for the Lithuanian National Television? Video streams are located [here](https://www.lrt.lt/mediateka/tiesiogiai/lrt-televizija), [here](https://www.lrt.lt/mediateka/tiesiogiai/lrt-kultura) and [here](https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica).

Thanks.

### PR DESCRIPTION
**Pull request by beardypig**
Support for live and VOD streams :)

Fixes #1812

### CODE REVIEW

**Comment by gravyboat** [comment]
Good stuff, thanks @beardypig. I looked over the site and the streams don't seem to be an issue, but I also don't speak the language so I could only get through what Google Translate provided.

**Comment by beardypig** [comment]
https://en.wikipedia.org/wiki/LRT_televizija :)

**Comment by gravyboat** [comment]
@beardypig Yeah I looked at that as well but I've been double checking sites even with a Wikipedia entry as a few here and there still aren't legit.

**Comment by beardypig** [comment]
Fair enough, "government owned" is good enough for me :)

**Pull request merged**
