### PR TITLE
plugins.crunchyroll: refactoring and updated API calls

### LINKED ISSUE #1808: No streams found for newest CR episodes that are only available to premium users
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
I'm not sure if its fair to call this a bug as it might be an issue on Crunchyroll's end either purposeful or not. I'm not able to watch the latest episode in a series if it's only available to premium users using Streamlink, even logged in as a premium user as there are no streams available according to Streamlink.

error: No playable streams found on this URL: http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957

I can't find any recent issues that match this behaviour and I used to be able to play the latest episode with Streamlink though the last time I used Streamlink was about a month or so ago for new episodes I've mainly been rewatching older shows.

URL Tested with http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
Tested watching other URLs which are not exclusive to premium users and they work fine.

...

### Expected / Actual behavior
A stream should be found and playable using Streamlink as there is no CR related issues open at present.
...

### Reproduction steps / Explicit stream URLs to test

1. Grab a URL (E.G http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957) for a new episode which is only available to premium users at present.
2. Use URL with Streamlink as usual.

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
[console][debug] OS:         Windows 10
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
[console][debug] Plugin specific arguments:
[console][debug]  --crunchyroll-username=howdlej (username)
[console][debug]  --crunchyroll-password=******** (password)
[plugin.crunchyroll][debug] Creating session with locale: en_GB
[plugin.crunchyroll][debug] Session created
[plugin.crunchyroll][debug] Using saved credentials
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
error: No playable streams found on this URL: http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
```

### Comments, screenshots, etc.

If this is a known issue and something CR is doing specifically to counter Streamlink then please feel free to delete or mark as closed but I couldn't see anything about this specific issue or any other related CR issues.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by beardypig**
This fixes the session issue #1574 using the API rather than the website, as this change caused some other issues.

The only changes I might make are to the X-Android headers, as it is pretty obviously the emulator. 

I added a small convenience parameter to `cache.set` to allow you to set an expiry time rather than expiry duration. (Need to add tests for this)

Should fix #1808.

### CODE REVIEW

**Comment by gravyboat** [comment]
Good stuff @beardypig, I think this is good to go unless you have something else you want to add as it has resolved the original issue.

**Comment by beardypig** [comment]
I would be nice is @Atemu could give it a try to see if their problem is still solved.

**Comment by Atemu** [comment]
Sure, getting a US Session ID via the method I used still doesn't work for the Monogatari series (eventhough it works for all other geo blocked content I've tried), but the ID Streamlink generates when using a US VPN or proxy now works flawlessly.

I just had to adjust my scripts to use an actual proxy instead of the other method.

Thanks a bunch @beardypig !

**Comment by beardypig** [comment]
>Sure, getting a US Session ID via the method I used still doesn't work for the Monogatari series

@Atemu were you generating a session id with an account?

**Comment by Atemu** [comment]
Don't think so, but it had nothing to do with Streamlink (I only assumed it did because Streamlink didn't generate the ID properly either) and shouldn't really have worked in the first place.

**Comment by beardypig** [comment]
@gravyboat _I_ think it's good to go.

**Comment by gravyboat** [comment]
Good stuff, thanks @beardypig.

**Pull request merged**
