### PR TITLE
0.8.0 Release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by gravyboat** [comment]
@cdrage When you do the release notes can you add the new collective link above the download link and note that credit cards are accepted?

**Comment by cdrage** [comment]
@gravyboat Hey man, I've gone ahead and reverted the master branch to before this PR. I'll add the collective link. Seems like I was *way* too fast in creating the changelog, etc.

**Comment by gravyboat** [comment]
@cdrage No worries, it really isn't that big a deal and I just thought of it, sorry for creating extra work for you.

**Comment by gravyboat** [comment]
Will redoing it break this? https://github.com/streamlink/streamlink/releases/tag/0.8.0

**Comment by cdrage** [comment]
@gravyboat haha no worries. It's not a problem with us, just PyPi.. Odd that they've never fixed that one issue even after 3 years.

I don't think it would break https://github.com/streamlink/streamlink/releases/tag/0.8.0 as I've already gone ahead and removed it.

**Comment by gravyboat** [comment]
@cdrage I was specifically talking about the windows executables that get added, sorry. I don't have a nice comment regarding why it hasn't been fixed so I won't say anything.

**Pull request merged**
