### PR TITLE
plugins.kanal7: Fixed iframe_re/stream_re, added new domain

### PR DESCRIPTION
**Pull request by back-to**
closes https://github.com/streamlink/streamlink/issues/2215

### CODE REVIEW

**Comment by dreamboxco** [comment]
i have add this here but not work whats wrong?

`import logging
import re
import unittest

from streamlink.compat import urljoin, urlparse
from streamlink.plugin import Plugin
from streamlink.stream import HLSStream
from streamlink.utils import update_scheme


class TestPluginKanal7(unittest.TestCase):
    def test_can_handle_url(self):
        should_match = [
            'http://www.kanal7.com/canli-izle',
            'https://www.tvt.tv.tr/canli-yayin',
        ]
        for url in should_match:
            self.assertTrue(Kanal7.can_handle_url(url))

    def test_can_handle_url_negative(self):
        should_not_match = [
            'https://example.com/index.html',
        ]
        for url in should_not_match:
            self.assertFalse(Kanal7.can_handle_url(url))

    def test_iframe_re(self):
        test_list = [
            # http://www.kanal7.com/canli-izle
            ('<iframe id="selectFrame" src="https://www.kanal7.com/canli-yayin-iframe.php" scrolling="no"></iframe>',
             'https://www.kanal7.com/canli-yayin-iframe.php'),
            # https://www.tvt.tv.tr/canli-yayin
            ('<iframe id="selectFrame" src="/canli-yayin-iframe.php" height="650"></iframe>',
             '/canli-yayin-iframe.php'),
        ]
        for text, url in test_list:
            m = Kanal7.iframe_re.search(text)
            self.assertIsNotNone(m, url)
            self.assertEqual(m.group(1), url, url)

    def test_stream_re(self):
        test_list = [
            # http://www.kanal7.com/canli-izle
            ('''script.setAttribute('video-source','https://live/kanal7LiveDesktop/index.m3u8');''',
             'https://live/kanal7LiveDesktop/index.m3u8'),
            # https://www.tvt.tv.tr/canli-yayin
            ('''video-source="https://live/tvtLiveStream/index.m3u8"''',
             'https://live/tvtLiveStream/index.m3u8'),
        ]
        for text, url in test_list:
            m = Kanal7.stream_re.search(text)
            self.assertIsNotNone(m, url)
            self.assertEqual(m.group(1), url, url)

__plugin__ = Kanal7`

**Comment by back-to** [comment]
@dreamboxco 

> File "/usr/lib/python2.7/site-packages/streamlink/plugins/kanal7.py", line 53

there is no line 53, use this file

https://raw.githubusercontent.com/streamlink/streamlink/f972fbf262067f97a72e515b34e4e99d5834b829/src/streamlink/plugins/kanal7.py

**Comment by gravyboat** [comment]
Looks good, thanks @back-to.

**Comment by dreamboxco** [comment]
now it works thanks

**Comment by sambirempo** [comment]
Doesnt work anymore please fix again. URL changed I think same counts for ULKE TV

**Pull request merged**
