### PR TITLE
2017

### PR DESCRIPTION
**Pull request by jokerr77**
Minor change from 2016 to 2017.

### CODE REVIEW

**Comment by bastimeyer** [comment]
@streamlink/members
I think the copyright holder information of the repo's main license file needs to be split. The debian package already does this (although 2017 is missing):
https://github.com/streamlink/streamlink/blob/0.3.0/debian/copyright#L6-L9

**Comment by beardypig** [comment]
@bastimeyer sounds like a good idea.

**Comment by gravyboat** [comment]
Yeah we updated it once to 2016 because that was when we forked it from Chrippa, but now that it's 2017 we need a new entry in the license.

**Comment by cdrage** [comment]
@gravyboat  + @streamlink/members 

Yeah, we'll need to run a script through the license to update it for 2017-onwards. Similar to https://github.com/streamlink/streamlink/blob/0.3.0/debian/copyright#L6-L9

So basically saying:

"Contributors of Streamlink" or something along those lines.

**Comment by cdrage** [comment]
Ex:
```
Copyright (c) 2011-2016, Christopher Rosell
Copyright (c) 2016-2017, Streamlink Contributors
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by bastimeyer** [comment]
Could you please open a PR with these changes (or just push it to master), @cdrage? These changes should be okay, I guess.
Btw, the debian package also still needs the year change. 😃

**Comment by gravyboat** [comment]
Closing this one out in favor of https://github.com/streamlink/streamlink/pull/515 per our discussion previously.

**Pull request closed without merging**
