### PR TITLE
plugins.douyutv: support vod

### PR DESCRIPTION
**Pull request by steven7851**

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me, do you want to add tests? If not I'll get it merged.

**Comment by gravyboat** [comment]
@steven7851 Any desire to write some tests or no?

**Comment by steven7851** [comment]
@gravyboat Not now. I'll add test when I have free time. Thank you.

**Comment by gravyboat** [comment]
Merged, thanks for contributing!

**Pull request merged**
