### PR TITLE
[ABweb] New plugin for BIS Livestreams of french AB Groupe

### PR DESCRIPTION
**Pull request by back-to**
> AB Groupe
> The AB is a French business group in the field of broadcasting.
> https://en.wikipedia.org/wiki/AB_Groupe

**Requires a login and a subscription.**

Username/Password is only required for the first login every 24h,
it will cache the required cookies and force a relog every 24h.

```
$ streamlink "http://www.abweb.com/BIS-TV-online/bistvo-tele-universal.aspx?chn=ab1" best
[cli][info] Found matching plugin abweb for URL
http://www.abweb.com/BIS-TV-online/bistvo-tele-universal.aspx?chn=ab1
[plugin.abweb][info] Attempting to authenticate using cached cookies
[cli][info] Available streams: 75k (worst), 240p, 360p, 432p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

http://www.abweb.com/BIS-TV-Online/
http://www.abweb.com/BIS-TV-Online/bistvo-tele-universal.aspx

closes https://github.com/streamlink/streamlink/issues/1592

---

Ping @NeySlim

would be nice if you can test it, the easiest way without changing all files is

sideloading the file `src/streamlink/plugins/abweb.py`

https://streamlink.github.io/cli.html#sideloading-plugins
https://streamlink.github.io/cli.html#cmdoption-plugin-dirs

and change this two lines from

```py
    options = PluginOptions({
        'username': None,
        'password': None,
        'purge_credentials': None
    })
```

to

```py
    options = PluginOptions({
        'username': 'YOUREMAIL',
        'password': 'YOURPASSWORD',
        'purge_credentials': None
    })
```

### CODE REVIEW

**Comment by back-to** [comment]
Not sure why you got an error at the first time there

It could be some _requests session error_, but **i can't reproduce it.**

---

can you reproduce it with every new session?

**delete** `~/.cache/streamlink/plugin-cache.json` to reset the cached session cookies

---

**if you can reproduce it**

change your file with this one and run the command with `-l debug` so it will print your installed versions.

https://gist.githubusercontent.com/back-to/98b56c02cd4459f2bfb02a0cb97fc185/raw/1bf5c426ab5a22445f2099adcdf8f0cbf58a368a/abweb.py

https://gist.github.com/back-to/98b56c02cd4459f2bfb02a0cb97fc185

it will print the whole website source to your terminal and some other informations.

could you upload the output as a **SECRET** file on https://gist.github.com/
and send me an email with the link.

**Comment by NeySlim** [comment]
Can't reproduce it. I think it may be a network issue, since it's an iframe, it may lead to another domain that was not resolved correctly or something like that.

**Comment by NeySlim** [comment]
There was an update on the ab website and streamlink cannot find playlist anymore.
I wanted to correct myself, but I have to admit, I suck.
This is still the same manifest, still the iframe, maybe the it's just the regex to catch it ?

If you lead me where the url is parsed, I can try to correct myself. Otherwise, credentials you've got are still available.

**Comment by back-to** [comment]
the iframe website changed,
with the new update it should work again.

**Comment by NeySlim** [comment]
Dude.
You rock.

**Comment by gravyboat** [comment]
Sorry about the delay here @back-to, busy week at work.

**Pull request merged**
