### PR TITLE
[TVP] New Plugin for Telewizja Polska S.A.

### PR DESCRIPTION
**Pull request by back-to**
> Telewizja Polska S.A. (TVP S.A., or Polish Television) is a public broadcasting corporation,
> the only public TV broadcaster in the territory of the Republic of Poland.
> https://en.wikipedia.org/wiki/Telewizja_Polska

http://tvpstream.vod.tvp.pl
http://tvpstream.vod.tvp.pl/?channel_id=1455

```
[cli][info] Found matching plugin tvp for URL
http://tvpstream.vod.tvp.pl/?channel_id=1455
[cli][info] Available streams: none_101k, 288p_228k (worst), 288p_578k,
288p_1119k, 288p_1797k, 576p_2433k, 576p_3811k (best)
[cli][info] Opening stream: 576p_3811k (hls)
```

closes https://github.com/streamlink/streamlink/issues/1590

---

ping @remek30

### CODE REVIEW

**Comment by beardypig** [comment]
Anyone else been able to test this? @remek30?

**Comment by remek30** [comment]
I would like to be able to test it as it works in streamlink. How can I do this?

**Comment by beardypig** [comment]
Cool @remek30, are you using Windows, Linux or macOS - and how did you install streamlink?

**Comment by remek30** [comment]
I have streamlink installed on VU + Ultimo4K.

**Comment by beardypig** [comment]
OK, interesting - I guess that is using Linux... depending on the user that runs streamlink you need to put [tvp.py](https://raw.githubusercontent.com/back-to/streamlink/e1b398bc49556e70e2659bbcfb0035c7e2aecab2/src/streamlink/plugins/tvp.py) in to `$XDG_CONFIG_HOME/streamlink/plugins` and it will be loaded as an extra plugin when you run streamlink.

**Comment by remek30** [comment]
I do not have such a folder in the VU + Ultimo4K decoder. Streamlink in this decoder is in the usr / sbin / streamlinksrv location. I pasted this tvp.py file there and tried to enable the channel from http://tvpstream.vod.tvp.pl/?channel_id=1455 but it does not work. Probably I put a tvp.py file in the wrong place

**Comment by beardypig** [comment]
@remek30 I'm not familiar with that, so I think you'll have to wait until those files are updated I'm afraid.

**Comment by back-to** [comment]
if you want to sideload it with your E2 receiver
https://streamlink.github.io/cli.html#sideloading-plugins

the path will be

```bash
~/.config/streamlink/plugins/
# or
/home/root/.config/streamlink/plugins/
```

but you will have to create the folders

---

or you use the install path of your streamlink version

```
/usr/lib/python2.7/site-packages/streamlink/plugins/
```
you might need to **restart** your streamlinksrv or your receiver

**Comment by remek30** [comment]
thank you very much. Now I tested this tvp.py on the VU + Ultimo4k tuner and it works perfectly. I would be happy to test it even if the .py file was ready for the site: http://www.europaplus.ru/europaplustv or http://europaplustv.com/ or else. I am available to test and provide test results.

**Comment by gravyboat** [comment]
Thanks @back-to!

**Pull request merged**
