### PR TITLE
Drop Python 2.6 support

### PR DESCRIPTION
**Pull request by beardypig**
As pointed out by @scottbuettner in #538/#539, we don't really have good support for Python 2.6. `requests` is currently pinned to `<2.0` for Python 2.6 and as such lacks SNI support. A lot of plugins use Python 2.6 incompatible format strings (I'll admit a lot of those were added by me:). 

Python 2.6 is no longer supported by the core Python team and is not getting any more updates. A lot of packages are starting to deprecate Python 2.6, and will soon stop supporting Python 2.6. 

I am proposing that deprecate Python 2.6 support, remove it from CI and from the docs as a supported Python version. We can continue to support it in a best-effort capacity, but I think "official" support puts an extra drain on the development work. However, if anyone does wish to continue Python 2.6 support they are more than welcome.

### CODE REVIEW

**Comment by gravyboat** [comment]
I see no reason to continue Python 2.6 support. The only users I can think of who might be impacted are those running very old Linux distros, is there anyone else? I agree, it's too much work to be worth supporting.

**Comment by Brainzyy** [comment]
I agree with all the above. Since there's no official support for it, it would be better to drop it.

**Comment by cdrage** [comment]
I agree too to drop 2.6 support.

**Comment by beardypig** [comment]
If this PR is merged it will remove Python 2.6 from the CI builds (travis, appveyor doesn't do 2.6) and will update the docs noting that Python 2.7 is minimum Python version supported. Nothing is done to explicitly stop people from installing `streamlink` on Python 2.6.

Most of the obvious Python 2.6 issues are also fixed by this PR.

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by gravyboat** [comment]
Then I'm merging it, next up let's drop 2.7!

**Pull request merged**
