### PR TITLE
plugins.twitch: support for clips added

### PR DESCRIPTION
**Pull request by chhe**
This PR adds clips support to the Twitch plugin.

e.g.:

https://clips.twitch.tv/basetradetv/BeautifulDuckOpieOP

### CODE REVIEW

**Comment by gravyboat** [comment]
Good stuff, thanks!

**Comment by Brainzyy** [comment]
@chhe @gravyboat Just a question, is it necessary to give a quality 2 names? (Lines 23,24 and so forth)

**Comment by chhe** [comment]
@Brainzyy Unfortunately, yes. Twitch uses different strings to identify the available quality options. For regular streams they still use `source`, `high` and so on. For clips they use the actual horizontal resolution i.e. `1080` for 1080p, `720`for 720p and so on.

**Comment by Brainzyy** [comment]
@chhe Thank you for clearing that up :)

**Pull request merged**
