### PR TITLE
Improve coverage reports on codecov

### LINKED ISSUE #3191: Update codecov/coverage config and add lgtm.com check
As an improvement to the code coverage reports, I'm proposing the following changes:

1. **Remove codecov-bot comment from pull requests**
   The comment with the status table nowadays gets added to the PR **checks** page ([example](https://github.com/streamlink/streamlink/pull/3187/checks?check_run_id=1144194464)) and can be read there. This will reduce the spamming (notifications as well) and also the audit log spamming when the bot usually updates its comment. The report page on codecov.io should be linked in the **checklist** next to the merge button, but for some reason it doesn't do that on the repo here and just links to their homepage. I don't see this behavior on the Twitch GUI repo and it correctly links to the generated report. That's probably a configuration issue here.
2. **Add branch coverage**
   `pytest-cov` currently only generates line coverage data, which isn't that detailed and useful. Branch/partial coverage data can be generated by adding [`--cov-branch`](https://pytest-cov.readthedocs.io/en/latest/config.html) to the [`pytest` command](https://github.com/streamlink/streamlink/blob/3a57a3ac6211b22843505c53a3466f8719dc3bdf/.github/workflows/main.yml#L39).
3. **Split the coverage scopes**
   The coverage reports can be [split up by codecov into different "projects"](https://docs.codecov.io/docs/commit-status), eg. "overall" (default - should be disabled), "streamlink", "streamlink_cli", "plugins", "tests".
   This helps checking which parts are tested well enough and which are not (plugins for example), and different targets + thresholds can be defined. The split coverage projects will be listed separately in the PR checklist and commit status, but differentiating between "streamlink", "streamlink_cli" and "tests" is what we should do at least IMO. The tests [need to be added](https://github.com/streamlink/streamlink/blob/3a57a3ac6211b22843505c53a3466f8719dc3bdf/.coveragerc#L1-L3) by the coverage generator of course.
4. **Rename `codecov.yml` to `.codecov.yml`**
   CI provider config files should be a dotfile.

----

Regarding lgtm.com, this is a CI service which semantically analyzes the code ("AI based" :roll_eyes:) in addition to the code-linter's static analysis. This helps finding more potential issues and the service is free for open source projects.

We currently have over 50 unnoticed alerts, most of them being issues with regexes in plugins:
https://lgtm.com/projects/g/streamlink/streamlink/alerts/?mode=list

I already have this service enabled on the Twitch GUI repo, so all it takes selecting the Streamlink repo from the drop-down in the [Streamlink orga settings](https://github.com/organizations/streamlink/settings/installations/11010222).

Enabling it will add another entry to the checklist of PRs and pushed/merged commits.

----

But let's wait for the next release first before changing anything.

### PR DESCRIPTION
**Pull request by bastimeyer**
Resolves #3191

1. Enables branch coverage (proper line hit numbers are still unsupported)
2. Gathers coverage from tests
3. Turns codecov config file into a dotfile
4. Splits up coverage reports into "projects"
   - `default` (overall data)
   - `streamlink`
   - `streamlink_cli`
   - `plugins`
     Plugins are excluded from the streamlink project, because they are rarely fully tested and unnecessarily distort the coverage results
   - `tests`
5. Sets coverage change thresholds
   - `default`
     Doesn't have a threshold and sets an overall **target of 50%**
   - `streamlink` **1%**
   - `streamlink_cli` **1%**
   - `plugins`
     Since plugins are rarely fully tested or tested at all, no threshold here as well and instead a **target of 30%**
   - `tests` **0%**
     New tests should always be fully covered. if it's not possible, lines can be annotated with `# pragma: no cover`
6. Disables the PR comment made by the codecov bot, to reduce noise.
   When disabling the PR comments, the `default` project needs to be kept, because it's the only project which has a summary text similar to the comment, and the other projects don't have this.
7. Increases the `codecov.notify.after_n_builds` config to the exact number of test runners, so that the reports will only be posted once everything is ready. Otherwise, failures may be reported for a short while until every runner has finished, and we don't want that.
   To make sure that the coverage PR checks get created, even during service outages on codecov or when an upload has stalled and is in limbo, we've made the `default` status project a requirement for merging, which means it'll always await the coverage reports. This `default` check has a coverage target of 50% and it's unlikely to be undershot by a contributor's changes and therefore won't fail. We could also set an optional `informational` flag here, so that it always passes.

**One thing to note is that by splitting up the coverage reports and adding threshold values, this PR's status will fail.**
A workaround would be submitting two PRs, where the second one sets the thresholds and the first one doesn't have any success conditions, but that's unnecessary.

### CODE REVIEW

**Comment by gravyboat** [comment]
@bastimeyer Looks good, pretty dumb that `after_n_builds` doesn't support a negative value to achieve what you want, but oh well.

**Comment by bastimeyer** [comment]
As you can see, it's failing in some cases, because it doesn't have a reference point on the PR base yet (the master branch) and the delta is too high for the set threshold of 1%:
https://github.com/streamlink/streamlink/pull/3200/checks?check_run_id=1158219285

And regarding the `codecov.notify.after_n_builds`, I think we should set this to 10, the overall number of runners, so that it doesn't show failures while running.

**Comment by bastimeyer** [comment]
What a great timing, there are no statuses after my push because apparently there's a "minor service outage"...
https://codecov.io/gh/streamlink/streamlink/commit/9f9fbab16df9a03413cb3f54e82a7d4bff61592b

And btw, if it's sometimes only showing "Codecov report" in the check list instead of the coverage delta, that's a bug which was reported on codecov's support forum yesterday or today.

**Comment by bastimeyer** [comment]
@gravyboat Should we set the overall default report (the 50% target) as a master branch protection requirement? I think that a missing status like right now counts as a failure and blocks from (accidental / early) merging.

**Comment by gravyboat** [comment]
@bastimeyer I'm not really a fan of that because it increases the overhead and easily confuses contributors, but if you're passionate about it I'm fine with that.

**Comment by bastimeyer** [comment]
With the coverage of the tests being included now, the overall coverage is at 62.73%. That means that 50% won't be undershot unless lots of stuff gets removed, which is very unlikely. That won't confuse contributors, because it "can't fail". Remember that this check only exists for the summary similar to the removed comment. Requiring this check is purely for cases like this right now where the report is still pending.

**Comment by gravyboat** [comment]
@bastimeyer Okay that's fine by me then, let's do it. 👍

**Comment by bastimeyer** [comment]
> **codecov/project** Expected — Waiting for status to be reported

OK, done.

Let me restart the runners so they can re-upload the reports. I don't think this was properly queued on codecov's end and the missing reports are lost. I could also force a notification push on the PR page on codecov.io, and it would probably be enough since the only missing reports were ubuntu 3.5 and 3.6, but let's not do this.

**Comment by bastimeyer** [comment]
@gravyboat If you feel more comfortable with the `informational: true` flag on the default project, so that it always succeeds/passes, and only *truly* serves as a report-upload-guarantee, then I could quickly change that.

Otherwise, we should be good to go here if we also ignore the status failure due to the split up and thresholds added, as mentioned above/earlier.

**Comment by gravyboat** [comment]
@bastimeyer Nah I don't care that much. It's fine since the chance of it falling below is extremely small. I'll give the others a couple hours to respond and if they don't will merge later tonight.

**Comment by bastimeyer** [comment]
That squash merge wasn't ideal. Now the history of the codecov config is gone due to the rename+change and the other individual changes are now part of one commit :/
A simple merge commit or rebase would've been better to preserve the semantic changes of the PR.

**Comment by gravyboat** [comment]
Sorry @bastimeyer :( I didn't think it was something we'd consider reverting.

**Pull request merged**
