### PR TITLE
plugins.tvplayer: fix bug with some channels not loading

### PR DESCRIPTION
**Pull request by beardypig**
Should fix the issue mention in https://github.com/streamlink/streamlink/issues/849#issuecomment-303064621.

### CODE REVIEW

**Comment by ppsspp213** [comment]
Still the same in 0.6.0+6daa2b5

**Comment by beardypig** [comment]
This hasn't been merged yet, so is not available in any nightly version. You would nee to manually update your `tvplayer.py` plugin file.

**Comment by gravyboat** [comment]
@beardypig Good stuff, thanks!

**Comment by ppsspp213** [comment]
Works fine with login but for channels that don't require login, it throws up this when you don't add the login details

streamlink https://tvplayer.com/watch/home best
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/ho
me
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in
 <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 103
8, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482
, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394
, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 328, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 236, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\tvplayer.py",
line 97, in _get_streams
    stream_data = self._get_stream_data(**stream_attrs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\tvplayer.py",
line 73, in _get_stream_data
    token=context_data["token"],
KeyError: 'token'

**Comment by beardypig** [comment]
Ah, yes should be `context_data.get("token", "")`, or similar. I'll update it later... I didn't see a channel before without a token :-)

**Pull request merged**
