### PR TITLE
plugins.ustreamtv: use Desktop instead of Mobile streams

### PR DESCRIPTION
**Pull request by back-to**
- use websocket API from https://github.com/streamlink/streamlink/pull/1777
- use **flv/segmented** streams for better stream qualitys

---

Test plugin URL `ustreamtv.py`

https://raw.githubusercontent.com/back-to/streamlink/ustream_desktop/src/streamlink/plugins/ustreamtv.py

---

might need to change some naming of the new used code.

---

@porcomail

closes https://github.com/streamlink/streamlink/issues/1146

@dd00

closes https://github.com/streamlink/streamlink/issues/1653

@sokkycakes

closes https://github.com/streamlink/streamlink/issues/1767

@InstallGentoo11

closes https://github.com/streamlink/streamlink/issues/2050

@xpatryk89

closes https://github.com/streamlink/streamlink/issues/2076

@beardypig

closes https://github.com/streamlink/streamlink/pull/1777

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me but I'm going to leave it open for others to review since this is a pretty big change.

**Comment by RuKeBo** [comment]
Doesn't seem to handle offline streams very well.  If I get an offline stream it says "Switching cluster to: omega" and just sits there.

**Comment by RuKeBo** [comment]
Works ok now.

Thanks,

**Comment by gravyboat** [comment]
This looks good, thanks @back-to.

**Pull request merged**
