### PR TITLE
plugins.canlitv: support for ecanlitvizle.live

### PR DESCRIPTION
**Pull request by beardypig**
Replacement PR for #1442.

### CODE REVIEW

**Comment by back-to** [comment]
since this is a restreaming website
maybe removing it would make more sense,
most of the streams are already covered from there original source anyways.

**Comment by gravyboat** [comment]
Yeah I agree with @back-to that we should just remove this plugin, we need to take a stance on this at some point and we've been cracking down on sites that are basically just restreams of stolen content.

**Comment by dreamboxco** [comment]
here is the new site http://www.canlitvizle.ca/?i=1

**Comment by beardypig** [comment]
Closing this as it seems to be a maintenance burden, we should open another PR to remove this plugin.

**Pull request closed without merging**
