### PR TITLE
appveyor: add codecov support

### PR DESCRIPTION
**Pull request by beardypig**
Get code coverage for Windows tests.

### CODE REVIEW

**Comment by gravyboat** [comment]
Awesome thanks!

**Comment by beardypig** [comment]
Still need to enable it for Streamlink, apparently an email was sent to to organisation's owners to ask for permission, I imagine you got it? Or maybe not, maybe you need to login on appveyor to do it...

**Comment by gravyboat** [comment]
@beardypig I spaced it last night when I saw the email, just approved the request.
appveyor_access

**Comment by beardypig** [comment]
Cool! Need to add the web hook for pull requests, I don't have admin rights on the repo so you will have to do it. https://ci.appveyor.com/api/github/webhook?id=7p5qew1w50r23563 should work.

**Comment by gravyboat** [comment]
Was there a secret associated with this or anything? This is what the interface looks like:
appveyor

**Comment by beardypig** [comment]
No secret, content type form encoded, and select events "push" and "pull request". 

Maybe you can login to appveyor, it supports logging in via Github, and set it up more easily.

**Comment by gravyboat** [comment]
I logged in but didn't have any options for the existing project it seems. I configured the webhook as per your comment.

**Comment by beardypig** [comment]
OK let's see if it works. If not, maybe need to remove and add the project again :-)

**Pull request merged**
