### PR TITLE
plugins.crunchyroll: update auth logic

### LINKED ISSUE #3148: Unable to purge crunchyroll credentials or reauthenticate
## Bug Report
- [x] This is a bug report and I have read the contribution guidelines.

### Description

Once your crunchyroll credentials expire, it seems like you can no longer purge them using --crunchyroll-purge-credentials or reauthenticate (if you delete your existing credentials from appdata).

### Expected / Actual behavior

Earlier, both purge and reauthenticating failed with
```error: Unable to validate API response: Unable to validate key 'auth': Type of None should be 'str' but is 'NoneType'```
Now they fail with:
```
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Users\kg\AppData\Local\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 1024, in main
    handle_url()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 585, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 465, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 369, in _create_api
    login = api.authenticate()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 217, in authenticate
    data = self._api_call("authenticate", {"auth": self.auth}, schema=_login_schema)
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 173, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: User could not be found.
```

### Reproduction steps / Explicit stream URLs to test

```streamlink https://www.crunchyroll.com/my-teen-romantic-comedy-snafu/episode-9-a-whiff-of-that-fragrance-will-always-bring-memories-of-that-season-796536 best -o oregairu9.mkv```

I have a username and password in my streamlinkrc, and I successfully downloaded an episode from CR about 2 days ago. I'm logged into the CR website right now so I don't think anything is wrong with my account.

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/my-teen-romantic-comedy-snafu/episode-9-a-whiff-of-that-fragrance-will-always-bring-memories-of-that-season-796536
[cli][debug] Plugin specific arguments:
[cli][debug]  --crunchyroll-username=******** (username)
[cli][debug]  --crunchyroll-password=******** (password)
[utils.l10n][debug] Language code: en_US
[plugin.crunchyroll][debug] Creating session with locale: en_US
[plugin.crunchyroll][debug] Session created with ID: c492ba4c706943f73dbf9819a8237465
[plugin.crunchyroll][debug] Using saved credentials
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Users\kg\AppData\Local\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 1024, in main
    handle_url()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 585, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 465, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 369, in _create_api
    login = api.authenticate()
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 217, in authenticate
    data = self._api_call("authenticate", {"auth": self.auth}, schema=_login_schema)
  File "C:\Users\kg\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 173, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: User could not be found.
```

### PR DESCRIPTION
**Pull request by beardypig**
Updated the auth logic a bit, re-authenticating with the auth token no longer returns an auth token. If the saved token no longer works then it will try to authenticate with the username and password if they are set. 

I updated the old logging calls too.

fixes #3148

### CODE REVIEW

**Comment by gravyboat** [comment]
Nice looks good, thanks @beardypig.

**Comment by skcihmit** [comment]
Thanks @beardypig. Confiring this fixes the issue - I had to still manually delete my auth token file to get it to work though.

**Comment by beardypig** [comment]
@skcihmit that's weird, it should have detected that the credentials didn't work and removed them automatically. You don't happen to have a log output from that failed attempt do you? :)

**Comment by skcihmit** [comment]
@beardypig sorry, no I don't, and I can't recreate it, so must have been something else I did.

**Pull request merged**
