### PR TITLE
Updated UStreamTV plugin

### PR DESCRIPTION
**Pull request by beardypig**
This is a complete re-write of the `UStreamTV` plugin. Only the mobile HLS streams are supported, not the custom fragmented flv/mp4 desktop streams. Some new features have been added though, eg. support for referrer locked embedded streams. There are future plans to support the desktop streams using this new API as well.  

This new plugin uses the new long polling UStream API (rather than the websockets API, to avoid adding a new dependency). The requirement for `python-librtmp` has been removed, and the docs updated to reflect this. 

If this is merged I suggest a new issue be created to track the addition of desktop stream support and the following issues be closed: #57, #58, #110, #129, #719, and #747.

### CODE REVIEW

**Comment by back-to** [comment]
the plugin works for me.

---

i think you removed the password support from the plugin here
https://github.com/streamlink/streamlink/pull/754/files#diff-907ea417b0c797b31eb5d1b934f148d8L415

but not from the other files

https://github.com/streamlink/streamlink/blob/c8a46395d05f9716374c82ed6d378241aab99fe4/src/streamlink_cli/argparser.py#L1024-L1030

https://github.com/streamlink/streamlink/blob/c8a46395d05f9716374c82ed6d378241aab99fe4/src/streamlink_cli/main.py#L803-L805

---

`plugin_matrix` needs an small update 
https://github.com/streamlink/streamlink/blob/fb81b65ecccde88d0352695e86af339f6f56c520/docs/plugin_matrix.rst#L192

```diff
-ustreamtv           ustream.tv           Yes   Yes   Currently broken.
+ustreamtv           ustream.tv           Yes   Yes
```
---

the issues won't close automatically with `,`  only the first one 🌵

**Comment by beardypig** [comment]
Thanks @back-to, well spotted. I'll take a quick look at adding password support again :)

The list of issues is more of a note to remember to close them after.

**Comment by beardypig** [comment]
Turned out to be quite simple to add password protected stream support hehe :)

**Comment by gravyboat** [comment]
Is this ready to merge then @beardypig?

**Comment by beardypig** [comment]
I've had some positive feedback, but probably should leave it open for now incase anyone wants to test it. There are some videos that are desktop only so won't work still - should note that in the docs...

**Comment by gravyboat** [comment]
I think we should merge this in, no one has said anything in over a week!

**Comment by TheSneakySniper** [comment]
@gravyboat Will we ever get support for desktop streams, do you think?

**Comment by back-to** [comment]
I need always two trys for a referer locked url, maybe there is a way to change this.

http://a-pac.tv
http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true

from issue #775

### Test with direct USTREAM url
first try
```sh
$ streamlink --plugin-dir plugins/ "http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true" best -l debug
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ecf6-lp-omega.ums.ustream.tv, and connectionId=deokpsq1d6ii90a805gh7tt3jc-7
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=http://www.a-pac.tv, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ece6-lp-omega.ums.ustream.tv, and connectionId=rfrd8s8sn6v4ida7jd6bh0id79-6
error: No playable streams found on this URL: http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true
```
second try
```sh
$ streamlink --plugin-dir plugins/ "http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true" best -l debug
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=http://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ef4c-lp-omega.ums.ustream.tv, and connectionId=ma1pl249lakgm6ej2oghnm513u-4
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=http://www.a-pac.tv, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ecf6-lp-omega.ums.ustream.tv, and connectionId=er33nh2trjkpto5bglo4c6n8pt-3
[cli][info] Available streams: 240p (worst), 270p (best)
[cli][info] Opening stream: 270p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 30 to queue
[stream.hls][debug] Adding segment 31 to queue
[stream.hls][debug] Adding segment 32 to queue
[stream.hls][debug] Download of segment 30 complete
[cli][info] Starting player: /usr/bin/vlc
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 31 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 32 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 33 to queue
[stream.hls][debug] Download of segment 33 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 34 to queue
[stream.hls][debug] Adding segment 35 to queue
[stream.hls][debug] Download of segment 34 complete
[stream.hls][debug] Download of segment 35 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 36 to queue
[stream.hls][debug] Download of segment 36 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 37 to queue
[stream.hls][debug] Download of segment 37 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
$ 
```

### Test with Iframe url (same as before, but this time i got the url from the iframe)
first try
```
$ streamlink --plugin-dir plugins/ http://a-pac.tv best -l debug
[cli][info] Found matching plugin apac for URL http://a-pac.tv
//www.ustream.tv/embed/20848756?wmode=direct?autoplay=true
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=https://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ef4c-lp-omega.ums.ustream.tv, and connectionId=oqmnmi0ihpp876jq1mildibbb3-2
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=http://www.a-pac.tv, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ece6-lp-omega.ums.ustream.tv, and connectionId=p2j9decrcq7561ltsbgqsur5dl-6
error: No playable streams found on this URL: http://a-pac.tv
```
second try
```sh
$ streamlink --plugin-dir plugins/ http://a-pac.tv best -l debug
[cli][info] Found matching plugin apac for URL http://a-pac.tv
//www.ustream.tv/embed/20848756?wmode=direct?autoplay=true
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=https://www.ustream.tv/embed/20848756?wmode=direct?autoplay=true, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ef4c-lp-omega.ums.ustream.tv, and connectionId=ogvh0nvhkdma30bkhlc0bccpur-0
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=20848756, application=channel, referrer=http://www.a-pac.tv, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ecf6-lp-omega.ums.ustream.tv, and connectionId=1fv8qtjhsockceir25c9aoremk-6
[cli][info] Available streams: 240p (worst), 270p (best)
[cli][info] Opening stream: 270p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 43 to queue
[stream.hls][debug] Adding segment 44 to queue
[stream.hls][debug] Adding segment 45 to queue
[stream.hls][debug] Download of segment 43 complete
[cli][info] Starting player: /usr/bin/vlc
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 44 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 46 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
$
```

**Comment by beardypig** [comment]
@back-to yeah, I have fixed the moduleInfo retry loop now :)

**Comment by gravyboat** [comment]
I think we can merge this now right @beardypig? No additional notes in a week.

**Comment by beardypig** [comment]
I think it's good to go, but I wrote it :)

**Comment by gravyboat** [comment]
Yep just wanted to make sure you didn't have any additional updates. Thanks for adding this, going to merge it.

**Comment by beardypig** [comment]
There are few related issues that can probably be closed now :-)

**Pull request merged**
