### PR TITLE
Add support for Bloomberg

### PR DESCRIPTION
**Pull request by melmorabity**
This PR provides support for Bloomberg TV, as requested in https://github.com/streamlink/streamlink/issues/776. It supports:

* live TV/radio streams:
  * https://www.bloomberg.com/live/europe
  * https://www.bloomberg.com/live/us
  * https://www.bloomberg.com/live/asia
  * https://www.bloomberg.com/live/stream
  * https://www.bloomberg.com/live/emea
  * https://www.bloomberg.com/live/asia_stream
  * https://www.bloomberg.com/audio (radio)
* VOD (https://www.bloomberg.com/news/videos/*/*), for example:
  * https://www.bloomberg.com/news/videos/2017-04-18/is-may-s-call-for-an-early-election-a-risky-move-video
  * https://www.bloomberg.com/news/videos/2017-04-18/full-show-bloomberg-daybreak-americas-04-17-video

Streams don't seem to be georestricted.

### CODE REVIEW

**Comment by beardypig** [comment]
Looks good to me :)

**Comment by beardypig** [comment]
Not sure why the travis build is failing for 3.6 and not for any others...

**Comment by gravyboat** [comment]
I restarted the 3.6 job in the event it was some weirdness as I didn't see anything that specifically pointed to an issue. If it fails again we can troubleshoot from there.

**Comment by gravyboat** [comment]
Easy enough, passed on the second run, merging. Thanks @melmorabity!

**Comment by beardypig** [comment]
That's weird I restarted it and it failed, oh well :-D

**Pull request merged**
