### PR TITLE
plugins.daisuki: add support for VOD streams from daisuki.net

### PR DESCRIPTION
**Pull request by beardypig**
Main plugin courtesy of @intact: https://gist.github.com/intact/3d6af5f361c1a44fd878 👍 

Adds a new option `--daisuki-mux-subtitles` that will automatically convert the xml subtitles to srt and mux them into the output stream which requires `ffmpeg`. (Which I think is pretty cool.)

### CODE REVIEW

**Comment by beardypig** [comment]
RFC: Should the subtitles be muxed by default? It requires `ffmpeg` and disables the possibility of `player-passthrough` for the stream (which is `hls`), which is why I had it disabled by default.

**Comment by intact** [comment]
btw. plugin use first language from multi languages subtitles (you can try Tales of Zestiria the X)

**Comment by beardypig** [comment]
Cool, I didn't have an example of a multi language show. I will set it up to use the locale settings to pick the correct language, with a fallback to language in the URL.

**Comment by starchivore** [comment]
First of all, thanks a lot for working on this one and that's doing fine with your stable portable version:

[https://github.com/beardypig/streamlink-portable](https://github.com/beardypig/streamlink-portable)

OTOH, something could be missing from **Streamlink_Patches.zip** and the VB version of streamlink-portable ain't supporting Daisuki.net ATM:

[https://github.com/streamlink/streamlink-portable/blob/master/Streamlink%20for%20Windows%20(Compiled)/Files/Resources/Streamlink_Patches.zip](https://github.com/streamlink/streamlink-portable/blob/master/Streamlink%20for%20Windows%20(Compiled)/Files/Resources/Streamlink_Patches.zip)

Regarding multi-lingual subtitles, here's an example with three languages:

[http://www.daisuki.net/us/en/anime/watch.DRAGONBALLSUPERUniverseSurvivalsaga.16137.html](http://www.daisuki.net/us/en/anime/watch.DRAGONBALLSUPERUniverseSurvivalsaga.16137.html)

FYI - this one should include:
English (1st)
Russian (2nd)
Spanish (3rd)

[http://bngnwww.b-ch.com/caption/35470338/4695/105124076934854/1763267720.xml](http://bngnwww.b-ch.com/caption/35470338/4695/105124076934854/1763267720.xml)

BTW, their security might be quite a bit tighter than the others and I wasn't even able to get **--player-passthrough hls** working with or without that **mpv.com --cookies** option:

image

Adding **--hls-prefer-native** to youtube-dl but no luck again:

image

Turned off youtube-dl with **--no-ytdl** and no dice as well:

image

image

No seeking but at least that's doing fine:

image

playback fails with 403
[https://github.com/kozec/chrome-extension-daisuki-html5/issues/1](https://github.com/kozec/chrome-extension-daisuki-html5/issues/1)

Option to choose resolution while playing m3u8?
[https://github.com/mpv-player/mpv/issues/2116](https://github.com/mpv-player/mpv/issues/2116)

**Comment by RosadinTV** [comment]
@starchivore Thanks for the report, i fixed the Pycryptodrome issue in https://github.com/streamlink/streamlink-portable/commit/e55b501ae3842797fdaea3c3dd9a5bce0b57c4fe

**Comment by beardypig** [comment]
Updated to mux all available subtitle tracks as they are all in one file. The user can select the subtitle track in their player.

**Comment by gravyboat** [comment]
Awesome, thanks @beardypig!

**Comment by starchivore** [comment]
Fantastic, thanks a lot for such a great job!

Regarding the conversion from XML line breaks (**< br/>**) to SRT line breaks, it's a bit tricky and that ain't working for these guys ATM:

MPC-HC v1.7.10
mpv v0.24.0
VLC v2.2.4

Basically subtitles with a single line is OK while the second line should be truncated / dropped since that CRLF wasn't handled properly:

[SRT universal formatting](https://forum.opensubtitles.org/viewtopic.php?t=15844)

[KDS-SRT: SubRip (.SRT File Extension)](http://www.textfiles.com/uploads/kds-srt.txt)

[SRT Subtitles - issue with line breaks](http://superuser.com/questions/788972/srt-subtitles-issue-with-line-breaks)

[SRT Subtitle - Line breaks](https://groups.google.com/d/msg/mx-videoplayer/9KzgBYew7tQ/TXt_FJA8asAJ)

[.Srt caption doesn't work?](https://support.jwplayer.com/customer/portal/questions/6062913--srt-caption-doesn-t-work-)

[SubRip decoder](https://ffmpeg.org/pipermail/ffmpeg-devel/2010-December/083892.html)

[SubRip (.SRT) subtitles support in players](http://ale5000.altervista.org/subtitles.htm)

[http://mplayerhq.hu/pipermail/mplayer-dev-eng/2005-October/037767.html](http://mplayerhq.hu/pipermail/mplayer-dev-eng/2005-October/037767.html)
[http://mplayerhq.hu/pipermail/mplayer-dev-eng/2005-October/037913.html](http://mplayerhq.hu/pipermail/mplayer-dev-eng/2005-October/037913.html)

FYI - this is ASS to SRT:

[https://github.com/luigino/ass2srt/blob/master/ass2srt.pl](https://github.com/luigino/ass2srt/blob/master/ass2srt.pl)

Instead of having fun with CRLF of SRT since that could be (potentially) a hit or miss, maybe we could simply convert XML to ASS instead?

**Comment by beardypig** [comment]
`ffmpeg` coverts it to ass or ssa when it muxes it in to the mkv output. I was going off this https://matroska.org/technical/specs/subtitles/srt.html for `srt`, which seems to suggest `\n` would be fine. I will take a look and fix it. Thanks for all the links, really useful :-)

**Comment by beardypig** [comment]
@starchivore: the truncated subtitles issue was unrelated to newlines in `srt`, see #616 :)

**Pull request merged**
