### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -L serie,dota,versio,medias,deques,cros,doubleclick,avod,fo,archiv,reponse`

### CODE REVIEW

**Review by bastimeyer — CHANGES_REQUESTED** [review]
Thanks for the PR.

- `streamlink.packages` contains 3rd party code and should not get modified
- `streamlink.webbrowser.cdp.devtools` is generated code and must not be modified
- modifying old changelogs is pointless

**Comment by kianmeng** [comment]
@bastimeyer Should I close this PR since I've updated the checking rules based on your suggestion didn't identify any typo errors?

```
$ codespell -S src/streamlink/packages/,src/streamlink/webbrowser,CHANGELOG.md -L cros,medias,serie,versio,doubleclick,reponse,avod,deques,fo,archiv,dota
```

**Comment by bastimeyer** [comment]
According to the PR's diff, there are a couple of typos / grammar errors / spelling mistakes outside of the ignored files which your `codespell` run found.

If you want to fix these, then please just update your commit and force-push. Otherwise, close the PR. Thanks.

**Comment by kianmeng** [comment]
> If you want to fix these, then please just update your commit and force-push. Otherwise, close the PR. Thanks.

Noted. I've checked, and those are not typos. Will close PR. Thanks.

**Pull request closed without merging**
