### PR TITLE
fix azubu.tv plugin

### PR DESCRIPTION
**Pull request by Brainzyy**
Thanks to GitHub user ThomasReedt for the fix!

### CODE REVIEW

**Comment by gravyboat** [comment]
@Brainzyy Looks like there are some merge conflicts now due to merging in https://github.com/streamlink/streamlink/pull/9, could you please rebase?

**Comment by Brainzyy** [comment]
@gravyboat I'm a git noob, but I tried, is it working now?

**Comment by gravyboat** [comment]
@Brainzyy Looks good to me in terms of the conflict, tests are running and hopefully someone can review it.

**Comment by Brainzyy** [comment]
@gravyboat  seems like Travis CI is done, don't know how long coveralls takes.

**Comment by gravyboat** [comment]
@Brainzyy Coveralls is usually done as soon as travis is, something is probably wrong with how it is processing (or the fact there isn't a coverage file), which I'll work on later today after I finish work.

**Comment by cdrage** [comment]
+1 / LGTM to me for this!

**Pull request merged**
