### PR TITLE
Ustream Partial Fix

### PR DESCRIPTION
**Pull request by RosadinTV**
-To avoid errors now only mobile streams are displayed
-Mobile prefix removed
-VOD not supported warning added

### CODE REVIEW

**Comment by gravyboat** [comment]
It seems like this might conflict with the work @beardypig has started for https://github.com/streamlink/streamlink/issues/58. Could you please weigh in @beardypig? This PR looks good but I don't want to limit people to mobile streams if the original problem is addressed.

**Comment by RosadinTV** [comment]
@gravyboat Also notice this, the ideal thing is fix all part of the Plugin (i mean support desktop streams and VOD too) this PR is something like a bypass until someone who know more about Python (in fact, i almost didnt know anything) fix the whole thing.

**Comment by gravyboat** [comment]
@RosadinTV There's a PR over here: https://github.com/streamlink/streamlink/pull/137 that takes care of the Ustream issues, I have a few concerns for merging it since it adds additional dependencies to Streamlink, but it would be great if you could try it out.

**Comment by RosadinTV** [comment]
@gravyboat Checked, seems promising but a bit unstable for now (and dont support VOD too), however is going in the right way.
Also i like the new dependency pymp4, maybe can be usefull for upcoming or updating plugins, i mean another streams providers can change to the same distribution method that ustream is using.
On the other hand i didnt agree with the idea of dropping the python-librtmp dependency, it can be usefull in the future.

**Comment by beardypig** [comment]
@RosadinTV the problem with `python-librtmp` is that it is no longer maintained and had become quite hard to install on Windows machines using newer versions of Python. It is only an optional dependency and dropping it just means not using it any more, for this plugin.

**Comment by RosadinTV** [comment]
@beardypig 
With dropping the dependency i mean dont include it by default in release, but you are right, tried installing Python-librtmp in Python 3.5.2 and didnt finish, some errors ocurred .. knowing this the position is hard to take 😕

**Pull request closed without merging**
