### PR TITLE
plugins.nowtvtr: new plugin

### LINKED ISSUE #5826: plugins.foxtr: name changed to nowtvtr
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.5.1

### Description

Hello Team,
As my first message, guidlines and conducts read before, apologies if confusions and thank you for Streamlink tool project.
Since today Turkish Fox channel becomes Now Tv. Website url https://www.fox.com.tr/ name has officially changed to https://www.nowtv.com.tr/
Impacted plugin file location : https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/foxtr.py
Could someone update that python file content if possible ? Feel free to feedback me if any please, Thanks a lot, Regards

### Debug log

```text
Debug log precision get on fox.com.tr :
An error occurred: Unable to open URL: https://www.fox.com.tr/canli-yayin?m3u8
(HTTPSConnectionPool(host='www.fox.com.tr', port=443): Max retries exceeded with url: /canli-yayin?m3u8
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))))
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Resolves #5826 

- https://www.nowtv.com.tr/kunye
- https://en.wikipedia.org/wiki/NOW_(Turkish_TV_channel)

Their news channel appears to be geo-blocked, so I can't test this.

@ipstreet312, please check and see if any streams (not covered by the tests) are not working...
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback

----

```
$ ./script/test-plugin-urls.py nowtvtr
:: Finding streams for URL: https://www.nowtv.com.tr/Gaddar/bolumler
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.nowtv.com.tr/Memet-Ozer-ile-Mutfakta/bolumler
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.nowtv.com.tr/canli-yayin
:: Found streams: 360p, 480p, 720p, worst, best
:: Finding streams for URL: https://www.nowtv.com.tr/now-haber
!! Error while fetching streams
:: Finding streams for URL: https://www.nowtv.com.tr/yayin-akisi
:: Found streams: 360p, 480p, 720p, 1080p, worst, best
```

### CODE REVIEW

**Comment by ipstreet312** [comment]
Sorry, still sinces hours on how to give feedback... i dont have skills :((((( . Can someone else help us ?

**Comment by ipstreet312** [comment]
@bastimeyer : i succeded in test, please see result : 
PS C:\Users\xxxxx> streamlink https://www.nowtv.com.tr/canli-yayin best
[cli][info] Found matching plugin nowtvtr for URL https://www.nowtv.com.tr/canli-yayin
[cli][info] Available streams: 360p (worst), 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
I don't know the next step, as no more action from my side possible ? Thanks, best regards

**Comment by bastimeyer** [comment]
Well, congrats, but I was looking for feedback whether there's any content on that site which does not work with this plugin implementation. As mentioned, there are some geo-blocked streams...

**Comment by bastimeyer** [comment]
Going to merge this now... Apparently, the news channel wasn't available at the time, but it's now, and it's working fine. I couldn't find any other content that's not working, but if I'm wrong, then a new plugin issue should be opened (if it makes even sense).

**Comment by ipstreet312** [comment]
Hello @bastimeyer thank you again for your updates. Yesterday url access was Ok but since today we get Exception Error : 
`streamlink.exceptions.PluginError: Unable to open URL: https://www.nowtv.com.tr/canli-yayin (HTTPSConnectionPool(host='www.nowtv.com.tr', port=443): Max retries exceeded with url: /canli-yayin (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3b6e86d610>: Failed to resolve 'www.nowtv.com.tr' ([Errno -3] Temporary failure in name resolution)")))`
More worklow info : https://github.com/ipstreet312/freeiptv/actions/workflows/nownew.yml 
Is there a workaround or a possible fix ? Thank you, best regards

**Comment by mkbloke** [comment]
It's a DNS issue.  Only one of their name servers is returning an A record for `www.nowtv.com.tr`.

Nothing can be done about it here.

**Comment by ipstreet312** [comment]
Thanks a lot for your help contributions.
py line added : `session = streamlink.session.Streamlink(options={"ipv4": True})`
working fine finally. Bests !

**Pull request merged**
