### PR TITLE
Move docs version selection to sidebar

### LINKED ISSUE #254: Documentation doesn't match stable version
The documentation is build from master whenever there is a commit on master, which is nice for some things like errors or omissions in the docs, but not so good for new features. It is unclear which features the latest stable version supports. For example, the docs currently list bigo as a supported site, however it is only supported in the nightly/HEAD version rather than the latest tagged version (0.1.0). 

There are a couple of ways I can think of resolving this. 
1. We could have a separate repo for the docs and ask people to submit separate PRs to update the docs. This might lead to the docs going unloved as it's an extra bit of work.
2. We could build the docs only on tagged revisions. This would fix the new features only in nightlies, but we'd have to have a tag/release to fix errors and omissions in the docs. We can build multiple versions of the docs, for each tag and for the current HEAD revision (similar to the readthedocs site).
3. We could mark each feature with the version that it was added or if it is currently only supported in the nightly version. This would be more work to update the versions when we release a new version as we'd have to updated all the "this feature is only supported in the nightly version" type messages to "added in x.y.z". It's possible that some automation (sphinx magic) could be used to make the release managers life easier. 

All of these suggestions add extra work, but would ultimately would benefit the users. If anyone has any other suggestions to improve the quality of the docs they would be most welcome. 

I think the 3rd option is pretty good, but the 2nd option would be OK too. 

Thought? Suggestions?

### PR DESCRIPTION
**Pull request by bastimeyer**
Also:
- Remove home icon from "Streamlink" title
- Fix spacing and text layout in sidebar header and menu
- Remove border from active main menu list item
- Rename CSS classes (wy-side-nav-search -> wy-side-nav-header)
- Remove some unneeded CSS rules

~~**DON'T MERGE**
This is a follow up to #1684 and includes all of its current commits. I will rebase this PR once #1684 gets merged.~~

Btw, the docs theme is an unmaintainable mess and the templates and stylesheets are outdated and just terrible. Upgrading it would break all custom changes which have been applied over the time, though.

Fixes #254 and closes #1684

### CODE REVIEW

**Comment by beardypig** [comment]
Cool - I will test it out. TBH, this could be merged instead of the original - doesn't make any difference doing one at a time (I don't think).

**Comment by amurzeau** [comment]
I believe most theme files are generated from https://github.com/chrippa/sphinx_rtd_theme_violet/ which is a modified version of the read-the-docs sphinx theme.
Maybe retrieving this to remove generated files and modify .sass and other sources instead might be better while keeping some compatibility
(I don't know much about sass and other things sphinx theme use but it's an idea ^^)

**Comment by beardypig** [comment]
@amurzeau, ideally we would do that - but it's quite a bit of work. We should create an issue to track it though, so maybe someone will work on it :)

**Comment by beardypig** [comment]
@gravyboat, just merge this one and close #1684 :)

**Comment by beardypig** [comment]
@bastimeyer I messed with your original post a bit... :]

**Comment by gravyboat** [comment]
Looks great @bastimeyer, thanks!

**Comment by bastimeyer** [comment]
Now we need a new stable release to make it fully work:
https://streamlink.github.io/
https://streamlink.github.io/latest/

I'd appreciate a new release anyway because of the issue with the changed log output that can break the error detection of the Twitch GUI :)

**Comment by gravyboat** [comment]
@cdrage Would you mind doing a stable release today if you have time?

**Comment by cdrage** [comment]
@gravyboat Didn't get this message until now, but yes! I'll do a release today. :+1:

**Pull request merged**
