### PR TITLE
Support for 4K videos in YouTube

### PR DESCRIPTION
**Pull request by beardypig**
_This PR depends on #224 and should __not__ merged prior to that PR as it includes the commit on that PR._

This PR along with its parent #224, adds support for YouTube videos with resolutions >= 1080p and high frame rate videos, eg. 1080p60. To test this out you will need `ffmpeg` installed as it uses `ffmpeg` to mux the separate video and audio streams. 

Here are some videos to test out:

- https://www.youtube.com/watch?v=iNJdPyoqt8U (4K)
- https://www.youtube.com/watch?v=UceRgEyfSsc (4K HFR)
- https://www.youtube.com/watch?v=Og5-Pm4HNlI (1080p previously unavailable, see #200) 

A windows installer for this branch is available to download: [streamlink-0.1.0-youtube-4k-8b77f99.exe](https://s3.amazonaws.com/streamlink-builds/beardypig/streamlink-0.1.0-youtube-4k-8b77f99.exe).

### CODE REVIEW

**Comment by Junior1544** [comment]
Here's a question for you...

Since this uses ffmpeg, how will that effect those of us that use streamlink on a raspberry pi?

I don't know if ffmpeg is compatible with the Raspberry Pi, and will it cause an error on install if ffmpeg doesn't work right, or will just the functions that use ffmpeg not work if ffmpeg doesn't work with Raspberry Pi??

Just some thoughts I had?

**Comment by stevek123** [comment]
I know it's not related, but is it still not working with live streams? For me, when I try to watch a youtube live stream, it says that it's a HLS stream, it opens VLC, and only shows the first frame, and that's all.

**Comment by beardypig** [comment]
@Junior1544 for YouTube, if you don't have ffmpeg install it won't show you the streams that require ffmpeg :-)

@stevek123 are you using the VLC 3 beta? I believe that you need to use VLC 3 for YouTube live streams to work.

**Comment by Junior1544** [comment]
You guys are wonderful!  I really wish I could buy you a cup of coffee or
something :)

James Hauge
James Virtual Tours LLC.
http://JamesVirtualTours.com
Hauge.James@gmail.com
808-782-8461

**Comment by stevek123** [comment]
It indeed works with VLC3 nightly

**Comment by beardypig** [comment]
I have uploaded a build of the Windows installer for people to test, see the original post for the link.

**Comment by tp0** [comment]
Just checking that this isn't supposed to have support for live videos?

```streamlink https://www.youtube.com/watch?v=Ga3maNZ0x0w
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=Ga3maNZ0x0w
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)```

**Comment by beardypig** [comment]
@tp0 I can only see 1080p for that stream, the same that streamlink lists. Are live streams available in higher quality?

**Comment by tp0** [comment]
@beardypig Yes, and in Chrome 1080p60 and 720p60 are selectable in the HTML5 player for that video.

**Comment by beardypig** [comment]
@tp0 I will see if the 60 fps live versions can be added :-)

**Comment by beardypig** [comment]
Looks like live streams use DASH for higher frame rates, when DASH is supported we can add higher frame rate live streams for YouTube.

**Comment by Vangelis66** [comment]
If still on WinXP/WinVista, you can try the updated installer [here](https://streamlink-builds.s3.amazonaws.com/beardypig/streamlink-0.1.0-youtube-4k-6803573.exe); 
see also https://github.com/streamlink/streamlink/pull/224#issuecomment-263851146; contains the fix for https://github.com/streamlink/streamlink/pull/224#issuecomment-263735849, too :+1:

**Comment by gravyboat** [comment]
Thanks @beardypig!

**Pull request merged**
