### PR TITLE
Add plugin for www.kingkong.com.tw

### PR DESCRIPTION
**Pull request by littlebtc**
This pull request will add a plugin for www.kingkong.com.tw, a game streaming website in Taiwan.

This plugin is mostly modified from the one of Douyutv.

Example of stream URLs can be found in the Kingkong front page.
A VOD URL example is provided FYI:
https://www.kingkong.com.tw/video/2152350G38400MJTU

### CODE REVIEW

**Comment by gravyboat** [comment]
@littlebtc This looks pretty good! Do you think you could add some tests for this plugin?

**Comment by littlebtc** [comment]
Added tests for `can_handle_url`.

**Comment by beardypig** [comment]
Looks fine, some negative test cases would be good too. They are useful to make sure the plugin isn’t matching sites that it shouldn’t. Thanks @littlebtc

**Comment by gravyboat** [comment]
Thanks @littlebtc!

**Pull request merged**
