### PR TITLE
Ignore WinError 10053 / WSAECONNABORTED

### PR DESCRIPTION
**Pull request by back-to**
A nice solution for this error was found in gevent/gevent#1000

Fixed streamlink/streamlink#916
Fixed streamlink/streamlink#975
Fixed streamlink/streamlink#1236

Maybe this will help streamlink/streamlink-twitch-gui#467

### CODE REVIEW

**Comment by beardypig** [comment]
Nice. Seems like it would work :) 
Would be nice to get some verification from a couple of users before closing those issues though.

**Comment by back-to** [comment]
This PR can be easy tested **on windows**

```
streamlink --player-external-http --player-external-http-port 9999 --player-continuous-http twitch.tv/rocketbeanstv best
```

open **http://127.0.0.1:9999/** in the browser(firefox) and click on abort(download)

**without** this PR it will **end streamlink**,
**with** this PR it should **just close** the stream and **not end streamlink**.

**Comment by beardypig** [comment]
@back-to yeah. I just wanted to get some verification that it fixed the issues that would be closed by merging this PR. I tested PotPlayer just now and it does fix it. Good job 🤗

**Comment by skulblakka** [comment]
Just tested it with mpv. Issue seems to be fixed with this PR.

**Comment by bastimeyer** [comment]
Looks like this fixes the issue.
Is this ready for merging? We have 4 hours to merge this (until midnight UTC+0) so that it gets included in the next nightly build, which should help us getting a few more verifications.

**Comment by gravyboat** [comment]
Thanks for the reviews everyone. @bastimeyer apologies on the delay. @back-to Thanks for fixing this up.

**Comment by bastimeyer** [comment]
> apologies on the delay

?
It's all fine... I thought the nightly builds were scheduled by TravisCI at midnight UTC+0, but it's not the case. Would be quite stupid of them triggering builds of all registered projects at the same time. Nightlies are being built at 18:19:49 here (probably because of the time the daily cron job was created).

Thanks for merging though, @gravyboat, and thanks @back-to for the fix.

**Comment by Tikounet** [comment]
I confirm this fixes the issue with PotPlayer (916).
Thanks !

**Pull request merged**
