### PR TITLE
Drop support for EOL Python 2

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/streamlink/streamlink/issues/2896.

Also upgrade syntax for Python 3 using https://github.com/asottile/pyupgrade.

### CODE REVIEW

**Comment by bastimeyer** [comment]
Thanks for taking the time doing this and submitting the pull request!
Oh boy, that are a ton of changes (+1,859 −2,728)...

Just a couple of early thoughts from my side after a first quick review:

- It would probably be better to split this up into more commits, for reviewing reasons. One commit for each operation `pyupgrade` supports, for example, if it's possible. This would also be better for the commit history, git blame, etc...
- The string format related changes are probably unneeded or rather too much, as they only make explicit string templates implicit. Also, there's the 3.5 support drop in September, which enables the usage of f-strings once we go >=3.6, making these changes therefore a bit redundant.
- The included flashmedia package still has a compat file with py2 stuff, even though some of its files were modified.
- The order of imports in some modules has changed after the removal of the compat module. There's no linting rule for that here and not really important now, just wanted to mention it though.
- By removing one python version from the build matrix in the GH workflow file, the CodeCov comment threshold also needs to be changed in its config file. (not important now)

**Comment by beardypig** [comment]
I would say the first change should be to update the docs and disallow Python 2 installs by updating `setup.py` and `setup.cfg` to remove the Python 2 specifics.

I believe that `setup.cfg` needs to be updated to remove this:
```
[wheel]
universal = 1
```

Perhaps a guard in `setup.py` needs to be added, something like
```
if sys.version_info < (3, 5):
    sys.exit('streamlink is only supported on Python 3.5 and later')
```

Once it is only possible to install `streamlink` on Python 3, then we can remove the Python 2 cruft. 

It would be nice to target Python 3.6+, but I don't know if that will be popular :)

**Comment by hugovk** [comment]
Thanks for the comments! Yeah, it's a big one!

PR https://github.com/streamlink/streamlink/pull/2920 is a minimal version of this, with the first commit from here, plus a few bits from the last commit here, plus @beardypig's suggestions.

Then we can deal with fine-grained pyupgrade and the compat replacements separately.

> The order of imports in some modules has changed after the removal of the compat module. There's no linting rule for that here and not really important now, just wanted to mention it though.

I've found https://github.com/timothycrosley/isort/ great for taking the hassle out this.

**Comment by bastimeyer** [comment]
#3270 already has all compat imports removed.

**Pull request closed without merging**
