### PR TITLE
docs: add minimalist code of conduct

### PR DESCRIPTION
**Pull request by bastimeyer**
Personally, I'm not a fan of Code of Conducts, as it's totally unnecessary to tell adults how to behave themselves :roll_eyes: :roll_eyes: :roll_eyes:, but unfortunately it's a requirement for being able to apply to the Netlify open source plan upgrade (see #3420).

That's why I'm proposing the "Minimalist Code of Conduct", which basically only tells the already implied and known rules of every community, "be nice and respectful", nothing more.

An alternative to the "Minimalist Code of Conduct" could be the "No Code of Conduct":
https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md

Either way, I don't think there's any reason to fight or argue about adding a CoC of such kind. It doesn't change anything here, so if one doesn't like this, they can just ignore it.

### CODE REVIEW

**Comment by back-to** [comment]
> "No Code of Conduct"

it has less text, I would prefer it over the long text version.

**Comment by bastimeyer** [comment]
I'm fine with either one. I just chose this one for this PR due to https://github.com/streamlink/streamlink/pull/3420#issuecomment-748528661

**Comment by beardypig** [comment]
I prefer the one you have suggested rather than the "no code of conduct".

**Comment by gravyboat** [comment]
As I mentioned in the other thread I prefer this one as well. Let's get this merged unless there are other concerns around wording.

**Comment by bastimeyer** [comment]
Please wait until 2.0.0

**Pull request merged**
