### PR TITLE
plugin.youtube: bug fix for YouTube live streams check

### LINKED ISSUE #2539: Unable to get the YT Live best quality hls stream url in sometimes
##  Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

YouTube seems to have changed their code on July 11, especially in terms of live streaming.

The first problem is the inability to parse the video id of the user/channel 's live broadcast room address.
```
> streamlink -l debug -o test.ts https://www.youtube.com/rocketbeanstv/live best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/rocketbeanstv/live
error: Could not find a video on this page
```
Try to fix in #2538 .

Another issue is that if a live stream video have 1080p and 1080p60 at the same time, it can't get the hls url for 1080p60. (Maybe it doesn't exist at all?)
It will try to get the http substream and program exit directly, only one frame/segment of data can be obtained (about 500k).

I found that youtube-dl has the same problem. https://github.com/ytdl-org/youtube-dl/issues/21734

### Reproduction steps / Explicit stream URLs to test

1. Looking for a live broadcast room with 1080p60 quality options
2. Try to download the video at the best quality

### Log output

Try to download best quality (1080p60) with format code 299
```
$ streamlink -o test.ts https://www.youtube.com/rocketbeanstv/live best -l debug
[cli][debug] OS:         Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1+39.g04f0b0d
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/rocketbeanstv/live
[plugin.youtube][debug] Video ID from currentVideoEndpoint
[plugin.youtube][debug] Using video ID: E-MsayZ_Epw
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 140 = 1080p
[plugin.youtube][debug] MuxedStream: v 299 a 140 = 1080p60
[utils.l10n][debug] Language code: zh_CN
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
[stream.ffmpegmux][debug] Opening http substream
[stream.ffmpegmux][debug] Opening http substream
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-74555-150 -i /tmp/ffmpeg-74555-765 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-74555-150
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-74555-765
[cli][debug] Pre-buffering 8192 bytes
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/ffmpeg-74555-765
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/ffmpeg-74555-150

[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
```

If you choose 1080p quality, it can download as normal.
```
$ streamlink -o test.ts https://www.youtube.com/rocketbeanstv/live 1080p -l debug
[cli][debug] OS:         Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1+39.g04f0b0d
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/rocketbeanstv/live
[plugin.youtube][debug] Video ID from currentVideoEndpoint
[plugin.youtube][debug] Using video ID: E-MsayZ_Epw
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 140 = 1080p
[plugin.youtube][debug] MuxedStream: v 299 a 140 = 1080p60
[utils.l10n][debug] Language code: zh_CN
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 72157; Last Sequence: 75755
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 75753; End Sequence: None
[stream.hls][debug] Adding segment 75753 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 75754 to queue
[stream.hls][debug] Adding segment 75755 to queue
```

After the live broadcast is over, it can be download normally.

### LINKED ISSUE #2541: youtube error when linking channel's live with unknown YT Video ID
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When linking a channel's live link without knowing the Video ID, you get "error: Could not find a video on this page"  It stopped working today.  It works with the YT link with a video ID but this is for a script with an unknown video ID.

### Reproduction steps / Explicit stream URLs to test

1. ...Try command "streamlink https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ/live"   (Sky News Broadcast)
2. ...Try command "streamlink https://www.youtube.com/channel/UCUMZ7gohGI9HcU9VNsr2FJQ/live
3. ...

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ/live
error: Could not find a video on this page

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by jitingcn**
close #2539.

Before this patch
```
PS E:\> streamlink -o test.ts -l debug https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live
[plugin.youtube][debug] Video ID from currentVideoEndpoint
[plugin.youtube][debug] Using video ID: 4EA6OIYo3gM
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 140 = 1080p
[plugin.youtube][debug] MuxedStream: v 299 a 140 = 1080p60
[utils.l10n][debug] Language code: zh_CN
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
[stream.ffmpegmux][debug] Opening http substream
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i \\.\pipe\ffmpeg-21932-944 -i \\.\pipe\ffmpeg-21932-651 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\ffmpeg-21932-944
[stream.ffmpegmux][debug] Pipe copy complete: \\.\pipe\ffmpeg-21932-944
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\ffmpeg-21932-651
[cli][debug] Pre-buffering 8192 bytes
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][error] Try 1/1: Could not open stream <Stream()> (No data returned from stream)
error: Could not open stream <Stream()>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
```

After
```
PS \PycharmProjects\streamlink> streamlink -o test.ts -l debug https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1+39.g6e926c7.dirty
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCKVlixycWmapnGQ_wht4cHQ/live
[plugin.youtube][debug] Video ID from currentVideoEndpoint
[plugin.youtube][debug] Using video ID: 4EA6OIYo3gM
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: zh_CN
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 801
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 799; End Sequence: None
[stream.hls][debug] Adding segment 799 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 800 to queue
[stream.hls][debug] Adding segment 801 to queue
```

### CODE REVIEW

**Comment by thpryrchn** [comment]
I applied this, and it works for my live stream!!! Thanks! Hopefully is will be merged soon so I won't have it as a hack.

**Comment by DavidOfOregon** [comment]
Works for me too, TY, TY, TY!

**Comment by gravyboat** [comment]
Looks good to me as well, thanks @jitingcn.

**Comment by themysciraa** [comment]
Hi, how do I use this patch? Please teach me

**Comment by beardypig** [comment]
@themysciraa you gotta install the nightly/dev version by way of the nightly [Windows Installer](https://streamlink.github.io/install#windows-binaries) or [using pip](https://streamlink.github.io/install#source-code).

**Comment by themysciraa** [comment]
@beardypig Thank you! You're my life savior!

**Pull request merged**
