### PR TITLE
release: 4.3.0

### PR DESCRIPTION
**Pull request by bastimeyer**
Anything missing? Any unsubmitted changes?

Release date is set for today, but I will update each day at midnight UTC if it's not ready yet, as usual.

Unmerged PRs:
- #4733

### CODE REVIEW

**Comment by gravyboat** [comment]
@bastimeyer The only thing that's worth discussing prior to merge and release is the issue @scowalt brought up here: https://github.com/streamlink/streamlink-chocolatey/pull/72#pullrequestreview-1072016449 about the way the windows releases are tagged that creates an inconsistency between the installer and the chocolatey package.

**Comment by bastimeyer** [comment]
Changelog updated and release date changed to tomorrow.

> the way the windows releases are tagged

The Windows releases are tagged correctly, like any other packaging version scheme, namely `major.minor.patch-pkgversion`. If chocolatey doesn't support this, then it's not our fault.

**Comment by gravyboat** [comment]
@bastimeyer Yes I agree and so does Scowalt that the versioning used is appropriate and that the other chocolatey packaging utilities are in the wrong, just wanted to bring it up 👍

**Comment by gravyboat** [comment]
@bastimeyer If there isn't anything blocking let's do the release today so maybe swap back the date? I was planning on cutting the new tag as soon as we resolved the above concern.

**Comment by bastimeyer** [comment]
> let's do the release today

I would prefer having it tagged tomorrow, because I will need to update the Windows builds and AppImages afterwards, and I don't want to do this now because I'm not at my desktop computer right now and don't have everything set up here. There also haven't been any comments from anyone else, in case something's missing.

**Comment by gravyboat** [comment]
Okay that's fine by me. Do you want me to try and cut the release in the morning tomorrow (PST)? I can do so before work if that helps.

**Comment by bastimeyer** [comment]
Sure

**Pull request merged**
