### PR TITLE
stream.hls_playlist: removed int check from PROGRAM-ID

### PR DESCRIPTION
**Pull request by back-to**
```
error: Failed to parse playlist: invalid literal for int() with base 10: 'be38842539da4fe7ad5265ec9ced7153'
```

https://rutube.ru/video/11bbbec75a2ceb8cf446ad16813c6eec/

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=700000, CODECS="avc1.42E01E,mp4a.40.5"
288p.m3u8?i=512x288_700000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=700000, CODECS="avc1.42E01E,mp4a.40.5"
288p.m3u8?i=512x288_700000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=1300000, CODECS="avc1.42c01f,mp4a.40.5"
360p.m3u8?i=640x360_1300000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=1300000, CODECS="avc1.42c01f,mp4a.40.5"
360p.m3u8?i=640x360_1300000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=2000000, CODECS="avc1.4D401F,mp4a.40.5"
576p.m3u8?i=896x504_2000000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=2000000, CODECS="avc1.4D401F,mp4a.40.5"
576p.m3u8?i=896x504_2000000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=3600000, CODECS="avc1.640029,mp4a.40.5"
720p.m3u8?i=1280x720_3600000
#EXT-X-STREAM-INF:PROGRAM-ID=be38842539da4fe7ad5265ec9ced7153, BANDWIDTH=3600000, CODECS="avc1.640029,mp4a.40.5"
720p.m3u8?i=1280x720_3600000
```

### CODE REVIEW

**Comment by beardypig** [comment]
I don't think `PROGRAM-ID` is currently used anywhere, so maybe it's better to treat it as a string?

**Comment by back-to** [comment]
how do you prefer it

1. completely removed

```diff
--- a/src/streamlink/stream/hls_playlist.py
+++ b/src/streamlink/stream/hls_playlist.py
@@ -67,11 +67,6 @@ class M3U8Parser(object):
 
     def create_stream_info(self, streaminf, cls=None):
         program_id = streaminf.get("PROGRAM-ID")
-        if program_id:
-            try:
-                program_id = int(program_id)
-            except ValueError:
-                program_id = ""
 
         bandwidth = streaminf.get("BANDWIDTH")
         if bandwidth:
```

2. just `str()`
3. `str()` from `from .compat import str`

```diff
--- a/src/streamlink/stream/hls_playlist.py
+++ b/src/streamlink/stream/hls_playlist.py
@@ -68,10 +68,7 @@ class M3U8Parser(object):
     def create_stream_info(self, streaminf, cls=None):
         program_id = streaminf.get("PROGRAM-ID")
         if program_id:
-            try:
-                program_id = int(program_id)
-            except ValueError:
-                program_id = ""
+            program_id = str(program_id)
```

**Comment by beardypig** [comment]
I think 1. is fine, leave it untouched - later if we need to we can change it.

**Comment by beardypig** [comment]
Of course, there are some tests that expect it to be an int (`test_hls_playlist.TestHLSPlaylist`).

**Comment by back-to** [comment]
yes, I just use `'1'` for now as it's **not used anywhere in the code** as an **int**

but https://github.com/streamlink/streamlink/pull/1646 will be affected

**Comment by beardypig** [comment]
I'll fix those once this is merged :)

**Comment by gravyboat** [comment]
Thanks @back-to and @beardypig.

**Pull request merged**
