### PR TITLE
plugins.ceskatelevize: Fix for https issues

### PR DESCRIPTION
**Pull request by back-to**
They now use **https** but it is _invalid_ for `requests`,
so we need to use it but ignore it.

---

There region block message is now played as the video,
but it can't be detected if it is blocked from there API call.

If you don't want the region block message video,
this command closes Streamlink faster `--hls-segment-ignore-names  "/0.k,/1.k"`

---

Added some trace logs

---

closes https://github.com/streamlink/streamlink/issues/1955

@remek30

### CODE REVIEW

**Comment by remek30** [comment]
How does the correct plugin look now so that I can test it?

**Comment by back-to** [comment]
@remek30 

you can replace your `ceskatelevize.py` file with this new file

https://raw.githubusercontent.com/back-to/streamlink/10758774a0f556839ffe6114fc7c6e6dfd98846f/src/streamlink/plugins/ceskatelevize.py

**Comment by remek30** [comment]
@back-to 

I tested this plugin with what you provided on this link ct24: #SERVICE 4097: 0: 1: 65: 1: 48: 0: 0: 0: 0: http% 3a // 127.0.0.1% 3a8088 / https% 3a // ct24.ceskatelevize.cz/#live:ČT24 HD
#DESCRIPTION ČT24 HD

but I still do not have any picture or sound - please help me and tell me what is wrong with this link.

**Comment by back-to** [comment]
@remek30 
try

- https://www.ceskatelevize.cz/porady/ct24/
- https://ct24.ceskatelevize.cz/

and if it doesn't work, provide the error log.

---

```
$ streamlink "https://ct24.ceskatelevize.cz/" best
[cli][info] Found matching plugin ceskatelevize for URL https://ct24.ceskatelevize.cz/
[plugin.ceskatelevize][warning] SSL certificate verification is disabled.
[cli][info] Available streams: 628k (worst), 1160k, 2176k, 3712k (best)
[cli][info] Opening stream: 3712k (hls)
[cli][info] Starting player: /usr/bin/mpv
```

**Comment by remek30** [comment]
@back-to  

Thank you very much, now everything works as it should

**Comment by gravyboat** [comment]
Good stuff @back-to.

**Pull request merged**
