### PR TITLE
Add support for some Bulgarian live streams

### PR DESCRIPTION
**Pull request by beardypig**
As requested in #374.

BTV requires a login, the username and password can be set with `--btv-username` and `--btv-password`. 

Should support for the following sites:
- eurocom.bg/live
- bgonair.bg/tvonline
- bitelevision.com/live
- kanal3.bg/live
- nova.bg/live
- tv.bnt.bg/bntworld
- tv.bnt.bg/bnt1/hd
- tv.bnt.bg/bnt1/16x9
- tv.bnt.bg/bnt2/16x9
- btv.bg/live (requires login)

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks @beardypig.

**Comment by anchev** [comment]
Can you please add support also for the other programs which are available on http://bul-tv.com/?

**Comment by bastimeyer** [comment]
@anchev This pull request has been closed more than a year ago. If you want to request a new plugin, please open a new issue and follow the guidelines.

**Comment by anchev** [comment]
Thanks. I will try to do that.

**Pull request merged**
