### PR TITLE
Fix for goodgame.ru plugin

### LINKED ISSUE #128: Goodgame moved to the new version of the site
Goodgame moved to the new version of the site (https://github.com/chrippa/livestreamer/issues/1513 ; https://github.com/chrippa/livestreamer/issues/1518 ; https://github.com/chrippa/livestreamer/pull/1527). Fix the plugin please.

### PR DESCRIPTION
**Pull request by beardypig**
Patch to fix the goodgame.ru plugin courtesy of @intact, fixes #128

### CODE REVIEW

**Comment by intact** [comment]
This change is incomplete (one line is missing). :)

https://github.com/intact/livestreamer/blob/91ad3aa98cf3dd355f78b106449adc47729c8977/src/livestreamer/plugins/goodgame.py#L38

**Comment by beardypig** [comment]
That change was already in the plugin :)

**Comment by gravyboat** [comment]
Thanks @beardypig.

**Comment by flijloku** [comment]
@beardypig It is a pity that you have removed the part relating to the protection against DDoS. It helped to watch the stream when enabled protection from DDoS on the site and may be helped in the future. Or I'm wrong?

**Comment by beardypig** [comment]
@flijloku I just pulled the changes by @intact, perhaps @intact can answer your question.

**Comment by flijloku** [comment]
@beardypig https://github.com/chrippa/livestreamer/issues/1518#issuecomment-256435488 - so I think @intact  will not mind. I do not understand why it was removed from the plugin.

**Comment by beardypig** [comment]
@flijloku OK! I can add that back in.

**Comment by flijloku** [comment]
@beardypig Thank you :)

**Pull request merged**
