### PR TITLE
plugins.ntv: remove plugin

### LINKED ISSUE #5602: plugins.ntv:  it have dead today
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.2.1+23.ga39816fb

### Description

Yet yesterday it was working but now it has reached its end of life due to site changing. Fortunately, it works with static URL:

`http://cdn.ntv.ru/ntv-msk_hd/index.m3u8`

I have constructed this URL from very similar URLs taken from under the hood of the site.

So, we have 3 options:

1. Remove the plugin.
2. Mark it as broken.
3. Incorporate this static URL into plugin code as what to be  returned.

I guess all of those decisions would be temporary.

### Debug log

```text
streamlink --loglevel=debug http://www.ntv.ru/air/
[cli][debug] OS:         Linux-6.5.0-2-amd64-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.0.11 19 Sep 2023
[cli][debug] Streamlink: 6.2.1+23.ga39816fb
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.16.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 1.26.17
[cli][debug]  websocket-client: 1.2.3
[cli][debug] Arguments:
[cli][debug]  url=http://www.ntv.ru/air/
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --player-args=--quiet
[cli][debug]  --default-stream=['best']
[cli][info] Found matching plugin ntv for URL http://www.ntv.ru/air/
error: No playable streams found on this URL: http://www.ntv.ru/air/
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Resolves #5602 

Static HLS URLs:

```sh
$ curl -sSL 'https://www.ntv.ru/api/new/widgets/air/schedule/index.jsp?channel=ntv' \
  | jq -r '.data.src'
https://cdn.ntv.ru/ntv0_hd/index.m3u8?filter.tracks=v3v4v5a1l1t1
```

```sh
$ curl -sSL 'https://www.ntv.ru/api/new/widgets/air/source/index.jsp' \
  | jq -r '.data.channels[] | .src'
https://cdn.ntv.ru/live7/index.m3u8
https://cdn.ntv.ru/th_style/index.m3u8
https://cdn.ntv.ru/th_serial/index.m3u8
https://cdn.ntv.ru/th_pravo/index.m3u8
https://cdn.ntv.ru/ntv0_hd/rewind-7150.m3u8?filter.tracks=v2v1v3v4v5a1l1t1
https://cdn.ntv.ru/unknown_russia/index.m3u8
```

### CODE REVIEW

**Comment by bastimeyer** [comment]
It doesn't let me merge this from the PR UI here...

> This branch cannot be rebased due to too many changes

???

```
$ git show --stat --format=reference | cat
7929dce2 (plugins.ntv: remove plugin, 2023-10-11)

 src/streamlink/plugins/ntv.py | 31 -------------------------------
 tests/plugins/test_ntv.py     | 16 ----------------
 2 files changed, 47 deletions(-)

$ git log --format=reference HEAD~2..HEAD | cat
7929dce2 (plugins.ntv: remove plugin, 2023-10-11)
0490c4ef (plugins.vlive: remove plugin, 2023-10-09)

$ curl -sSL 'https://api.github.com/repos/streamlink/streamlink/commits?per_page=1' | jq -r '.[0].sha'
0490c4eff16d3afad1566647a1eb3b91a1f4f59f

$ curl -sSL 'https://api.github.com/repos/streamlink/streamlink/commits/0490c4eff16d3afad1566647a1eb3b91a1f4f59f/branches-where-head' | jq -r '.[] | .name'
master
```

**Comment by mkbloke** [comment]
Yes.  I was going to merge it about 5 minutes ago, but I saw that and thought I'd leave it well alone, not understanding why it's saying that...

**Comment by bastimeyer** [comment]
It's a bug according to GH community discussions. I could fast-forward this commit onto master (since the branch-protection rules require passing tests, which this commit does have), but I will instead submit a bug report to them first...

**Review by gravyboat — APPROVED** [review]

**Comment by bastimeyer** [comment]
With a new commit being pushed to master, it allows me to rebase-merge again...

**Pull request merged**
