### PR TITLE
Release 1.3.1

### PR DESCRIPTION
**Pull request by bastimeyer**

### CODE REVIEW

**Comment by bastimeyer** [comment]
**Don't merge this yet**, it's just a template. The 2020 and docs fix PRs need to be merged first and maybe we should try to squeeze in one or two more plugin fixes.
And if that's done, I will need to update the changelog.

**Comment by gravyboat** [comment]
The other 2 PRs are merged.

**Comment by bastimeyer** [comment]
Rebased...
If you want to wait for further input or plugin fixes, like YT for example (which seems to be partially broken), then let's wait. If not and you're also fine with the changelog, then please merge and push a new release-tag.

**Comment by gravyboat** [comment]
@bastimeyer Let's wait, otherwise we'll just have to do another release any way.

**Comment by bastimeyer** [comment]
@gravyboat I've set the date of the changelog to today, so if you (or anyone else) feels like merging this and tagging the release, please go for it. We've been waiting for far too long now. MPV introduced a breaking change which we have to fix, no matter if there are still some issues with certain plugins like YT.

**Comment by gravyboat** [comment]
@bastimeyer Tag is created, thanks for the update: https://github.com/streamlink/streamlink/tree/1.3.1

**Pull request merged**
