### PR TITLE
plugins.showroom: cleanup

### PR DESCRIPTION
**Pull request by back-to**
- remove RTMP
- cleanup room_id
- error message for 403 eror on playlist

### CODE REVIEW

**Comment by bastimeyer** [comment]
```
[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/adbbc5792409
[plugins.showroom][debug] {'is_live': 1, 'room_id': 374348, 'room': {'content_region_permission': 1, 'is_free': 0}}
[utils.l10n][debug] Language code: en_US
error: Failed to parse playlist: invalid Content-Type image/png
```

**Comment by back-to** [comment]
> error: Failed to parse playlist: invalid Content-Type image/png

you are geo-blocked, works with an IP from HongKong

**Comment by bastimeyer** [comment]
Yes, I am aware. The HLS playlist shows a PNG when geo-blocked. The plugin shouldn't return an error though.

If there's no other way of checking whether the user is geo-blocked, the plugin should send a `HEAD` request first to see what the content-type header is, so that `HLSStream.parse_variant_playlist` doesn't raise an error.

Btw, `validate.text` should be replaced with `str` in the validation schema.

**Comment by back-to** [comment]
`HEAD` won't work, it is always `error 405`
only `GET` will work

**Pull request merged**
