### PR TITLE
Tiktok plugin

### PR DESCRIPTION
**Pull request by NeftaliYagua**
Tiktok plugin for public streams.

### CODE REVIEW

**Comment by NeftaliYagua** [comment]
Test is passed
Captura de pantalla 2023-07-21 104619
Captura de pantalla 2023-07-21 104716

**Comment by NeftaliYagua** [comment]
Github actions tests is passed
https://github.com/NeftaliYagua/streamlink/actions/runs/5624098505

**Review by bastimeyer — CHANGES_REQUESTED** [review]
Thanks for the PR, but this won't work.

I should've been more clear in the PR you've opened previously and which I closed with a link to previously closed issues. The streams don't work because they require additional query string parameters with a specific signature. You'll need an account for that site and retrieve/calculate the correct signatures. Otherwise, their servers simply won't return any data on the HTTP request of the HLS multivariant playlist.

```
$ streamlink -l trace --output=/dev/null --http-timeout=10 'https://www.tiktok.com/@kbc_news/live' best
[21:58:45.825872][cli][debug] OS:         Linux-6.4.4-1-git-x86_64-with-glibc2.37
[21:58:45.825994][cli][debug] Python:     3.11.3
[21:58:45.826044][cli][debug] Streamlink: 6.0.0+7.gebb1a767
[21:58:45.826487][cli][debug] Dependencies:
[21:58:45.827110][cli][debug]  certifi: 2023.5.7
[21:58:45.827432][cli][debug]  isodate: 0.6.1
[21:58:45.827689][cli][debug]  lxml: 4.9.3
[21:58:45.828098][cli][debug]  pycountry: 22.3.5
[21:58:45.828343][cli][debug]  pycryptodome: 3.18.0
[21:58:45.828654][cli][debug]  PySocks: 1.7.1
[21:58:45.828924][cli][debug]  requests: 2.31.0
[21:58:45.829171][cli][debug]  trio: 0.22.1
[21:58:45.829402][cli][debug]  trio-websocket: 0.10.3
[21:58:45.829618][cli][debug]  typing-extensions: 4.7.1
[21:58:45.829880][cli][debug]  urllib3: 2.0.3
[21:58:45.830135][cli][debug]  websocket-client: 1.6.1
[21:58:45.830239][cli][debug] Arguments:
[21:58:45.830276][cli][debug]  url=https://www.tiktok.com/@kbc_news/live
[21:58:45.830308][cli][debug]  stream=['best']
[21:58:45.830345][cli][debug]  --loglevel=trace
[21:58:45.830383][cli][debug]  --player=mpv
[21:58:45.830418][cli][debug]  --output=/dev/null
[21:58:45.830463][cli][debug]  --http-timeout=10.0
[21:58:45.830639][cli][info] Found matching plugin tiktok for URL https://www.tiktok.com/@kbc_news/live
[21:58:46.743924][plugins.tiktok][info] Stream status: active
[21:58:46.744601][cli][info] Available streams: origin, 360p (worst), 540p, 720p, 720p60 (best)
[21:58:46.744717][cli][info] Opening stream: 720p60 (hls)
[21:58:46.744890][cli][info] Writing output to
/dev/null
[21:58:46.744956][cli][debug] Checking file output
[21:58:46.745605][stream.hls][debug] Reloading playlist
[21:58:46.745738][cli][debug] Pre-buffering 8192 bytes
[21:59:14.027429][stream.hls][error] Unable to open URL: https://pull-hls-f16-tt03.fcdn.eu.tiktokcdn.com/game/stream-7257017215407475457_hd560/index.m3u8 (HTTPSConnectionPool(host='pull-hls-f16-tt03.fcdn.eu.tiktokcdn.com', port=443): Read timed out. (read timeout=10.0))
[21:59:14.027586][stream.segmented][debug] Closing worker thread
[21:59:14.027658][stream.segmented][debug] Closing writer thread
[21:59:14.250554][cli][error] Try 1/1: Could not open stream <HLSStream ['hls', 'https://pull-hls-f16-tt03.fcdn.eu.tiktokcdn.com/game/stream-7257017215407475457_hd560/index.m3u8']> (No data returned from stream)
error: Could not open stream <HLSStream ['hls', 'https://pull-hls-f16-tt03.fcdn.eu.tiktokcdn.com/game/stream-7257017215407475457_hd560/index.m3u8']>, tried 1 times, exiting
[21:59:14.251024][cli][info] Closing currently open stream...
```

There are also at least a million linting and code style issues, as well as general plugin implementation issues which I'm not going to comment on.

Since I don't want to be involved in anything with that platform (I don't have any nice words for it), there won't be any assistance from my side.

**Comment by gravyboat** [comment]
@bastimeyer Let's close this. If people want to side load they can but I don't see any reason to keep this open as we won't add it any way.

**Comment by i-cant-git** [comment]
@NeftaliYagua thank you for this.

> You'll need an account for that site
YT-DLP can download live streams without any account.

**Comment by i-cant-git** [comment]
@NeftaliYagua thank you for this.

> You'll need an account for that site

YT-DLP can download live streams without any account so this is false. @bastimeyer

**Comment by i-cant-git** [comment]
@NeftaliYagua thank you for this.

> You'll need an account for that site

[YT-DLP](https://github.com/yt-dlp/yt-dlp/blob/2023.07.06/yt_dlp/extractor/tiktok.py) can download live streams without any account. @bastimeyer

Please re-consider this pull request. 🙏

**Comment by aibi786** [comment]
where's the plugin code?

**Comment by NeftaliYagua** [comment]
> where's the plugin code?

Your need clone and execute
gh pr checkout 5459

**Pull request closed without merging**
