### PR TITLE
Contributing guidelines

### PR DESCRIPTION
**Pull request by sbstp**
This is a PR to create [contributing guidelines](https://github.com/blog/1184-contributing-guidelines), one of the main things I want is to keep a list of known issues in there so that we don't get bugs out of our control reported over and over again. If you guys think of other known issues please let me know and I'll add it to this PR.

### CODE REVIEW

**Comment by beardypig** [comment]
There are some known issues on the [players](https://streamlink.github.io/players.html#known-issues-and-workarounds) page of the docs.

What do you guys think of including an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)?

**Comment by sbstp** [comment]
Hmm, maybe we should just link to this.

**Comment by beardypig** [comment]
Yeah, maybe that's better :-)

**Comment by gravyboat** [comment]
Looks good to me, thanks!

**Pull request merged**
