### PR TITLE
plugins.booyah: new plugin

### LINKED ISSUE #3567: Booyah.live
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Booyah.live is a gaming streaming platfmorm, just like Twitch. It also hosts the official broadcast of the Loading TV channel online.

### Example stream URLs

1. https://booyah.live/loading52x
2. https://booyah.live/nfa
3. https://booyah.live/levelup

### Additional comments, etc.

No login required, no DRM, no geo-block.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by mkbloke**
WIP:
- [ ] Fix clips

closes #3567

### CODE REVIEW

**Comment by gravyboat** [comment]
So I just looked at this site and it seems like every single stream is just Fortnite and Fortnite drops? Is this site associated with Epic in any way? I don't see much of a point in supporting this website when you (presumably) have to be logged in to get drops and the plugin doesn't support that. If the chat wasn't active I would believe most of these streams were scams/bots.

**Comment by mkbloke** [comment]
@gravyboat, I can't really answer any of your questions because I'm not a gamer.  I therefore could not recognise the games being played, nor do I know what drops are...

The privacy page on the website states that it's run by 'Garena International I Private Limited', which I think, via a quick search is this company: https://en.wikipedia.org/wiki/Garena

A whois lookup on the domain does not reveal anything - all the registrant details are redacted for privacy.

I just looked at the site and thought it appeared to meet all the requirements for a plugin...

**Comment by gravyboat** [comment]
@mkbloke Yeah I agree it meets the requirements, I'll ping the original requester. @potterface do people actually watch this site without being logged in? When I looked at it there's nothing but fortnite drop streams which seem to require login.

**Comment by bastimeyer** [comment]
How come that if I google this site to get some more informations, I find the Streamlink issue thread on the first page, even while using incognito mode and using a proxy? The site apparently just went live in January, and just like every other Twitch clone in the past 10 years, it'll be dead within a couple of months, because there's no audience, regardless of which company is behind it (see Mixer and Microsoft).

**Comment by potterface** [comment]
> @mkbloke Yeah I agree it meets the requirements, I'll ping the original requester. @potterface do people actually watch this site without being logged in? When I looked at it there's nothing but fortnite drop streams which seem to require login. It meets the requirements to be added but is there any actual content on this that isn't just getting people to watch for drops?

This website is the official streaming platform for a game called "Free Fire", which is very popular in Brazil and Latin America. It was created last year and it very well known in Brazil and Latin America.

**Comment by gravyboat** [comment]
@bastimeyer Let's make a decision on this. I've just now checked the site and growth on it seems pretty stagnant and there's fewer than 10000 total viewers across all the streamers on the front page. Looking at the chat of the top streamer most of the chat is spamming about following, free currency, etc. so I have no idea how many of the viewers are bots. I don't think it's worth adding in considering no one else has asked for it, but I also realize that I'm often the outlier when it comes to adding more plugins.

**Comment by bastimeyer** [comment]
@gravyboat Not sure, but there seems to be enough user activity, even though there is not a huge variety of streams/streamers. The site is about one single game and according to its [wikipedia article](https://en.wikipedia.org/wiki/Garena_Free_Fire) the company behind it has made huge profits from it. I can't tell what this means for the streaming site, but it doesn't look like it's going offline that soon. The focus on item drops is however a concern and I am not sure if a streaming site with gaming as topic but without any variety (without judging the content) brings any value to Streamlink other than being able to "view-bot" for item drops or popularity.

**Comment by gravyboat** [comment]
@bastimeyer Alright let's merge it for now since it doesn't violate any of the existing rules. If we need to have a further discussion about potential abuse/value we can have that elsewhere.

**Pull request merged**
