### PR TITLE
release: 2.4.0

### PR DESCRIPTION
**Pull request by bastimeyer**
Let's prepare the 2.4.0 release.

- Anything missing in the changelog?
- Any mistakes in the changelog? Anything that should be worded differently?
- Anything important that should be included in 2.4.0? I don't have anything on my radar at least.

Date is set to 2021-09-07, which is in ~2 hours.

### CODE REVIEW

**Comment by bastimeyer** [comment]
https://deploy-preview-3998--streamlink.netlify.app/changelog.html#streamlink-2-4-0-2021-09-07

**Comment by gravyboat** [comment]
I don't know if 2.4.0 is sufficient for this change since we're deprecating Windows 7. Any opinions on a 3.0.0 release?

**Comment by bastimeyer** [comment]
> since we're deprecating Windows 7

We're not. This only affects the installer and thus doesn't justify a major version bump.

**Comment by gravyboat** [comment]
Fair enough. I'll merge it later tonight and cut a new release tag. Notes look good.

**Pull request merged**
