### PR TITLE
[playtv] Add support for international Play TV website

### PR DESCRIPTION
**Pull request by melmorabity**
This PR adds support for the [international version](http://play.tv/) of [Play TV](http://playtv.fr/) website.

### CODE REVIEW

**Comment by gravyboat** [comment]
@melmorabity What are the concerns here legality wise? We're trying to avoid adding more plugins that could be problematic and it seems like this site has a lot of channels from around the world and opens us up to some gray areas.

**Comment by melmorabity** [comment]
@gravyboat I understand your worries. Play TV doesn't steal anything. It's a legal and French online platform, managed by Play Media company, based in Paris. It is accredited as a TV broadcaster by the French TV & radio regulation organism. Play TV negociated with many French and international TV channels to broadcast their streams online and display their EPGs, freely or with a subscription for pay-TV channels.
Play TV is also available on Android for years: https://play.google.com/store/apps/details?id=fr.playmedia.playtv&hl=fr
play.tv is the "international" version of playtv.fr. It belongs and was registered by Play Media also.

**Comment by gravyboat** [comment]
@melmorabity Can you rebase against the updated plugin_matrix? Sorry I dropped the ball on this one.

**Comment by bastimeyer** [comment]
Please don't merge the master branch into your feature branch. You're including all of the other commits by doing that. Just rebase:
```bash
git checkout master
git pull upstream master
git checkout your-branch
git rebase --interactive master
git push --force origin your-branch
```

**Comment by melmorabity** [comment]
@bastimeyer Sorry for having screwed up my rebase... I resubmitted my PR at https://github.com/streamlink/streamlink/pull/1564

**Pull request closed without merging**
