### PR TITLE
Add a github issue template

### PR DESCRIPTION
**Pull request by bastimeyer**
I'm not sure if an issue template is really necessary here or if this specific template fits the project, but I thought that we could at least have a discussion about it.

👎
- It might be overwhelming or intimidating for casual users or bug reporters
- Not all information is always necessary

👍
- People *usually* read the template before submitting, resulting in clearer reports
- Reduces the number of duplicates
- Environment details will *most likely* be included without asking first (reduces number of responses)
- Posts are formatted correctly *most of the time*

My suggested template can ofc be changed if it's too much or if sth is missing... 😜

### CODE REVIEW

**Comment by gravyboat** [comment]
This looks good to me, fail2ban and many other projects have similar templates and it's helpful.

**Comment by beardypig** [comment]
I'm in favour of a template, for bugs I always end up asking the same questions... Which version of which OS are you using, how did you install streamlink link, have you tried the nightly, etc...

**Comment by bastimeyer** [comment]
> have you tried the nightly

Additional stuff like that could be added to the CONTRIBUTING.md file (among plugin guidelines, etc.). I think it's too much to include this in the issue template.

**Comment by gravyboat** [comment]
I'm going to merge this as is for now, we can add more to it later if we want. Thanks @bastimeyer!

**Pull request merged**
