### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
Closes #2

**Comment by gravyboat** [comment]
Good stuff, thanks!

**Comment by gravyboat** [comment]
I don't think this will work as those options are only supported by pytest, and this repo is using the standard unittest (not a huge fan myself but let's not stray into those weeds for now). I think modifying your line to be `script: coverage run --source streamlink setup.py test` should work.

**Comment by cdrage** [comment]
@gravyboat what about installing pytest? I quite like the output that pytest uses in comparison to unittest.

I've updated the PR, I'll see if this one passes this time.

**Comment by gravyboat** [comment]
I'm fine with it, haven't used pytest a ton so as long as it supports the existing unit tests (which I believe it should) then it's cool with me.

**Comment by sbstp** [comment]
The build failed, I guess you can't use sudo in there. I think you can install pip packages without sudo.

**Comment by cdrage** [comment]
argh, i forgot about that, i'll update it again. 3rd times the charm, eh?

**Comment by gravyboat** [comment]
Awesome job, thanks @cdrage!

**Pull request merged**
