### PR TITLE
plugins.youtube: rewrite and remove API calls

### LINKED ISSUE #3795: plugins.youtube.py: 404 Intermittent and Repeatable (and related, but not duplicate of 3724 of other 404 issues)
## Plugin Issue

- [X] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch. [I apologize, I'm on latest stable, but plugin hasn't been updated in 28 days and we have that installed]

### Description

There have been issues over the past couple of months with YouTube reporting 404s. It's been tricky because it's not always reproducable. We had no problems last two days, and today, half our captures have this problem.

The symptom is no different than 3724 and other previously reported items. The error is the same. Using the simplest execution.
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ streamlink https://www.youtube.com/watch?v=YertdWavZdk
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YertdWavZdk
[cli][error] Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=YertdWavZdk&html5=1&el=detailpage)
```
However, what we are seeing is similar to what we couldn't narrow down when this occurred a month ago. If you wait 3-5 minutes, or do from different machines, the same call can work, or it can report an error.

From the same machine:
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ streamlink https://www.youtube.com/watch?v=YertdWavZdk
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YertdWavZdk
[cli][error] Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=YertdWavZdk&html5=1&el=detailpage)
[Note: Paused 10 minutes manually and tried again]
ubuntu@ip-XXX-XXX-XXX-XXX:~$ streamlink https://www.youtube.com/watch?v=YertdWavZdk
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YertdWavZdk
Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p (best)
```
If you can test from machines with different IP addresses, you can run the same plain command a few times at the same time, and you'll see about half work, half return the 404.

I'm not sure if I'm missing something on the retry or other recommended fixes (e.g. cookies) but regardless of how complex or simple the query is, we see this intermittent vs. consistent behavior.

Thinking out loud / speculation: a partial rollout of something new in the youtube cluster, a potential change being tested. Just plain don't know. Clearly it's not the plug-in since it behaves some of the time on the same call, but some new behavior (or bug) on YouTube?

### Reproduction steps / Explicit stream URLs to test

1. Run this command on multiple machines (or wait a few minutes in between each call, either works: streamlink `https://www.youtube.com/watch?v=YertdWavZdk` - note you can use any youtube link that was a live stream originally, whether it's not yet live, currently live, or after the stream finishes. URL, have not tested with previously recorded only

### Log output

When the command works / doesn't 404:
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ streamlink --loglevel debug https://www.youtube.com/watch?v=YertdWavZdk
[cli][debug] OS:         Linux-5.4.0-1049-aws-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.6.5), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=YertdWavZdk
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YertdWavZdk
[plugins.youtube][debug] Video ID from URL
[plugins.youtube][debug] Using video ID: YertdWavZdk
[plugins.youtube][debug] get_video_info - 1: Found data
[plugins.youtube][debug] MuxedStream: v 135 a 251 = 480p
[plugins.youtube][debug] MuxedStream: v 133 a 251 = 240p
[plugins.youtube][debug] MuxedStream: v 160 a 251 = 144p
Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p (best)
```
When the command 404s:
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ streamlink --loglevel debug https://www.youtube.com/watch?v=YertdWavZdk
[cli][debug] OS:         Linux-5.4.0-1049-aws-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.6.5), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=YertdWavZdk
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YertdWavZdk
[plugins.youtube][debug] Video ID from URL
[plugins.youtube][debug] Using video ID: YertdWavZdk
error: Unable to open URL: https://youtube.com/get_video_info (404 Client Error: Not Found for url: https://www.youtube.com/get_video_info?video_id=YertdWavZdk&html5=1&el=detailpage)
```
Note the two calls above were run on the same machine ~3 minutes apart.

### Additional comments, etc.
I've seen and tried the other suggestions: manually adding a cookie, playing with retries. As best I can tell, this is something on YouTube's end that's now been appearing intermittently for at least 2 months and, in our daily use, has not once been affecting 100% of our calls, which are all structured identically other than the youtube link. Either everything works fine, or half the YouTube calls fail when this appears. Never 100%. In going through our internal Jira, it's always been an intermittent thing.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by bastimeyer**
Resolves #3795 

This removes the private API calls from youtube, as those are currently "a bit" wonky and return 404s more often than not.

As said, I have split up this rewrite into multiple commits for reviewing purposes (and also added a couple more changes since my last push mentioned in #3795), but the commits could also be squashed if you want to.

Changes are documented in each commit message.

----

**Invalid video**
```
$ streamlink -l debug 'https://www.youtube.com/watch?v=foooooooooo'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=foooooooooo
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][error] Could not get video info: Video nicht verfügbar
error: No playable streams found on this URL: https://www.youtube.com/watch?v=foooooooooo
```

**Scheduled live stream**
```
$ streamlink -l debug 'https://www.youtube.com/channel/UCM39V4aT21lAebPlJToSN2Q/live'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCM39V4aT21lAebPlJToSN2Q/live
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][error] Could not get video info: Diese Live-Veranstaltung beginnt in 3 Tage.
error: No playable streams found on this URL: https://www.youtube.com/channel/UCM39V4aT21lAebPlJToSN2Q/live
```

**Protected**
```
$ streamlink -l debug 'https://www.youtube.com/watch?v=UWcdeWZ_ZuM'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=UWcdeWZ_ZuM
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: UWcdeWZ_ZuM
[plugins.youtube][debug] This video may be protected.
error: This plugin does not support protected videos, try youtube-dl instead
```

**Adaptive video**
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.youtube.com/watch?v=aqz-KE-bpKQ' best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=aqz-KE-bpKQ
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: aqz-KE-bpKQ
[plugins.youtube][debug] MuxedStream: v 299 a 258 = 1080p60
[plugins.youtube][debug] MuxedStream: v 308 a 258 = 1440p60
[plugins.youtube][debug] MuxedStream: v 315 a 258 = 2160p60
[plugins.youtube][debug] MuxedStream: v 302 a 258 = 720p60
[plugins.youtube][debug] MuxedStream: v 135 a 258 = 480p
[plugins.youtube][debug] MuxedStream: v 133 a 258 = 240p
[plugins.youtube][debug] MuxedStream: v 160 a 258 = 144p
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 720p60, 1080p60, 1440p60, 2160p60 (best)
[cli][info] Opening stream: 2160p60 (muxed-stream)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Blender - Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film" -
```

**Adaptive video - embedded**
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.youtube.com/embed/aqz-KE-bpKQ' best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/aqz-KE-bpKQ
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: aqz-KE-bpKQ
[plugins.youtube][debug] MuxedStream: v 299 a 258 = 1080p60
[plugins.youtube][debug] MuxedStream: v 308 a 258 = 1440p60
[plugins.youtube][debug] MuxedStream: v 315 a 258 = 2160p60
[plugins.youtube][debug] MuxedStream: v 302 a 258 = 720p60
[plugins.youtube][debug] MuxedStream: v 135 a 258 = 480p
[plugins.youtube][debug] MuxedStream: v 133 a 258 = 240p
[plugins.youtube][debug] MuxedStream: v 160 a 258 = 144p
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 720p60, 1080p60, 1440p60, 2160p60 (best)
[cli][info] Opening stream: 2160p60 (muxed-stream)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Blender - Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film" -
```

**Adaptive video - short URL**
```
$ streamlink -l debug --title '{author} - {title}' 'https://youtu.be/aqz-KE-bpKQ' best
[cli][info] Found matching plugin youtube for URL https://youtu.be/aqz-KE-bpKQ
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: aqz-KE-bpKQ
[plugins.youtube][debug] MuxedStream: v 299 a 258 = 1080p60
[plugins.youtube][debug] MuxedStream: v 308 a 258 = 1440p60
[plugins.youtube][debug] MuxedStream: v 315 a 258 = 2160p60
[plugins.youtube][debug] MuxedStream: v 302 a 258 = 720p60
[plugins.youtube][debug] MuxedStream: v 135 a 258 = 480p
[plugins.youtube][debug] MuxedStream: v 133 a 258 = 240p
[plugins.youtube][debug] MuxedStream: v 160 a 258 = 144p
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 720p60, 1080p60, 1440p60, 2160p60 (best)
[cli][info] Opening stream: 2160p60 (muxed-stream)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Blender - Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film" -
```

**HLS Live**
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.youtube.com/watch?v=Rf4jJzziJko' best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=Rf4jJzziJko
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: Rf4jJzziJko
[plugins.youtube][debug] This video is live.
[plugins.youtube][debug] This video may be protected.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Hospital Records - Drum & Bass Non-Stop Liquid - To Relax/Chill To" -
```

**HLS Live - channel URL**
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.youtube.com/channel/UCw49uOTAJjGUdoAeUcp7tOg/live' best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCw49uOTAJjGUdoAeUcp7tOg/live
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: Rf4jJzziJko
[plugins.youtube][debug] This video is live.
[plugins.youtube][debug] This video may be protected.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Hospital Records - Drum & Bass Non-Stop Liquid - To Relax/Chill To" -
```

**HLS Live - embedded**
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.youtube.com/embed/Rf4jJzziJko' best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/Rf4jJzziJko
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: Rf4jJzziJko
[plugins.youtube][debug] This video is live.
[plugins.youtube][debug] This video may be protected.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Hospital Records - Drum & Bass Non-Stop Liquid - To Relax/Chill To" -
```

**HLS Live - embedded channel URL** (requires additional request of canonical URL)
```
$ streamlink -l debug --title '{author} - {title}' 'https://www.youtube.com/embed/live_stream?channel=UCw49uOTAJjGUdoAeUcp7tOg' best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/live_stream?channel=UCw49uOTAJjGUdoAeUcp7tOg
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: Rf4jJzziJko
[plugins.youtube][debug] This video is live.
[plugins.youtube][debug] This video may be protected.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv "--force-media-title=Hospital Records - Drum & Bass Non-Stop Liquid - To Relax/Chill To" -
```

### CODE REVIEW

**Comment by bastimeyer** [comment]
@back-to 
https://github.com/streamlink/streamlink/commit/3d2848ae5b2d9dd70fd66fd25b8523db38cf741a#r52311523

> won't work for videos with }; in the title
> https://www.youtube.com/watch?v=CqSfYBGfYEc
> `error: Unable to parse JSON: Unterminated string starting at:`

This can't be fixed entirely unless we parse the JS code and get the JSON data from the AST.

I could change the regex and extract the entire JS from the `<script>` tag and then give the regex a stronger anchor at the end, but that doesn't solve the problem entirely, as titles with `};\s*var` would also break the regex.

**Comment by bastimeyer** [comment]
@back-to 
Making the regex super strict has the potential to break the plugin as soon as YT adjusts a tiny thing
```diff
diff --git a/src/streamlink/plugins/youtube.py b/src/streamlink/plugins/youtube.py
index 3b5b2531..eaf3f26a 100644
--- a/src/streamlink/plugins/youtube.py
+++ b/src/streamlink/plugins/youtube.py
@@ -38,7 +38,13 @@ class YouTube(Plugin):
         https?://youtu\.be/(?P<video_id_short>[0-9A-z_-]{11})
     """, re.VERBOSE)
 
-    _re_ytInitialPlayerResponse = re.compile(r"""var ytInitialPlayerResponse\s*=\s*({.*?});""", re.DOTALL)
+    _re_ytInitialPlayerResponse = re.compile(r"""
+        var\s+ytInitialPlayerResponse\s*=\s*({.*?});\s*
+        var\s+meta\s*=\s*document\.createElement\('meta'\);\s*
+        meta\.name\s*=\s*'referrer';\s*
+        meta\.content\s*=\s*'origin-when-cross-origin';\s*
+        document.getElementsByTagName\('head'\)\[0]\.appendChild\(meta\);
+    """, re.VERBOSE | re.DOTALL)
     _re_mime_type = re.compile(r"""^(?P<type>\w+)/(?P<container>\w+); codecs="(?P<codecs>.+)"$""")
 
     _url_canonical = "https://www.youtube.com/watch?v={video_id}"
```

**Comment by bastimeyer** [comment]
I've added `\s*var\s+meta\s*=` to the regex, as a compromise, since it's way more unlikely that someone has set a title that matches the regex's anchor `};\s*var\s+meta\s*=` than just `};` and there's more room for YT to make changes without breaking the plugin.

Diff:
https://github.com/streamlink/streamlink/compare/cfd7329455781f92e8b45cc8e81ad810072905b4..eabf22875d72b223ccd47c08ede25c14a9a13144

I've also squashed the first two commits into one, which is better if you want to keep the individual commits when merging.

**Comment by tfdahlin** [comment]
> 
> 
> @back-to
> [3d2848a#r52311523](https://github.com/streamlink/streamlink/commit/3d2848ae5b2d9dd70fd66fd25b8523db38cf741a#r52311523)
> 
> > won't work for videos with }; in the title
> > https://www.youtube.com/watch?v=CqSfYBGfYEc
> > `error: Unable to parse JSON: Unterminated string starting at:`
> 
> This can't be fixed entirely unless we parse the JS code and get the JSON data from the AST.
> 
> I could change the regex and extract the entire JS from the `<script>` tag and then give the regex a stronger anchor at the end, but that doesn't solve the problem entirely, as titles with `};\s*var` would also break the regex.
> 
> This is the entire script tag content:
> 
> ```
> <script nonce="...">var ytInitialPlayerResponse = {};var meta = document.createElement('meta'); meta.name = 'referrer'; meta.content = 'origin-when-cross-origin'; document.getElementsByTagName('head')[0].appendChild(meta);</script>
> ```

I'm here because somebody linked to this in a pytube issue, wanted to look at your solution to the get_video_info problem. If you're interested in doing parsing like this, I actually wrote a parser that I haven't had problems with for doing exactly this over [here](https://github.com/pytube/pytube/blob/master/pytube/parser.py).

Out of curiosity, did you test your changes against age-restricted videos? That's the stumbling block that I'm running into right now using the innertube API endpoints, and I'm wondering if you happen to know if the stream data for age-restricted videos is available on the page or not

**Comment by bastimeyer** [comment]
Custom parsing solutions are always bad, same with cheap regexes like this, and the only true solution when trying to extract data from JS is using a parser which supports the latest ECMA versions and their syntaxes and then reading and traversing the generated AST. We've had these discussions several times now (eg. #2534), but the proposed python dependencies were either outdated or unmaintained and thus not ideal. I hope we can spark up a discussion again now that the youtube plugin is affected by this problem. But let's not discuss this here.

No, I have not checked all types of videos with these changes. My OP post has a list of types I've checked. YT-Authentication was not supported before and testing age-restricted videos therefore doesn't make much sense.

**Comment by tfdahlin** [comment]
I wasn't sure if your OP was extensive or not for what you had tested. Pytube doesn't support yt auth either, but by passing certain parameters to the `get_video_info` endpoint, we were able to extract stream data for age-restricted videos without auth which is why I was asking.

**Comment by back-to** [comment]
It should work with most of the videos, other small changes can be done later on.

**Comment by vstavrinov** [comment]
You make "live" suffix mandatory for "/c/" and "/user/" URLs. Is it a bug or feature?

This works:
```
mpv http://youtube.com/c/SkyNews
```
But this doesn't work:
```
streamlink http://youtube.com/c/SkyNews
```

**Comment by bastimeyer** [comment]
> You make "live" suffix mandatory for "/c/" and "/user/" URLs. Is it a bug or feature?

Intentional change, as there's no data embedded for finding the live streams.
- https://github.com/streamlink/streamlink/issues/3795#issuecomment-863083854
- https://github.com/streamlink/streamlink/pull/3797/files#diff-c4af91c02f26ae4306eb98bbce129a4a0e9420988d8f71818e2f163ceb5ecca3R33-R35

Channel URLs without `/live` suffix could be translated and `/live` appended in this case and Streamlink could then fail regularly if there's no live stream available, but I didn't think about that.

**Comment by vstavrinov** [comment]
You shouldn't append this suffix, because the cases exist where different live streams available with and without the suffix.

**Comment by bastimeyer** [comment]
> This works:
> `mpv http://youtube.com/c/SkyNews`
> cases exist where different live streams are available with and without the suffix

When a channel has multiple live streams (eg. https://youtube.com/hospitalrecords - perfect to test, as there are always two live streams online), then Youtube will redirect to the first one when accessing the channel URL with the `/live` suffix.

Implementing a URL translation in Streamlink when the `/live` suffix is missing is a tradeoff, because providing a channel URL without `/live` suffix is an invalid input URL, as it's not a canonical live stream URL.

Your mpv/yt-dl example doesn't make sense, as it'll access all channel uploads and will return a playlist of multiple videos. This logic does not apply to Streamlink.

**Comment by vstavrinov** [comment]
> When a channel has multiple live streams (eg. https://youtube.com/hospitalrecords - perfect to test, as there are always two live streams online), then Youtube will redirect to the first one when accessing the channel URL with the `/live` suffix.

Not always. In the case of SkyNews it is last, not first.

> Implementing a URL translation in Streamlink when the `/live` suffix is missing is a tradeoff, because providing a channel URL without `/live` suffix is an invalid input URL, as it's not a canonical live stream URL.

The fact is that before the last update, streamlink could play different streams with and without the suffix, so You could choose what You need. Yes, we can use video id for the exact choice, but it is not permanent and requires sometimes a playlist update.

> Your mpv/yt-dl example doesn't make sense, as it'll access all channel uploads and will return a playlist of multiple videos. This logic does not apply to Streamlink.

That is better than nothing. And this means that they can find the streams in some way. And in most cases, the first of them is a live stream.

**Comment by bastimeyer** [comment]
Streamlink can't use the old Youtube API anymore (the whole reason for this change), so what you're expecting / asking for is not possible anymore. If you don't provide a canonical livestream/video URL, and a proper URL translation is not possible like in the case of channel URLs, then Streamlink can't do anything about it. Streamlink can't output playlists or multiple videos, and whatever other tools will or can do is irrelevant.

**Comment by vstavrinov** [comment]
URL without the suffix is the main URL for tv channels where their main live stream is present. In the past, I have encountered cases where the URL with suffix leads to something different. Thus URL without the suffix is main, while the URL with the suffix is auxiliary. So if now streamlink couldn't play URL without the suffix that means that it has lost the essential feature for some ridiculous ideological reasons. Along with this feature,  You can lose a certain number of users this way, who may prefer youtube-dl in such specific cases at least. That is because the final decision is made on what URL (i.e. TV channel) You can play and not on ideological preferences.

**Pull request merged**
