### PR TITLE
plugins.twitcasting: new plugin for TwitCasting.tv

### PR DESCRIPTION
**Pull request by printempw**
Add support for https://twitcasting.tv

### CODE REVIEW

**Comment by gravyboat** [comment]
I'm hesitant to add this site because it has had almost no one streaming and very few viewers every time I've checked. There have also been a few instances where it seems people are just using the site to restream restricted content. I'll wait and see what others say.

**Comment by printempw** [comment]
It's a quite famous live streaming platform in Japan though. Wait for other opinions.

**Comment by gravyboat** [comment]
@printempw I'll try to check it out when more Japanese people are awake I guess (so far I've checked late night and early morning JPN time). For such a famous streaming platform it seems like no one is using it.

**Comment by MaserIsNotALaser** [comment]
Please add this site, its popular in Japan. (You can see much more streams if you change site language to Japanese)

**Comment by gravyboat** [comment]
Thanks for the contribution @printempw, changing the language to Japanese made actual streams with viewers show up. I didn't realize they categorized them in such an obtuse way.

**Comment by printempw** [comment]
That's nice. Thank you ;)

**Comment by i-cant-git** [comment]
Sometimes streamer has bad signal and connection is lost for few seconds, because of that streamlink closes websocket connection and you have to start streamlink again and again and again. Is it possible to add "reconnect to websocket if connection is lost" feature?

**Pull request merged**
