### PR TITLE
Add a coverage file

### PR DESCRIPTION
**Pull request by gravyboat**
This will (hopefully) work now that we aren't having a tox conflict.

### CODE REVIEW

**Comment by sbstp** [comment]
Let me know when you get the results you want, because I'm not following.

**Comment by gravyboat** [comment]
Will do, the issue is that the coverage right now is running against a bunch of stuff we don't want. I'm working on getting it to handle the actual streamlink code.

**Comment by gravyboat** [comment]
Travis appears to have failed to install pytest on the latest test, rerunning it.

**Comment by sbstp** [comment]
It looks like `pytest` isn't in the PATH. Maybe you can try `python -m pytest tests/`?

**Comment by sbstp** [comment]
Oh, we might be getting all this spam because there's like 4 VMs checking the coverage. Maybe pin it to one of them.

**Comment by gravyboat** [comment]
Okay all the tests are passing and we're swapped over to codecov. @sbstp can you please merge this (and please squash it as well)?

**Comment by sbstp** [comment]
Yeah I will, but I can't right now I'm on windows.

**Comment by gravyboat** [comment]
@sbstp You can do it directly from the github interface now, just click the dropdown arrow next to `merge pull request` and you can do a `squash and merge`. No need to do it from the command line.

**Comment by sbstp** [comment]
Neat.

**Pull request merged**
