### PR TITLE
plugins.vaughnlive: support for the HTML flv player

### LINKED ISSUE #1780: Vaughn Live returns invalid links
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [X] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://vaughnlive.tv/everything80s --stream-url --best >>my.m3u
2. streamlink https://vaughnlive.tv/franky_eyes2 --stream-url --best >>my.m3u

the above result in unplayable streams:

output from file:

rtmp://192.240.105.171:1935/live? live=1 pageUrl=https://vaughnlive.tv/everything80s playpath=live_everything80s

rtmp://192.240.105.171:1935/live? live=1 pageUrl=https://vaughnlive.tv/franky_eyes2 playpath=live_franky_eyes2

### Logs
sorry no log , and no idea where to get it.

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by beardypig**
Includes a custom `Stream` class to rejigger the stream (thanks @yoya3312)

fixes #1780

### CODE REVIEW

**Comment by fadster** [comment]
Thank you!

**Comment by Twilight0** [comment]
It appears websocket is no longer needed, perhaps it can also be removed from the dependencies.

**Comment by beardypig** [comment]
@Twilight0 it looks like we could remove it, yes.

**Comment by back-to** [comment]
removing dependencies is always nice,

but it might break some custom plugins that expects websocket from the streamlink install.

it will also make future plugins less flexible

**Comment by Twilight0** [comment]
Are you referring to unofficial plugins that are not part of streamlink?

**Comment by back-to** [comment]
@Twilight0 
that's not the important part,
but **new plugin** can't use it and **old plugins** that might need it won't work.

if it's get removed it must be noted in the changelog

**Comment by beardypig** [comment]
I think I will use the websockets client to upgrade the UStream plugin...

**Comment by Twilight0** [comment]
@back-to : No other plugin used it except vaughnlive, hense why I asked if we can get rid of websocket, but @beardypig says he can utilize on Ustream so I am all for it... ustream has definitely become a beast a year or so ago with their API changes.

**Pull request merged**
