### PR TITLE
plugins.tiktok: fix room ID schema

### LINKED ISSUE #6105: plugins.tiktok: No playable streams found on this URL
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 6.8.3

### Description

I can't get any streams and it just shows "No playable streams found on this URL" error though the stream is on air, and it is same when given any other URL live.

### Debug log

```text
PS C:\Users\WDAGUtilityAccount\Desktop> streamlink "https://www.tiktok.com/@ktkt7621v6a/live" best --loglevel=debug
[session][debug] Loading plugin: tiktok
[cli][debug] OS:         Windows 11
[cli][debug] Python:     3.12.4
[cli][debug] OpenSSL:    OpenSSL 3.0.13 30 Jan 2024
[cli][debug] Streamlink: 6.8.3
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.7.4
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.2.2
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.26.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.2
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.tiktok.com/@ktkt7621v6a/live
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin tiktok for URL https://www.tiktok.com/@ktkt7621v6a/live
error: No playable streams found on this URL: https://www.tiktok.com/@ktkt7621v6a/live
PS C:\Users\WDAGUtilityAccount\Desktop>
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Resolves #6105 

```
$ ./script/test-plugin-urls.py tiktok -r CHANNEL ktkt7621v6a -m
:: https://www.tiktok.com/@ktkt7621v6a
::  ao, ld, origin, sd, hd, worst, best
::   {'id': '7398851432071645960', 'author': '브롤 멜로디 잘하는사람', 'category': None, 'title': '제발 도와주세요 미코 30랭크 까지만 ㅜㅜㅜ'}
:: https://www.tiktok.com/@ktkt7621v6a/live
::  ao, ld, origin, sd, hd, worst, best
::   {'id': '7398851432071645960', 'author': '브롤 멜로디 잘하는사람', 'category': None, 'title': '제발 도와주세요 미코 30랭크 까지만 ㅜㅜㅜ'}
```

### CODE REVIEW

**Comment by pikamonvvs** [comment]
Dear @bastimeyer ,
I have checked that the problem was solved with your commit.

```
[cli][info] Found matching plugin tiktok for URL https://www.tiktok.com/@ktkt7621v6a/live
[cli][info] Available streams: ao, ld (worst), origin, sd, hd (best)
[cli][info] Opening stream: hd (http)
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player, a file path to save the stream with --output, or pipe the stream to another program with --stdout.
```

I was surprised at your quick fix. :D
Thanks a lot!

**Comment by birdmonter** [comment]
> ```
> $ streamlink --json 'www.tiktok.com/@honekrasae_official/live' | jq .metadata 
> ::  { 
> "id": "7408428720647949072",        
> "author": "โหนกระแส (HoneKrasae_Official)", 
> "category": null,     
> "title": "LIVE โหนกระแส 29/08/67"
> }
> ```

**Comment by birdmonter** [comment]
add Cookie 
> ```
> $ streamlink --http-cookie sessionid_ss=xxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxx --http-cookie store-idc=xxxxx tiktok.com/@honekrasae_official best -o output.mp4
```

**Comment by bastimeyer** [comment]
Please don't comment on merged pull requests, especially if the merged code is already part of a new stable release. If there's a plugin issue, then open a new plugin issue thread on the issue tracker.

Locking...

**Pull request merged**
