### PR TITLE
0.1.0 Release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
Closes https://github.com/streamlink/streamlink/issues/116

**Comment by cdrage** [comment]
@beardypig @gravyboat 

Bumping release to 0.1.0 since it's quite major (Windows binary + lot's of pickup in development last couple of months).

If you disagree let me know! Otherwise, once this is merged I'll push to Pypi + do a GitHub release.

**Comment by beardypig** [comment]
I'm fine with `0.1.0` :-)

**Comment by gravyboat** [comment]
I'm fine with it, let's do this thing!

**Comment by beardypig** [comment]
Congrats! Awesome work from everyone involved getting this out :-)

**Comment by cdrage** [comment]
@beardypig @gravyboat done! should see it under pypi and the github release now :)

**Comment by Brainzyy** [comment]
Thanks for all the great work guys, currently learning some more Python to maybe help out some more :p

**Comment by gravyboat** [comment]
Just installed the latest release via pip on Ubuntu 16.04 and things look good. :+1:

**Comment by gravyboat** [comment]
We should get @RosadinTV's portable build added to the release page. We discussed this a while back but do we want to make a repo where that code can live so it's publicly available/maintained?

**Comment by stevek123** [comment]
How can I update streamlink if it was installed via "pip install streamlink"?

**Comment by mmetak** [comment]
Updated in AUR. :)

**Comment by gravyboat** [comment]
@stevek123 `pip install --upgrade streamlink`

**Comment by gravyboat** [comment]
@mmetak Are the instructions still accurate on the docs page regarding installation via `pacman -S streamlink`?

**Comment by mmetak** [comment]
@gravyboat No since streamlink is not yet in official arch repos. It's in the AUR so you would have to install it with aur helper like pacaur or yaourt...
`pacaur -S streamlink`  for stable version
'pacaur -S streamlink-git`  for latest git

**Comment by gravyboat** [comment]
@mmetak Makes sense, we should probably update the docs at some point.

**Comment by mmetak** [comment]
@gravyboat I'll ask Felix Yan (arch TU & livestreamer maintainer) if he's willing to import streamlink to community repo.

**Pull request merged**
