### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by cdrage**
Updates the changelog for 0.13.0

### CODE REVIEW

**Comment by beardypig** [comment]
Did you use the release script to generate this? Seems to be missing the git shortlog.

**Comment by cdrage** [comment]
@beardypig No I did not, is there any scripts? I didn't see any within `scripts`

**Comment by beardypig** [comment]
Yeah, should be... #1711

```sh
$ /script/release.sh -h
usage: release.sh [OPTIONS]

Helper script for performing a release of Streamlink.
Options can be specified on the command line, or the user will
be prompted to enter the required options.

General options:
  -h, --help
    Show this help message and exit.

  -u, --upstream REPO
    Set the upstream repo (streamlink/streamlink)

  -o, --origin REPO
    Set the users fork of the upstream repo (gituser/streamlink)

  -v, --version VERSION
    Set the new version number.
```

**Comment by cdrage** [comment]
@beardypig Isn't that script only being used in Travis CI / you shouldn't be running it manually?

I tried it locally anyways:

``sh
▶ python script/github_releases.py --tag 0.13.0 --repo https://github.com/streamlink/streamlink --dry-run --api-key $GITHUB_TOKEN --debug
DEBUG:__main__:Opening changelog file: /home/wikus/seafile/files/dev/python/streamlink/CHANGELOG.md
DEBUG:__main__:Parsing change log file
DEBUG:__main__:Found 18 change logs
DEBUG:__main__:Getting the current release ID for https://github.com/streamlink/streamlink#0.13.0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/https://github.com/streamlink/streamlink/releases/tags/0.13.0 HTTP/1.1" 404 None
DEBUG:__main__:Release ID fetch failed:
DEBUG:__main__:{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
ERROR:__main__:Failed to update release info.
Traceback (most recent call last):
  File "script/github_releases.py", line 78, in main
    raise ValueError("Unable to get release ID, check API KEY")
ValueError: Unable to get release ID, check API KEY
```

**Comment by beardypig** [comment]
That's a different one, the `github_releases.py` updates the release in GitHub based on the CHANGELOG.md file. A the `release.sh` script is a helper to update the CHANGELOG.md and create a release-xx branch for you :)

**Comment by cdrage** [comment]
@beardypig Crap. I completely missed that (wasn't actually +x'd)

**Comment by beardypig** [comment]
Ah, that's weird, should be +x in git...

**Comment by gravyboat** [comment]
@beardypig On that note we should probably document what the full release process looks like now just so it's written down and concise.

**Comment by beardypig** [comment]
Yeah, I should have done it before :)

There still seems to be a problem with the release process - the wheel and tar were not added to the GitHub release. I’ll fix that today, I think it’s the ordering ...

**Pull request closed without merging**
