### PR TITLE
Add capability of extracting current sport.francetv stream

### PR DESCRIPTION
**Pull request by yhel**
Hello,

As the French Open (Roland Garros) is currently airing, Pluzz plugin dont work on the network sport dedicated website "sport.francetvinfo.fr".

This commit just adds the ability to retrieve the stream from this website.

Best regards.

### CODE REVIEW

**Comment by bastimeyer** [comment]
Unrelated to the changes of this PR, the commit seems to have author metadata that is not linked to your github account. I don't know if this is intentional or not and if you don't want to get linked and credited for your changes, but if you do, see [here](https://help.github.com/articles/setting-your-email-in-git/) on how to set up your git config properly.

**Comment by yhel** [comment]
It was not really intentional. Thanks for the link I will be careful next time.
Regarding the code coverage report, I guess it's based on assertions from the test file, I understand why the third assert failed (the url was just for the current game and so temporary) but not why a second one failed.

**Comment by beardypig** [comment]
All of the tests pass, the coverage reports that you added 3 lines but only 1 of the lines was covered by the new test.

Code looks good, I'm not able to test it though. @melmorabity is probably the best person to review this, if possible :)

**Comment by melmorabity** [comment]
@yhel thanks for your contribution
@beardypig sure, I will have a look :)

**Comment by melmorabity** [comment]
@yhel: VOD is OK :).
When the Roland Garros stream is offline on http://sport.francetvinfo.fr/roland-garros/direct, I get this error:
```
$ streamlink http://sport.francetvinfo.fr/roland-garros/direct[cli][info] Found matching plugin pluzz for URL http://sport.francetvinfo.fr/roland-garros/direct
error: Unable to validate JSON: Unable to validate key 'videos': Unable to validate key 'format': Type of None should be 'str' but is 'NoneType'
```
Coulld you modify the _api_schema variable so that empty 'format' values are allowed?
```
                'format': validate.any(
                    None,
                    validate.text
                ),
```

**Comment by melmorabity** [comment]
OK for me :)

**Comment by gravyboat** [comment]
Thanks for the contribution @yhel! Also thanks for reviewing this one @bastimeyer, @beardypig, and @melmorabity.

**Pull request merged**
