### PR TITLE
Create install script for pynsist

### PR DESCRIPTION
**Pull request by sbstp**
Taking a shot at #25. This creates an installer package using NSIS, it includes a full copy of Python and streamlink. It also modifies the PATH variable for easy access from cmd.exe.

### CODE REVIEW

**Comment by sbstp** [comment]
According to [pynsist's FAQ](http://pynsist.readthedocs.io/en/latest/faq.html#building-on-other-platforms), it can even create the installer package from linux.

**Comment by cdrage** [comment]
@sbstp should we add a WIP label for this?

I don't have much time this week in regards to windows debugging, but I can try to find some time once my machine is up and running to test this ^^

**Comment by sbstp** [comment]
Yeah, we'll need people to test it.

**Comment by Brainzyy** [comment]
If someone gives me some basic instructions on how to test this, I'm up for it.

**Comment by sbstp** [comment]
1. Checkout the `installer` branch of this repo. (I pushed here instead of in my fork by mistake)
2. Install [NSIS](http://nsis.sourceforge.net/Download).
3. Install pynsist with pip `pip install pynsist`.
4. Run pynsist on the config file `pynsist streamlink.cfg`.
5. Once the command is finished check the `build/nsis` directory for a file named `Streamlink-1.0.exe` This is the installer.

**Comment by Brainzyy** [comment]
@sbstp Thanks for the tut, I'll check it out now.

**Comment by Brainzyy** [comment]
Installer builds fine, installs fine, but when trying to run I get this error: [http://imgur.com/a/mbeWU](url)

**Comment by gravyboat** [comment]
@Brainzyy Are you using 2.7? I don't think futures is included by default. Try `pip install futures` then run it again.

**Comment by sbstp** [comment]
The packages field of the config file should have the futures package listed there.

**Comment by Brainzyy** [comment]
@gravyboat Python 2.7 was installed by the installer, but it didn't work. Installing futures didn't help either, I think my Python 3 installation might be causing all this.

**Comment by sbstp** [comment]
I think the issue is that I didn't add futures packages to the list of packages to bundle. I'm going to test it in a couple of minutes.

**Comment by sbstp** [comment]
My last commit contains a fix for the issue. @Brainzyy can you test it? This issue was only caused because I told `pynsist` to bundle Python 2.7.12, where the `concurrent.futures` module does not exist.

I thought using Python 2 was safer in terms of compatibility. Looking back at livestreamer's README, it clearly states that plugins should be compatible with both Python 2 and 3. Debian has a [package](https://packages.debian.org/jessie/python3-livestreamer) in jessie for livestreamer & Python 3. I can only assume that it was pretty stable if it made it into jessie. Maybe we should bundle Python 3.5. We get a much smaller installer, it doesn't mess with current installations. Thoughts?

**Comment by Brainzyy** [comment]
@sbstp I get a different error now: http://imgur.com/a/5p8ZO

**Comment by sbstp** [comment]
Did you produce the installer using Python 3? I think that it took the `concurrent` module from Python 3, and not the one from the `futures` packages.

**Comment by Brainzyy** [comment]
@sbstp I'm sorry for my stupidity. After installing the Python 2 versions of everything, it worked perfectly! Thanks for your patience.

**Comment by sbstp** [comment]
No worries, that's not your fault at all. I expected it to work on python 3, I didn't think it would copy a builtin module.

**Comment by gravyboat** [comment]
The error on python 3.5 is pretty minimal, I'm fine with merging this if others are.

**Comment by sbstp** [comment]
@gravyboat I'd like to do more testing of the installer before it's merged. We should also discuss the use of the embedded Python 3.5, instead of 2.7.12. It's a lot smaller and it's isolated from other Python installations. Also, it won't cause issues when building it Python 2 or 3. The real question is: do we think the code is sufficiently compatible with Python 3?

**Comment by cdrage** [comment]
Yeah, please no merge until it's 100% working!

Don't want to ship anything half-broken.

**Comment by gravyboat** [comment]
@sbstp I honestly don't know if it is, and right now the tests aren't comprehensive enough to confirm that.

**Comment by sbstp** [comment]
Is there a tool that we can run on the plugins to check for compatibility? I've heard of the `2to3` tool, but not sure if it does linting.

**Comment by SpootDev** [comment]
There are a handful of spots in the code using the dreaded b.

I use "from __future__ import absolute_import, division, print_function, unicode_literals" on all my source code files to help migrate to py3.  Not sure if this is the best way but it certainly helped bring alot of my code up to py3.

**Comment by sbstp** [comment]
I tried running the `2to3` tool in diff mode on the plugins. Almost 95% of the changes are caused by calls to `items()` on a dictionnary. The tool changes it to `list(x.items())` because `items()` is lazy in Python 3, it replicates the behavior of Python 2. But I think that in most cases, it doesn't matter if it's a generator or a list. Other than that, the plugins look like they're compatible.

**Comment by sbstp** [comment]
@cdrage @gravyboat I could produce an installer for `0.0.1` using this. It could a 'beta' level installer, we could get feedback on how well it works.

**Comment by gravyboat** [comment]
@sbstp I think it's definitely worth giving a shot at least for our Windows user base.

**Comment by martinth** [comment]
Some feedback: I could built a Installer on my Macbook (using Python 2.7) which I then copied to my Windows 10 machine. The installer worked but when launching `streamlink` I get the following error:

```
PS C:\Users\Martin> streamlink
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 11, in <module>
    from streamlink_cli.main import main
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 18, in <module>
    from streamlink.plugins.twitch import TWITCH_CLIENT_ID
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", line 10, in <module>
    from streamlink.plugin.api import http, validate
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\validate.py", line 25, in <module>
    from singledispatch import singledispatch
ImportError: No module named singledispatch
PS C:\Users\Martin>
```

Note I already hade Python 2.7 installed beforehand but I don't think that should cause this. I also found that the installer could probably a bit confusing to non-developers since I asks you this question:


Some users will most certainly not install Python 2.7 (since it looks like something optional) which will then anger them. Doesn someone know if you scan hide this selection?

**Comment by martinth** [comment]
Okay, figured it out. The installer installed the Python into `C:\Program Files (x86)\Common Files\Python\2.7` while not touching my installation in `C:\Python27` it also didn't add the new Python to my `PATH` which meant that my inital try of `pip install singledispatch` didn't change anything. 

After finding the used Python intallation (easy enough, it was references in the wrapper script that `pynsist` created) and running `"C:\Program Files (x86)\Common Files\Python\2.7\Scripts\pip.exe" install singledispatch` (in an administrative prompt) `streamlink` appears to work:

```
PS C:\Users\Martin> streamlink https://www.twitch.tv/sing_sing best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/sing_sing
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[cli][info] Player closed
[cli][info] Stream ended
PS C:\Users\Martin>
```

So it should be as easy as adding `singledispatch` to the Config file for `pynsist`.

**Comment by martinth** [comment]
Oh, btw: This also means that we could ship a Python 2.7 based installer as short-term solution to get an installer out while figuring out the way to the Python 3.5 embedded version. The chances that this installer breaks anything on the user side are pretty low since it isolates itself from any already installed Python versions.

**Comment by sbstp** [comment]
@martinth thanks for testing this. I added the `singledispatch` package, so it should run properly now.

**Comment by sbstp** [comment]
Oh also, the embedded version works. I'm using it on my Windows partition and I haven't had any issues so far. I obviously haven't used all the plugins, but the core seems to be stable on Python 3, which is how it should be given that the old README claimed Python 3 compatibility.

**Comment by martinth** [comment]
@sbstp re-tested with your changes. Now it works flawlessly. Built it on Windows 10 with Python 2.7 this time and that also worked.

The version in `streamlink.cfg` should probably be adjusted. The only remaining thins would be the "Select components to install" dialog. Maybe this could be avoided by customizing the NSIS script? I saw that pynsist has an option to use a custom one.

**Comment by sbstp** [comment]
I'd rather not get into customizing the NSIS script. The "Select components to install" dialog, while unintuitive, is something I can live with. Perhaps we could open an issue on the `pynsist` repo to see if there's a way of getting rid of it.

**Comment by thinkpad4** [comment]
Being built on Win10 means it will work on Win7, right? Cause that is what I use

**Comment by sbstp** [comment]
The installer can be built on any platform. The fact that it runs on Windows 10 does not guarantee it will work with Windows 7, but Windows 7 is definitely a platform we want to run on. It still is the most popular version of Windows.

**Comment by sbstp** [comment]
I'd like to package a beta version of this installer in the next release, is anything blocking it? AFAIK most issues have been resolved.

**Comment by sbstp** [comment]
Created an installer for Python 2 & 3. The config file is now generated by a bash script, allows us to insert dynamic information such as streamlink's version.

**Comment by gravyboat** [comment]
@sbstp What else needs to be done to get this into master?

**Comment by sbstp** [comment]
I think it's pretty much ready. We should release 0.2 with the installers and collect feedback from people using them. Might be appropriate to updates docs/readme to explain how to use the installers (py2/py3).

**Comment by gravyboat** [comment]
Cool, can you rebase to fix the conflicts and then I'll merge it?

**Comment by cdrage** [comment]
@sbstp @gravyboat I agree with you both. Let's get this rebased and merged, then I'll do a release (either later today) or tomorrow to pip so people can test and such.

**Comment by gravyboat** [comment]
Good stuff @sbstp, thanks for fixing that up, do you mind if I squash the merge? If so let me know and I'll retain them.

**Comment by gravyboat** [comment]
@sbstp @cdrage I'm going to squash and merge this, I really want to try out the Windows installer on my Windows partition, then I can update my powershell command line script for it.

**Pull request merged**
