### PR TITLE
[TF1] Fix plugin

### PR DESCRIPTION
**Pull request by BZHDeveloper**
TF1 group renamed some of her channels, NT1 & HD1, as "TFX" & "TF1 Séries Films". So I've updated plugin according to last TF1 changes.

### CODE REVIEW

**Comment by gravyboat** [comment]
What do you think about adding some tests to https://github.com/streamlink/streamlink/blob/master/tests/test_plugin_tf1.py to cover the new domains?

**Comment by BZHDeveloper** [comment]
NOTE : TF1 redirect old channel names to new ones (for now).
so I added tests only for TF1 & TMC (NT1 & HD1 failure tests are commented and disabled)

**Comment by melmorabity** [comment]
Works fine :)

**Comment by gravyboat** [comment]
Good stuff thanks @BZHDeveloper, sorry for the slow response. Thanks for the review @melmorabity.

**Pull request merged**
