### PR TITLE
plugins.huomao: Adding plugin for Huomao

### PR DESCRIPTION
**Pull request by svenanderzen**
**Adding plugin to play video sources from huomao.tv / huomao.com.**

I could not find any documentation for developing plugins for Streamlink so winged it a bit (a lot) and used some of the other plugins as inspiration. Let me know if something needs to be changed. Also; Python isn't my strongest side, so let me know if something seems completely bananas.

### CODE REVIEW

**Comment by gravyboat** [comment]
Very hacky but I'm okay with it if this is the only way to do things. Would it be possible to get some test coverage?

**Comment by svenanderzen** [comment]
Hehe, yeah I know! But since they don't provide an API and my chinese is non-existent I had a hard time finding any alternative... :/

I'll fix some tests as soon as time allows and update the PR. 👍 

On a side note: do you guys have any plans of setting up an Gitter or Slack channel for project communications? :)

**Comment by gravyboat** [comment]
@svenanderzen Thanks! We actually have gitter already set up: https://gitter.im/streamlink/streamlink it's not super busy since we're a pretty small team so time is limited in terms of what we spend our time on.

**Comment by beardypig** [comment]
Looks good to merge to me :) Thanks @svenanderzen. Tests would be nice but ...

**Comment by gravyboat** [comment]
Let's merge for now since this has been open for a bit.

**Pull request merged**
