### PR TITLE
docs: tweak CLI argument help texts

### PR DESCRIPTION
**Pull request by pzhlkj6612**
Hi! This PR contains the re-implement of 1e12d02ba922e936d342d86848b34de5623b95c1 in #4618 . The comparison are as follows.

## 1. plugins.nicolive: docs: apply bold style to "--timeshift-offset"

Commit: cfe5b418c4add84e38f466167ddea27d8cc1f96c

Original:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-niconico-timeshift-offset">
> <span class="sig-name descname"><span class="pre">--niconico-timeshift-offset</span></span><span class="sig-prename descclassname"> <span class="pre">[HH:]MM:SS</span></span><a class="headerlink" href="#cmdoption-niconico-timeshift-offset" title="Permalink to this definition">#</a></dt>
> <dd><p>Amount of time to skip from the beginning of a stream. Default is 00:00:00.</p>
> </dd></dl>

New:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-niconico-timeshift-offset">
> <span class="sig-name descname"><span class="pre">--niconico-timeshift-offset</span></span><span class="sig-prename descclassname"> <span class="pre">[HH:]MM:SS</span></span><a class="headerlink" href="#cmdoption-niconico-timeshift-offset" title="Permalink to this definition">#</a></dt>
> <dd><p>Amount of time to skip from the beginning of a stream.</p>
> <p>Default is: <strong>00:00:00</strong>.</p>
> </dd></dl>

## 2. docs: use valid or full-length options to create links

Commit: b1c7ac765658004bb19e9538d0475a134e0ae7ee

Original:

```console
$ streamlink --help | grep --before-context=1 -e 'IPv4 only'
  -4, --ipv4
    Resolve address names to IPv4 only. This option overrides :option:`-6`.

```

New:

```console
$ streamlink --help | grep --before-context=1 -e 'IPv4 only'
  -4, --ipv4
    Resolve address names to IPv4 only. This option overrides --ipv6.

```

## 3. docs: use bulleted list to organize content

Commit: 0ae409eecccfd4411325e2ab6187d412ad064cbb

Original:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-hls-playlist-reload-time">
> <span class="sig-name descname"><span class="pre">--hls-playlist-reload-time</span></span><span class="sig-prename descclassname"> <span class="pre">TIME</span></span><a class="headerlink" href="#cmdoption-hls-playlist-reload-time" title="Permalink to this definition">#</a></dt>
> <dd><p>Set a custom HLS playlist reload time value, either in seconds
> or by using one of the following keywords:</p>
> <div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">segment</span><span class="p">:</span> <span class="n">The</span> <span class="n">duration</span> <span class="n">of</span> <span class="n">the</span> <span class="n">last</span> <span class="n">segment</span> <span class="ow">in</span> <span class="n">the</span> <span class="n">current</span> <span class="n">playlist</span>
> <span class="n">live</span><span class="o">-</span><span class="n">edge</span><span class="p">:</span> <span class="n">The</span> <span class="nb">sum</span> <span class="n">of</span> <span class="n">segment</span> <span class="n">durations</span> <span class="n">of</span> <span class="n">the</span> <span class="n">live</span> <span class="n">edge</span> <span class="n">value</span> <span class="n">minus</span> <span class="n">one</span>
> <span class="n">default</span><span class="p">:</span> <span class="n">The</span> <span class="n">playlist</span><span class="s1">'s target duration metadata</span>
> </pre></div>
> </div>
> </dd></dl>

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-fs-safe-rules">
> <span class="sig-name descname"><span class="pre">--fs-safe-rules</span></span><span class="sig-prename descclassname"></span><a class="headerlink" href="#cmdoption-fs-safe-rules" title="Permalink to this definition">#</a></dt>
> <dd><p>These characters are replaced with an underscore for the rules in use:</p>
> <div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">POSIX</span>  <span class="p">:</span> \<span class="n">x00</span><span class="o">-</span>\<span class="n">x1F</span> <span class="o">/</span>
> <span class="n">Windows</span><span class="p">:</span> \<span class="n">x00</span><span class="o">-</span>\<span class="n">x1F</span> \<span class="n">x7F</span> <span class="s2">" * / : &lt; &gt; ? \ |</span>
> </pre></div>
> </div>
> </dd></dl>

New:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-hls-playlist-reload-time">
> <span class="sig-name descname"><span class="pre">--hls-playlist-reload-time</span></span><span class="sig-prename descclassname"> <span class="pre">TIME</span></span><a class="headerlink" href="#cmdoption-hls-playlist-reload-time" title="Permalink to this definition">#</a></dt>
> <dd><p>Set a custom HLS playlist reload time value, either in seconds
> or by using one of the following keywords:</p>
> <ul class="simple">
> <li><p>segment: The duration of the last segment in the current playlist</p></li>
> <li><p>live-edge: The sum of segment durations of the live edge value minus one</p></li>
> <li><p>default: The playlist's target duration metadata</p></li>
> </ul>
> </dd></dl>

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-fs-safe-rules">
> <span class="sig-name descname"><span class="pre">--fs-safe-rules</span></span><span class="sig-prename descclassname"></span><a class="headerlink" href="#cmdoption-fs-safe-rules" title="Permalink to this definition">#</a></dt>
> <dd><p>These characters are replaced with an underscore for the rules in use:</p>
> <ul class="simple">
> <li><p>POSIX: x00-x1F /</p></li>
> <li><p>Windows: x00-x1F x7F " * / : &lt; &gt; ? |</p></li>
> </ul>
> </dd></dl>

## 4. docs: include the option itself in its example

Commit: 9d7e3e37fe5fd6803437d22f92dc360887b4cc8e

Original:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-stream-sorting-excludes">
> <span class="sig-name descname"><span class="pre">--stream-sorting-excludes</span></span><span class="sig-prename descclassname"> <span class="pre">STREAMS</span></span><a class="headerlink" href="#cmdoption-stream-sorting-excludes" title="Permalink to this definition">#</a></dt>
> <dd><p>For example this will exclude streams from two quality types:</p>
> <div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="s2">"&gt;480p,&gt;medium"</span>
> </pre></div>
> </div>
> </dd></dl>

New:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-stream-sorting-excludes">
> <span class="sig-name descname"><span class="pre">--stream-sorting-excludes</span></span><span class="sig-prename descclassname"> <span class="pre">STREAMS</span></span><a class="headerlink" href="#cmdoption-stream-sorting-excludes" title="Permalink to this definition">#</a></dt>
> <dd><p>For example this will exclude streams from two quality types:</p>
> <div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="o">--</span><span class="n">stream</span><span class="o">-</span><span class="n">sorting</span><span class="o">-</span><span class="n">excludes</span> <span class="s2">"&gt;480p,&gt;medium"</span>
> </pre></div>
> </div>
> </dd></dl>

## 5. docs: apply option links in indented lines

Commit: 8a0c23f9f2927e94fde1925bbc1ffd4d58725b91

Original:

> <dl>
> <dt>VLC specific information:</dt><dd><p>These variables are accessible in the --title option by adding a backslash
> in front of the dollar sign which VLC uses as its formatting character.</p>
> <p>For example, to put the current date in your VLC window title,
> the string "\$A" could be inserted inside the --title string.</p>
> </dd>
> </dl>

New:

> <dl>
> <dt>VLC specific information:</dt><dd><p>These variables are accessible in the <a class="reference internal" href="#cmdoption-title"><code class="xref std std-option docutils literal notranslate"><span class="pre">--title</span></code></a> option by adding a backslash
> in front of the dollar sign which VLC uses as its formatting character.</p>
> <p>For example, to put the current date in your VLC window title,
> the string "\$A" could be inserted inside the <a class="reference internal" href="#cmdoption-title"><code class="xref std std-option docutils literal notranslate"><span class="pre">--title</span></code></a> string.</p>
> </dd>
> </dl>

## 6. docs: add names for special characters

Commit: 1e6217a54c10e5744bce676bbd80694dc493e76a

Original:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-stream-types">
> <span class="sig-name descname"><span class="pre">--stream-types</span></span><span class="sig-prename descclassname"> <span class="pre">TYPES</span></span><a class="headerlink" href="#cmdoption-stream-types" title="Permalink to this definition">#</a></dt>
> <dt class="sig sig-object std" id="cmdoption-stream-priority">
> <span class="sig-name descname"><span class="pre">--stream-priority</span></span><span class="sig-prename descclassname"> <span class="pre">TYPES</span></span><a class="headerlink" href="#cmdoption-stream-priority" title="Permalink to this definition">#</a></dt>
> <dd><p>A <code class="docutils literal notranslate"><span class="pre">*</span></code> can
> be used as a wildcard to match any other type of stream, eg. muxed-stream.</p>
> </dd></dl>

New:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-stream-types">
> <span class="sig-name descname"><span class="pre">--stream-types</span></span><span class="sig-prename descclassname"> <span class="pre">TYPES</span></span><a class="headerlink" href="#cmdoption-stream-types" title="Permalink to this definition">#</a></dt>
> <dt class="sig sig-object std" id="cmdoption-stream-priority">
> <span class="sig-name descname"><span class="pre">--stream-priority</span></span><span class="sig-prename descclassname"> <span class="pre">TYPES</span></span><a class="headerlink" href="#cmdoption-stream-priority" title="Permalink to this definition">#</a></dt>
> <dd><p>An <code class="docutils literal notranslate"><span class="pre">*</span></code> (asterisk) can
> be used as a wildcard to match any other type of stream, eg. muxed-stream.</p>
> </dd></dl>

## 7. ~~docs: adjust string type to avoid doubling symbols~~

Commit: 72c32f141a8b230700eb597813203bdd41c0edd3 (dropped)

No difference between rendered content.

## 8. docs: use single-backtick inline code block

Commit: 8eda37d4afa3067c0041759b4866a9178f51b7c0 (was 0ac38c860b87c8885ef8c02d260e123399b76298) (was d02c81e8a3c9e4bfaf25dd4304ee8e04b35f831b)

### Group 1: webpage

Original:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-fs-safe-rules">
> <span class="sig-name descname"><span class="pre">--fs-safe-rules</span></span><span class="sig-prename descclassname"></span><a class="headerlink" href="#cmdoption-fs-safe-rules" title="Permalink to this definition">#</a></dt>
> <dd><p>These characters are replaced with an underscore for the rules in use:</p>
> <ul class="simple">
> <li><p>POSIX: x00-x1F /</p></li>
> <li><p>Windows: x00-x1F x7F " * / : &lt; &gt; ? |</p></li>
> </ul>
> </dd></dl>

New:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-fs-safe-rules">
> <span class="sig-name descname"><span class="pre">--fs-safe-rules</span></span><span class="sig-prename descclassname"></span><a class="headerlink" href="#cmdoption-fs-safe-rules" title="Permalink to this definition">#</a></dt>
> <dd><p>These characters are replaced with an underscore for the rules in use:</p>
> <ul class="simple">
> <li><p>POSIX: <code class="code docutils literal notranslate"><span class="pre">\x00-\x1F</span> <span class="pre">/</span></code></p></li>
> <li><p>Windows: <code class="code docutils literal notranslate"><span class="pre">\x00-\x1F</span> <span class="pre">\x7F</span> <span class="pre">"</span> <span class="pre">*</span> <span class="pre">/</span> <span class="pre">:</span> <span class="pre">&lt;</span> <span class="pre">&gt;</span> <span class="pre">?</span> <span class="pre">\</span> <span class="pre">|</span></code></p></li>
> </ul>
> </dd></dl>

### Group 2: man page

Original:

> --locale LOCALE
> 
>   The preferred locale setting, for selecting the preferred subtitle and audio language.
> 
>   The locale is formatted as [language_code]_[country_code], eg. en_US or es_ES.

New:

> --locale LOCALE
> 
>   The preferred locale setting, for selecting the preferred subtitle and audio language.
> 
>   The locale is formatted as **[language_code]_[country_code]**, eg. **en_US** or **es_ES**.

### Group 3: help content

Original:

```console
$ streamlink --help | grep --before-context=4 --after-context=1 -e 'Valid operators are'
    Uses a filter expression in the format:
    
      [operator]<value>
    
    Valid operators are ``>``, ``>=``, ``<`` and ``<=``. If no operator is specified then
    equality is tested.

```

New:

```console
$ streamlink --help | grep --before-context=4 --after-context=1 -e 'Valid operators are'
    Uses a filter expression in the format:
    
      [operator]<value>
    
    Valid operators are `>`, `>=`, `<` and `<=`. If no operator is specified then
    equality is tested.

```

## 9. docs: put inline code to code blocks in examples

Commit: 4ce3cbce79f1fa6dfa3bda429ccd5d6698f06c57 (was 00a9c12c22f08c4ad1172ff9620065f90b963b3e) (was b70aaf1b80d8a6bac26ee0628aa5c58c886bdd98)

Original:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-hls-segment-ignore-names">
> <span class="sig-name descname"><span class="pre">--hls-segment-ignore-names</span></span><span class="sig-prename descclassname"> <span class="pre">NAMES</span></span><a class="headerlink" href="#cmdoption-hls-segment-ignore-names" title="Permalink to this definition">#</a></dt>
> <dd><p>A comma-delimited list of segment names that will get filtered out.</p>
> <p>Example: --hls-segment-ignore-names 000,001,002</p>
> <p>This will ignore every segment that ends with 000.ts, 001.ts and 002.ts</p>
> </dd></dl>

New:

> <dl class="std option">
> <dt class="sig sig-object std" id="cmdoption-hls-segment-ignore-names">
> <span class="sig-name descname"><span class="pre">--hls-segment-ignore-names</span></span><span class="sig-prename descclassname"> <span class="pre">NAMES</span></span><a class="headerlink" href="#cmdoption-hls-segment-ignore-names" title="Permalink to this definition">#</a></dt>
> <dd><p>A comma-delimited list of segment names that will get filtered out.</p>
> <p>Example: <code class="code docutils literal notranslate"><span class="pre">--hls-segment-ignore-names</span> <span class="pre">000,001,002</span></code></p>
> <p>This will ignore every segment that ends with 000.ts, 001.ts and 002.ts</p>
> </dd></dl>

### CODE REVIEW

**Comment by bastimeyer** [comment]
Thanks for the PR. I'll take a closer look at the changes later. Most of it looks fine, but there's at least one change which I don't agree with.

**Comment by pzhlkj6612** [comment]
Hi @bastimeyer , thanks for your reply.

> Most of it looks fine, but there's at least one change which I don't agree with.

I guess the change is "*docs: adjust string type to avoid doubling symbols*" (72c32f141a8b230700eb597813203bdd41c0edd3) . To display `"\$A"` correctly, I made this change during development, but now it looks a bit wrong and confusing, at least in my view. I'll check it later, so now switch this PR to a draft.

**Comment by bastimeyer** [comment]
> I guess the change is "_docs: adjust string type to avoid doubling symbols_"

Yes. Strings should not get unnecessarily concatenated. This is very confusing to read, especially if you're mixing f-strings with normal strings.

**Comment by pzhlkj6612** [comment]
Force-pushed what:

1. "_docs: adjust string type to avoid doubling symbols_" (72c32f141a8b230700eb597813203bdd41c0edd3) has been dropped.
2. The fix about ```\$A``` has been put into 0ac38c860b87c8885ef8c02d260e123399b76298 .

**Comment by pzhlkj6612** [comment]
I just discovered that "_docs: use single-backtick inline code block_" (0ac38c860b87c8885ef8c02d260e123399b76298 , or the old commit d02c81e8a3c9e4bfaf25dd4304ee8e04b35f831b) has fixed a wrong style about backslashes introduced by "_docs: use single-backtick inline code block_" (0ae409eecccfd4411325e2ab6187d412ad064cbb). Here is the comparison.

Before 0ae409eecccfd4411325e2ab6187d412ad064cbb :

Man page:

```console
$ man ./docs/_build/man/streamlink.1 | grep --after-context=4 -e 'These characters are replaced with'
              These characters are replaced with an underscore for the rules in use:

                 POSIX  : \x00-\x1F /
                 Windows: \x00-\x1F \x7F " * / : < > ? \ |


```

Webpage:

> <dd><p>These characters are replaced with an underscore for the rules in use:</p>
> <div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">POSIX</span>  <span class="p">:</span> \<span class="n">x00</span><span class="o">-</span>\<span class="n">x1F</span> <span class="o">/</span>
> <span class="n">Windows</span><span class="p">:</span> \<span class="n">x00</span><span class="o">-</span>\<span class="n">x1F</span> \<span class="n">x7F</span> <span class="s2">" * / : &lt; &gt; ? \ |</span>
> </pre></div>
> </div>
> </dd>

After 0ae409eecccfd4411325e2ab6187d412ad064cbb :

Man page:

```console
$ man ./docs/_build/man/streamlink.1 | grep --after-context=4 -e 'These characters are replaced with'
              These characters are replaced with an underscore for the rules in use:

              • POSIX: x00-x1F /

              • Windows: x00-x1F x7F " * / : < > ? |

```

Webpage:

> <dd><p>These characters are replaced with an underscore for the rules in use:</p>
> <ul class="simple">
> <li><p>POSIX: x00-x1F /</p></li>
> <li><p>Windows: x00-x1F x7F " * / : &lt; &gt; ? |</p></li>
> </ul>
> </dd>

**Comment by pzhlkj6612** [comment]
Hi, @bastimeyer , all of my changes are ready to be reviewed.

In addition, thank you for rewriting the PR title. Composing a short but clear title is an art.

**Review by bastimeyer — APPROVED** [review]
Had a deeper look at the changes. Everything's looking fine, thanks.

One minor detail however is how the `Example: ...` and `Examples:\n  ...` sections get rendered in the man page. Since you're now applying inline code after `Example: `, stuff gets rendered as highlighted text, whereas the block text does not. That seems to be an issue with Sphinx though, and this can be ignored. Doesn't matter much anyway.

There's also one tiny issue with an unnecessary non-capture group in one of the new regexes, but it's pretty much irrelevant. If you want to fix it, you can do it before this gets merged.
```diff
diff --git a/docs/ext_argparse.py b/docs/ext_argparse.py
index 55732fab..2066e57e 100644
--- a/docs/ext_argparse.py
+++ b/docs/ext_argparse.py
@@ -26,7 +26,7 @@ _option_re = re.compile(r"(?:^|(?<=\s))(--\w[\w-]*\w)\b")
 _prog_re = re.compile(r"%\(prog\)s")
 _percent_re = re.compile(r"%%")
 _cli_metadata_variables_section_cross_link_re = re.compile(r"the \"Metadata variables\" section")
-_inline_code_block_re = re.compile(r"(?<!`)`((?:[^`])+?)`")
+_inline_code_block_re = re.compile(r"(?<!`)`([^`]+?)`")
 _example_inline_code_block_re = re.compile(r"(?<=^Example: )(.+)$", re.MULTILINE)
```

**Comment by pzhlkj6612** [comment]
Thank you, @bastimeyer .

What do you think about the new commit "_docs: highlight inline code blocks in single-line examples_" (e3dba123d157d28ce2e37e4300de22b8c33c5928)?

**Comment by bastimeyer** [comment]
Please squash 364821bd0f9a89495ddbd3091caffb12e8373e69 into 0ac38c860b87c8885ef8c02d260e123399b76298. PRs should not include commits which fix other commits in the same PR.

IMO, e3dba123d157d28ce2e37e4300de22b8c33c5928 is unnecessary, since all it does is highlight quoted shell arguments in example texts which don't actually have to be quoted. The custom role adds unnecessary complexity.

**Comment by pzhlkj6612** [comment]
Force-pushed what:

1. "_docs: highlight inline code blocks in single-line examples_" (e3dba123d157d28ce2e37e4300de22b8c33c5928) has been dropped due to unnecessary complexity.
2. "_docs: remove a useless non-capturing group_" (364821bd0f9a89495ddbd3091caffb12e8373e69) has been combined with "_docs: use single-backtick inline code block_" (0ac38c860b87c8885ef8c02d260e123399b76298) because we should keep the git history clear. Now the commit is 8eda37d4afa3067c0041759b4866a9178f51b7c0 .

**Pull request merged**
