### PR TITLE
release: 5.1.0

### PR DESCRIPTION
**Pull request by bastimeyer**
Release date is set for tomorrow. I'm going to merge once approved, so I can immediately build the AppImages and Windows releases afterwards.

As usual, only fixes for those plugin are mentioned directly which are more relevant or which had more comments or changes than average.

Full changelog:
https://github.com/streamlink/streamlink/compare/5.0.1...bastimeyer:streamlink:releases/5.1.0

### CODE REVIEW

**Review by gravyboat — APPROVED** [review]

**Comment by gravyboat** [comment]
@bastimeyer Sorry for the delay, busy day at work. Approved, please go ahead whenever you're ready.

**Comment by bastimeyer** [comment]
I'll merge this tomorrow (later today). It's a bit late here.

**Comment by bastimeyer** [comment]
I should probably also add the new `--ffmpeg-no-validation` parameter and the updated dev-requirements to the changelog. #4861

**Comment by bastimeyer** [comment]
I'm thinking about waiting a bit more before releasing 5.1.0...

I'd like to publish 5.1.0 and bump the AppImages and Windows builds to Python 3.11 in one go, and since some cp311 wheels for lxml are still missing (#4903) and since I don't want to include custom lxml builds, I need to wait.

lxml has had issues with their Appveyor CI, because cp311 was not available, including newer VS compiler versions for building libxml2 and libxslt. This was just resolved yesterday on the side of Appveyor, so now all the lxml dev has to do is merge the PRs for the updated build configs, which should happen any time soon. Once they've published new wheels, Streamlink 5.1.0 AppImages and Windows installers and portable archives can be built on top of Python 3.11 instead of 3.10. Considering that Python 3.11 has had some pretty nice performance improvements and that lxml's issues should be resolved soon, I don't want to publish 5.1.0 now and then build new AppImages and Windows releases again on top of 3.11. This is unnecessary work for me and users / third party packagers.

**Comment by gravyboat** [comment]
@bastimeyer I'm fine with waiting. There's nothing especially pressing in this release that can't be delayed. 👍

**Comment by bastimeyer** [comment]
I'll publish 5.1.0 tomorrow after I've come home. The changelog has been updated and should be good to go.

**Pull request merged**
