### PR TITLE
fix livestream.com

### PR DESCRIPTION
**Pull request by Brainzyy**
Thanks @intact for the updated plugin.

### CODE REVIEW

**Comment by cdrage** [comment]
Errr what's happening here? It looks like the `git diff` messed up, is everything indented / spaced by one or something?

**Comment by Brainzyy** [comment]
I'll check it in an hour or so, I'll open a new PR.

Op 23-sep.-2016 16:01 schreef "Charlie Drage" <notifications@github.com>:

**Comment by sbstp** [comment]
Something weird happened to all the pull requests. Extra commits appeared in them. Must be because master was modified with `--force`.

**Comment by gravyboat** [comment]
This looks like a messed up rebase to me where additional history is getting pushed in.

**Comment by sbstp** [comment]
The thing is, it happened in all the of the pull requests at the same time.

**Comment by cdrage** [comment]
@sbstp Must of messed up when I fixed up the changelog in the 0.0.1 release commit. Sorry guys! Weird how github changed all the PR's like that.

**Pull request closed without merging**
