### PR TITLE
Ruv plugin updated. Fixes #643.

### LINKED ISSUE #643: RUV Iceland : plugin partially outdated
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

RUV is Icelandic broadcasting corporation consisting of 3 radio and TV channels : 

1. Radio channels
------------------

- RAS 1 : `http://ruv.is/nolayout/popup/ras1`
- RAS 2 : `http://ruv.is/nolayout/popup/ras2`
- Rondo : `http://ruv.is/nolayout/popup/rondo`

2. TV
-----

- RUV : `http://ruv.is/ruv`
- RUV 2 : `http://ruv.is/ruv-2`
- Krakkaruv : `http://krakkaruv.is/hlusta/spila`

### Expected / Actual behavior

Channels use HLS for broacasting. In the past they used rtmp too, not sure if it's still the case. 

### Reproduction steps / Stream URLs to test

Radio
------

`streamlink -l debug "http://ruv.is/nolayout/popup/ras1"
error: No plugin can handle URL: http://ruv.is/nolayout/popup/ras1`

TV
---

```
streamlink -l debug --http-proxy "82.221.48.137:8080" "http://ruv.is/ruv" best
[cli][info] Found matching plugin ruv for URL http://ruv.is/ruv
[cli][info] Available streams: 720p_hls, 480p_hls, 240p_hls, 360p_hls, 240p (wor
st), 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (rtmp)
[stream.rtmp][debug] Spawning command: C:\Users\Ddr\Downloads\streamlink\\rtmpdu
mp\rtmpdump.exe --flv - --live --pageUrl http://ruv.is/ruv --rtmp rtmp://ruvruvl
ivefs.fplive.net/ruvruvlive-live/stream1
[cli][error] Could not open stream: Error while executing subprocess
```

### Environment details (operating system, python version, etc.)

W7 PRO/streamlink portable

### Comments, logs, screenshots, etc.

TV channels are geolocked unlike radio.

### PR DESCRIPTION
**Pull request by hannespetur**
Hey all,

I have updated the RUV plugin since the current version is highly out-of-date. This PR fixes #643 and contains both many bug fixes and a new feature (support for VODs with multiple qualities available). I have also removed the RTMP stream, since RUV no longer provides that stream.

Note that these streams are usually restricted to Icelandic IP addresses. The only exception is when RUV are showing something they have a full copyright of (i.e. their evening news). Here are some example usages:

**Live stream**
`streamlink http://ruv.is/ruv best`

**Sarpurinn/VOD (with 240p, 360p, 480p, 720p and 1080p available)**
`streamlink ruv.is/spila/ruv/ol-2018-skidafimi-kvenna/20180216 best`

**Sarpurinn/VOD (with only 576p available)**
`streamlink ruv.is/spila/ruv/ol-2018-svig-kvenna-seinni-ferd/20180216 worst`

All the best,
Hannes

### CODE REVIEW

**Comment by back-to** [comment]
you should use there api and not build all urls as a hardcode,
this would most likely cleanup the code.

---

**LIVE** from api

http://www.ruv.is/sites/all/themes/at_ruv/scripts/ruv-stream.php?channel=ruv&format=json
http://www.ruv.is/sites/all/themes/at_ruv/scripts/ruv-stream.php?channel=ruv2&format=json

http://www.ruv.is/sites/all/themes/at_ruv/scripts/ruv-stream.php?channel=ras1&format=json
http://www.ruv.is/sites/all/themes/at_ruv/scripts/ruv-stream.php?channel=ras2&format=json
http://www.ruv.is/sites/all/themes/at_ruv/scripts/ruv-stream.php?channel=ras3&format=json

**VOD** from website

http://www.ruv.is/spila/ruv/ol-2018-listhlaup-karla/20180217

```js
 theoplayer.onReady = function () {
   var video = document.createElement('video');
   video.controls = "controls";
   video.poster = "http://cdn-img.ruv.is/sites/default/files/styles/1200x750/public/kringlumyndir/26243-75-1_0.jpg?";
   video.src = "http://sip-ruv-vod.dcp.adaptive.level3.net/lokad/4953386R12.mp4.m3u8";
   video.className = "player col12";
   video.preload = "none";
   video.autoplay = "autoplay";
   video.style = "width:100%;";
   video.type = "application/x-mpegURL";

   document.getElementById("sarpur-player").appendChild(video);
   var player = theoplayer(video);
```

**Comment by hannespetur** [comment]
> you should use there api and not build all urls as a hardcode,
this would most likely cleanup the code.

I am not seeing a way to get the correct HLS URLs with the api you sent. Can you elaborate?

Best,
Hannes

**Comment by back-to** [comment]
for
http://www.ruv.is/sites/all/themes/at_ruv/scripts/ruv-stream.php?channel=ruv2&format=json
if will get

```json
{
    "result": [
      "rtmp:\/\/ruvruverllivefs.fplive.net\/ruvruverllive-live\/",
      "https:\/\/ruvruverl-live-hls.secure.footprint.net\/ID-TIME\/ruv\/ruv2erl\/index.m3u8"
    ],
    "ipinfo": ["0.0.0.0", "ABC"],
    "user_agent": ["web"]
}
```

---

`https://ruvruverl-live-hls.secure.footprint.net/...-.../ruv/ruv2erl/index.m3u8`

this is the m3u8 url

```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=950400,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360
index/stream1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1390400,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=852x480
index/stream2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2710400,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
index/stream3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4030400,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080
index/stream4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5570400,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080
index/stream5.m3u8
```


```
$ streamlink "https://ruvruverl-live-hls.secure.footprint.net/...-.../ruv/ruv2erl/index.m3u8"
[cli][info] Found matching plugin hls for URL https://ruvruverl-live-hls.secure.footprint.net/...-.../ruv/ruv2erl/index.m3u8
[plugin.hls][debug] URL=https://ruvruverl-live-hls.secure.footprint.net/...-.../ruv/ruv2erl/index.m3u8; params={}
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 98252; Last Sequence: 99051
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 99049; End Sequence: None
[stream.hls][debug] Adding segment 99049 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 99050 to queue
[stream.hls][debug] Adding segment 99051 to queue
[stream.hls][debug] Download of segment 99049 complete
[cli][info] Starting player: /usr/bin/mpv
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 99050 complete
[stream.hls][debug] Download of segment 99051 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 99052 to queue
[stream.hls][debug] Download of segment 99052 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 99053 to queue
[stream.hls][debug] Download of segment 99053 complete
```

can't test all of them because of geo blocking but they should work aswell.

**Comment by hannespetur** [comment]
Amazing find. The API has a 1080p live stream which is not available at the old hard-coded URL! Thank you very much. The latest changed replace the hard-coded URLs with the URLs provided by the API.

Best,
Hannes

**Comment by gravyboat** [comment]
Good stuff, thanks @hannespetur and @back-to!

**Pull request merged**
