### PR TITLE
Merge current most-up-to-date-livestreamer into streamlink

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @LoneFox78 

Thanks so much for all the hard work!

Mind giving this your grace and we could merge this in? :)

This would be a great base to start our fork / dev on streamlink with all the most up-to-date PR's.

**Comment by gravyboat** [comment]
Did anyone confirm all of these work on a fresh build?

**Comment by LoneFox78** [comment]
@gravyboat I did check a random stream for each site. There was one that didn't work (afreecatv.jp) and a few that I couldn't test beacuse of geo restrictions. Also, this was with python 3.5.2, and it is possible that there are problems with older versions of python.

**Comment by cdrage** [comment]
May as well have this merged in so we have a good base.

Did anyone else check some of the major ones (twitch, livestream, etc.)?

**Comment by skulblakka** [comment]
Twitch works fine. So does ustream (only tried the hls stream).

For livestream.com (using the akaimhd stream) I get  ```404 Client Error: Not Found for url: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf```. The hls one works.

**Comment by flijloku** [comment]
@cdrage https://github.com/chrippa/livestreamer/pull/1461 - "goodgame.ru" works fine.

**Comment by cdrage** [comment]
I say that we merge this PR as-is so we're the most up-to-date with everything and start working through all the plugins.

I'm going to try and find some spare time later today to start converting the naming scheme from livestreamer to streamlink within the code and get a good "base release" for streamlink.

**Comment by Brainzyy** [comment]
Azubu.tv does not work with this version. The azubu.py plugin needs to be updated to this one: https://gist.github.com/ThomasReedt/eb55780c1c3d66c61d5b/raw/e4f543d72e3e64ce4dd37e795d3e1dfd6809e720/azubutv.py

**Comment by scottbernstein** [comment]
There is a fix checked into livestreamer for the livestream.com issue.  If nobody else has fixed it, I might try to merge it in later.


________________________________

**Comment by gravyboat** [comment]
@cdrage I'm fine with merging this in and agree with your point regarding it being messy. My main concern is that the primary sites still worked. As such I'm going to merge this.

**Comment by Brainzyy** [comment]
@gravyboat I opened a PR to fix azubu.tv

**Comment by gravyboat** [comment]
@Brainzyy I saw it, I'm going to have to let someone else review it for the time being as I'm not familiar enough with the codebase yet to review it confidently.

**Comment by cdrage** [comment]
@gravyboat thanks for the merge!

Alright. Now it's time to clean-up some of the code! xD

**Pull request merged**
