### PR TITLE
plugins.aloula: add HTTP headers, update matchers

### LINKED ISSUE #5791: plugins.aloula: 403 Client Error: Forbidden for url
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.5.1

### Description

Can't generate stream URL for aloula plugin with forbidden code (403).
Streamlink can play the stream well on latest versions (using external vlc player). but generating --stream-url fails.

Desktop:~$ streamlink https://www.aloula.sa/en/live/sunnatvsa  --stream-url
error: Unable to open URL: https://live.kwikmotion.com/ksasunnalive/ksasunna.smil/playlist_dvr.m3u8?hdnts=exp=1705848372~acl=/ksasunnalive/ksasunna.smil/*~hmac=5ea60ce1704942dc93782e233063d9142c19f4980ea6a4bb856331a08bc73c6c (403 Client Error: Forbidden for url: https://live.kwikmotion.com/ksasunnalive/ksasunna.smil/playlist_dvr.m3u8?hdnts=exp=1705848372~acl=/ksasunnalive/ksasunna.smil/*~hmac=5ea60ce1704942dc93782e233063d9142c19f4980ea6a4bb856331a08bc73c6c)

### Debug log

```text
andalus@Desktop:~$ streamlink https://www.aloula.sa/en/live/sunnatvsa  --loglevel=debug
[cli][debug] OS:         Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.12
[cli][debug] OpenSSL:    OpenSSL 3.0.2 15 Mar 2022
[cli][debug] Streamlink: 6.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.4
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.aloula.sa/en/live/sunnatvsa
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin aloula for URL https://www.aloula.sa/en/live/sunnatvsa
[utils.l10n][debug] Language code: en_US
Available streams: 360p (worst), 480p, 1080p (best)
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Fixes #5791 

```
$ ./script/test-plugin-urls.py aloula
:: Finding streams for URL: https://www.aloula.sa/en/episode/6676
:::: This stream requires a login; specify appropriate Authorization and profile HTTP headers
!! No streams found
:: Finding streams for URL: https://www.aloula.sa/en/live/saudiatv
:: Found streams: 360p, 480p, 1080p, worst, best
:: Finding streams for URL: https://www.aloula.sa/episode/6676
:::: This stream requires a login; specify appropriate Authorization and profile HTTP headers
!! No streams found
:: Finding streams for URL: https://www.aloula.sa/live/saudiatv
:: Found streams: 360p, 480p, 1080p, worst, best
```

### CODE REVIEW

**Comment by bastimeyer** [comment]
Btw, @andaluspc, if you're just getting the HLS playlist URL using `--stream-url`, then you have to set the `Origin` and `Referer` headers manually.

**Comment by andaluspc** [comment]
Hello @bastimeyer . Thank you.
I use streamlink to get the m3u8 URL then I store it in my m3u8 playlist which is being played by my TV application.
Would there be a way to pass `Origin `and `Referer `headers in in my m3u8 in EXTINF tag (or any other tag)? I can't a supportive documentation about if this can be done. I hope I am not at a dead end!

**Comment by bastimeyer** [comment]
This is not how any of this works. The application which sends the HTTP requests to the HLS playlist/segment URLs has to set those headers. If you're using Streamlink to just resolve the HLS playlist URL without using its own HLS download logic, then you're on your own. Good luck.

**Comment by andaluspc** [comment]
Ya.. it seems so. but it is a good challenge so I start providing a solution for such issues :)
Thank you again Sebastian. Appreciate all your support so far.

**Pull request merged**
