### PR TITLE
[qq] New Plugin for live.qq.com

### PR DESCRIPTION
**Pull request by back-to**
Fixed https://github.com/streamlink/streamlink/issues/1190

### CODE REVIEW

**Comment by gravyboat** [comment]
@back-to What is the content on this site like? I just want to be sure we aren't merging in a new plugin that's used to restream stolen content.

**Comment by back-to** [comment]
i don't know, i can't read anything in chinese

i only checked that **Tencent** is the owner of `qq.com` and
they have like all livestreaming rights in china.

https://www.theverge.com/2017/8/22/16182754/nfl-tencent-china-streaming-deal
https://www.si.com/nba/2015/01/29/nba-deal-china-tencent

so they must tolerate or permit it at least.

or maybe china has just some other / no rules.

**I don't care if it gets merged or not.**

**Comment by karlo2105** [comment]
Qq.com is just a video hosting as youtube, so I don't see any issues with merging. On the other hand if it's available freely there is not any big deal.

**Comment by gravyboat** [comment]
Thanks @back-to!

**Pull request merged**
