### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by stepshal**

### CODE REVIEW

**Comment by beardypig** [comment]
Thanks! If you are going to do more of these PEP8 fixed can you roll them up into one PR?

**Comment by stepshal** [comment]
@beardypig are you gonna accept all of them? Because some of them was not merged in other projects. I put all non-aggressive autopep8 fixes in this PR. Check out changes.

**Comment by beardypig** [comment]
Most of them I will accept, if you put them in separate commits with the appropriate message it will be easier to filter out the ones that we don't want. 
Can you drop the line length limit (E501 I think).

**Comment by beardypig** [comment]
All of those look reasonable to me, thanks :)

**Comment by stepshal** [comment]
I'm done. Except E265, don't know about this one.

**Comment by beardypig** [comment]
Cool, looks good... E309 isn't part of PEP8, it's part of PEP257 and it doesn't look like `autopep8` does it correctly.

**Comment by stepshal** [comment]
@beardypig Ok, reverted it.

**Comment by gravyboat** [comment]
@beardypig these look good to me, any other concerns/questions? If not @stepshal can you rebase after https://github.com/streamlink/streamlink/pull/417 is merged?

**Comment by stepshal** [comment]
@gravyboat No. Done.

**Comment by gravyboat** [comment]
@beardypig If you don't have any comments when you're around tomorrow let's squash and merge this.

**Comment by beardypig** [comment]
Looking good to merge. @stepshal thanks for breaking them out in to separate commits, that must have been a bit of a pain :) Good job!

**Comment by gravyboat** [comment]
@beardypig Do you want to keep all these PRs separate in the event we need to roll back? If not I would like to squash since it's a large number of commits and it might crowd the history.

**Comment by beardypig** [comment]
Yeah squash it!

**Comment by gravyboat** [comment]
Done, thanks @stepshal!

**Pull request merged**
