### PR TITLE
plugins.pluto: fix URL match for 2 letter language codes

### PR DESCRIPTION
**Pull request by mkbloke**
fixes #3959

### CODE REVIEW

**Comment by bastimeyer** [comment]
Please add tests for the updated URL matcher.

**Comment by mkbloke** [comment]
Oops, I forgot about updating the tests... should be OK now, cheers.

**Comment by mkbloke** [comment]
Actually, I might just add some extra checks for the language letter stuff on the 'should not match' side.

**Comment by mkbloke** [comment]
Ah, never mind!

**Pull request merged**
