### PR TITLE
plugins.vaughnlive: find the info url from the SWF file

### LINKED ISSUE #690: vaughnlive error: Unable to validate response text: '' does not equal '<error></error>' or Minimum length is 3 but value is 1
Using latest nightly and this plugin

https://github.com/streamlink/streamlink/pull/383/files/4f7d4f683ce61c0d10908d71603e8df40d744a27..0de2ede40755ee4b76fac8b2d9c8d3204f649b0a

Thank you

### PR DESCRIPTION
**Pull request by beardypig**
This PR is a followup to #378 and should also fix #690. 

It works by downloading the SWF and searching for the info url, player version, etc.

### CODE REVIEW

**Comment by gravyboat** [comment]
@beardypig Ugh I merged @mmetak's PR prior to seeing this one, can you rebase? Sorry.

**Comment by beardypig** [comment]
@gravyboat rebased 💥

**Comment by gravyboat** [comment]
Thanks @beardypig!

**Comment by Ordval** [comment]
Can somebody verify if this still is working ? for me, not.
I've pasted the latest  756743f/ #693 the “Click here to learn more” is Chinese to me 
unless it means 'no change'.  

> The commit did not affect project coverage.  (Codecov Delta)

**Comment by mmetak** [comment]
@Ordval I check vaugnlive.tv channel almost daily and it works just fine for me.
(running latest streamlink git commit)

**Comment by Ordval** [comment]
Thank You! Well, I'll get back to this later, can't even get into their webpage now,
but if it's about having the latest .exe's they're both there. 
Did as previously proposed: uninstalled then a reinstall. 
Tried the regular .exe before installing the Nightly build.

**Comment by Ordval** [comment]
I'm getting the same as JourneyOver (#378):
> C:\Program Files (x86)\Streamlink Nightly build\Streamlink\bin>streamlink.exe "http://vaughnlive.tv/platinum_hd" best
> [cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/platinum_hd
> error: Unable to validate response text: '' does not equal '<error></error>' or Minimum length is 3 but value is 1
> C:\Users\Ordval>call streamlink.exe "https://vaughnlive.tv/416moviez" best
> [cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/416moviez
> error: Unable to open URL: https://vaughnlive.tv/416moviez (503 Server Error: Service Temporarily Unavailable for url: https://vaughnlive.tv/416moviez)

Both tested while active, with http: and https.
Haven't restarted the computer though after the reinstall.

**Comment by beardypig** [comment]
There were some site issues before, but they are resolved. The plugin still works for me. I will double check that the "latest" installer is still installing the latest version.

**Comment by Ordval** [comment]
Thanks for the check up.

> C:\Program Files (x86)\Streamlink Nightly build\bin>streamlink.exe "https://vaughnlive.tv/416moviez" best
> [cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/416moviez
> [cli][info] Available streams: live (worst, best)
> [cli][info] Opening stream: live (rtmp)
> [cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=50500

**Pull request merged**
