### PR TITLE
plugins.dogus: add startv URL

### PR DESCRIPTION
**Pull request by hymer-up**

### CODE REVIEW

**Comment by hymer-up** [comment]
https://github.com/streamlink/streamlink/commit/dcdb08a354d0c248930e366dc9e2dc18fc8cbf2a

**Comment by mkbloke** [comment]
You should also update: https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/.removed for removed plugins.

I don't know for sure in this particular case, but it's possible that you'll be asked to split the plugin update and the plugin removal into separate PRs by the devs.

Hope that's useful.  Cheers.

**Comment by gravyboat** [comment]
Yep please split the removal PR and the plugin update just so we have it correctly for the git history.

**Comment by hymer-up** [comment]
#3163

**Review by bastimeyer — CHANGES_REQUESTED** [review]
Please add regex tests for the new URL

**Review by bastimeyer — APPROVED** [review]

**Pull request merged**
