### PR TITLE
streamlink.plugins: replace global http session by self.session.http

### PR DESCRIPTION
**Pull request by Billy2011**
Global http session obj should not be used because there may be problems
with other server/proxy applications.

### CODE REVIEW

**Comment by beardypig** [comment]
I like it. But, why is this commit 32e2458954beabb8fc84d47ee6800ccd685a10e9 included? Shouldn't you rebase on the upstream master to get this included.

**Comment by Billy2011** [comment]
All PR's end up with me - it is no longer possible to create a PR for streamlink???

**Comment by back-to** [comment]
I think it should work now, if you push something to `Billy2011:api-http-fix`

**Comment by beardypig** [comment]
What's happening here? :D

**Comment by Billy2011** [comment]
I've been wondering the same thing all day (•ิ_•ิ)?

**Comment by Billy2011** [comment]
How can I fix the test plugins garena + tvplayer?
That, for example, no longer exists: `streamlink.plugins.garena.http`

**Comment by beardypig** [comment]
@Billy2011 https://github.com/Billy2011/streamlink/pull/10 :)

**Comment by back-to** [comment]
Missed 2 plugins.

https://github.com/Billy2011/streamlink/blob/api-http-fix/src/streamlink/plugins/bongacams.py#L48-L49
https://github.com/Billy2011/streamlink/blob/api-http-fix/src/streamlink/plugins/tvrplus.py#L30

**Comment by Billy2011** [comment]
I guess I was too frustrated yesterday :-D

**Comment by Billy2011** [comment]
Must the global var. `api.http` and all remaining references to it be preserved?

**Comment by beardypig** [comment]
Anything that referrers to the global should be removed. While it won’t help with the thread safety, we will have more control - for example, we could create one session per thread ID (not sure if that’s actually a workable idea).

**Comment by Billy2011** [comment]
I think the last reference to api.http is in streamlink.session, should I remove that?

**Comment by beardypig** [comment]
>I think the last reference to api.http is in streamlink.session, should I remove that?

@Billy2011 Can you post a line reference? Maybe that one will have to be done separately :)

**Comment by Billy2011** [comment]
@beardypig, in line #469    api.http = self.http

**Comment by beardypig** [comment]
@Billy2011 I believe that would make it a breaking change. We should open a separate PR for that, and probably keep it open until we are ready for `1.0.0` :)

**Comment by Billy2011** [comment]
OK, then I hope that this PR is ready to merge and no other member raises an objection :)

**Comment by gravyboat** [comment]
Alright let's get this in then, thanks for the hard work @Billy2011, and for the feedback everyone!

**Pull request merged**
