### PR TITLE
plugins.tvplayer: allow https stream URLs

### PR DESCRIPTION
**Pull request by beardypig**
Additional fix for #849, changed since the original PR #850.

### CODE REVIEW

**Comment by nicr4wks** [comment]
Thanks @beardypig ! Confirmed working.

**Comment by beardypig** [comment]
No problem, I think they must have changed it since my original PR :(

**Comment by gravyboat** [comment]
If this service continues changing I'm going to add it to the list of services not worth supporting. Thanks @beardypig.

**Comment by beardypig** [comment]
To be fair if hasn't changed for a couple of years and they just had a new design, I doubt it'll change again anytime soon :-)

**Comment by gravyboat** [comment]
Hopefully so!

**Pull request merged**
