### PR TITLE
Update Windows portable version documentation

### PR DESCRIPTION
**Pull request by RosadinTV**

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me!

**Comment by RosadinTV** [comment]
@gravyboat Kinda strange but the font size in "Package maintainers > Windows port. version" is bigger than the others.
package maintainers font bug

**Comment by gravyboat** [comment]
@RosadinTV I think it has to do with the way the table has been broken up due to multiple entries, maybe try removing line 108? I wonder if the blank line is breaking it somehow.

**Comment by RosadinTV** [comment]
@gravyboat I don't know, it seems like the format changes when converted to html in the repository "streamlink.github.io", so the results may be unexpected.
I'm a bit afraid of doing several trial-and-error commits, but let me know if you want me to change anything.

**Comment by gravyboat** [comment]
You can build the docs locally if you want to test it first, I'm not too concerned though, I would just go with the comma if you're worried about making too many. We need to fix it anyways.

**Comment by RosadinTV** [comment]
Now works as expected, thanks @gravyboat 💝

**Comment by gravyboat** [comment]
@RosadinTV Awesome! If we have one of these again let's make sure to PR it instead of pushing directly to master, just makes it easier to track and roll back if we need to! Thanks for fixing that up.

**Comment by RosadinTV** [comment]
@gravyboat Sorry, I'll keep that in mind for the next one 🚀

**Comment by gravyboat** [comment]
No worries it happens! Thanks again for the quick fix.

**Pull request merged**
