### PR TITLE
plugins.twitch: new plugin command --twitch-api-header

### PR DESCRIPTION
**Pull request by back-to**
- can be used for `Authorization` or other headers
- change PlaybackAccessToken playerType to `site` as `embed` will show ads
- remove some unsed HLS and headers code

---

```
streamlink https://twitch.tv/twitch best \
    --twitch-api-header "X-Device-Id=twitch-web-wall-mason" \
    --twitch-api-header "Device-Id=twitch-web-wall-mason"
```

closes https://github.com/streamlink/streamlink/pull/4080

### CODE REVIEW

**Review by bastimeyer — COMMENTED** [review]
It's GQL (Graph Query Language), not GPL.

Adding a generic parameter for adjusting the API requests headers makes more sense than adding multiple ones for specific authentication/identification methods, so I'm in favor of that. The problem here though is that it's not particularly user-friendly, but neither is extracting headers from the web browser, so it's fine.

**Comment by bastimeyer** [comment]
It might be better to just call it `twitch-api-header`. This is less confusing, people don't have to memorize specific names (gql) and it's shorter (no http-).

**Comment by bastimeyer** [comment]
`playerType="site"` also causes (preroll-)ads. There's no difference. Did you get midroll ads with `embed` or why did you change it?

**Comment by back-to** [comment]
server_ads will be False with `site` but True with `embed`

`[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': False, 'show_ads': True}`

when used with 

```
streamlink https://twitch.tv/twitch best \
    --twitch-api-header "X-Device-Id=twitch-web-wall-mason" \
    --twitch-api-header "Device-Id=twitch-web-wall-mason"
```

**Review by bastimeyer — APPROVED** [review]

**Pull request merged**
