### PR TITLE
TVPlayer.com: fix for 400 error, correctly set the platform parameter

### PR DESCRIPTION
**Pull request by beardypig**
The User-Agent header needs to be sent for the page to fill in the correct platform variable.

### CODE REVIEW

**Comment by gravyboat** [comment]
Thank you.

**Comment by gravyboat** [comment]
@beardypig do you want an invite to the Streamlink org? You've contributed a good amount and I think we're pretty open to adding people if they are interested (@cdrage please confirm).

**Comment by beardypig** [comment]
Sure, I'm interested :)

**Comment by beardypig** [comment]
@gravyboat thanks :-D

**Comment by cdrage** [comment]
@beardypig add you mannn

**Comment by gravyboat** [comment]
@cdrage That was me, I figured you would be fine with it since there wasn't an immediate 'no' response. @beardypig No problem!

**Pull request merged**
