### PR TITLE
plugins.aljazeeraen: plugin removal

### LINKED ISSUE #3198: aljazeera error
[cli][info] Found matching plugin aljazeeraen for URL https://www.aljazeera.com/live/
[plugin.aljazeeraen][error] Could not find a video ID on this page
error: No playable streams found on this URL: https://www.aljazeera.com/live/

### PR DESCRIPTION
**Pull request by mkbloke**
I had a look at reverse engineering the JS to get to the eventual playlist URL, but quite honestly, it just didn't seem worthwhile given the live stream playlist URL looks to be static.

closes #3198

### CODE REVIEW

**Comment by back-to** [comment]
> but quite honestly, it just didn't seem worthwhile given the live stream playlist URL looks to be static.

just remove the plugin instead of using a static URL in a plugin file.

also  there is https://www.youtube.com/channel/UCNye-wNBqNL5ZzHSJj3l8Bg

**Comment by mkbloke** [comment]
> just remove the plugin instead of using a static URL in a plugin file.

Fair enough.  I guess I was just trying to keep the plugin while the VOD side was still functional.

I'll change this PR to a plugin removal.  Cheers.

**Comment by mkbloke** [comment]
I don't know what the codecov issue is.  Let me know if it's something I can fix or do differently, cheers.

**Comment by bastimeyer** [comment]
> I don't know what the codecov issue is.

An oversight/mistake by me with the new test coverage config, sorry about that. Apparently removing (fully covered) tests will reduce the coverage by a small percentage, since there are a few lines in the overall tests which are not fully covered, and the config doesn't accept a reduction percentage-wise in the tests scope. I didn't think about that.

For now, you can either rebase onto the 1.6.0 commit, or wait until a config fix was merged and rebase onto that. I will submit a PR soon/later.

What annoys me a bit is that codecov still hasn't fixed the checklist inline summary text, and it's still only showing "Codcov report".

**Pull request merged**
