### PR TITLE
build: include correct signing key: 0xE3DB9E282E390FA0

### LINKED ISSUE #2929: Unknown signing key for release 1.4.0
## Bug Report

- [X] This is a bug report and I have read the contribution guidelines.

### Description

The latest release 1.4.0 is signed with the key `C85DFC2B93847AB978BB1476D70949F46BA8C77B` but it was `0xE3DB9E282E390FA0` for previous releases.

I'm being a bit picky here, but I can't find anything about that new key.
As part of the packaging for Debian, I'm verifying the signing key, so I would need the public key of the signing key (which I can't find on keyservers).

Is this release key change expected ?

### Expected / Actual behavior

Expected: the release 1.4.0 to be signed with the gpg key `0xE3DB9E282E390FA0 `
Actual behavior: the release is signed with a key `0xD70949F46BA8C77B` for which I can't find its public key for authentication.

### Reproduction steps / Explicit stream URLs to test

```
$ gpg --verify streamlink-1.4.0.tar.gz.asc streamlink-1.4.0.tar.gz
gpg: Signature made Wed Apr 22 19:56:35 2020 CEST
gpg:                using RSA key C85DFC2B93847AB978BB1476D70949F46BA8C77B
gpg: Can't check signature: No public key
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### PR DESCRIPTION
**Pull request by beardypig**
I didn't check the signing key last time, this is the correct key with the correct ID. 

Resolves #2929.

### CODE REVIEW

**Comment by beardypig** [comment]
I guess we should release a `1.4.1` with the correct signature ...

**Comment by bastimeyer** [comment]
Well, I can't verify the key file without having the decryption passphrase, but let's merge this anyway. I don't think a test release on a fork / secondary account is necessary.

Would you please be so kind and open a PR for 1.4.1?

**Comment by beardypig** [comment]
@bastimeyer I'm not entirely sure of the process for opening a release PR now :)

**Comment by bastimeyer** [comment]
No problem. Let me do it.
Btw, we should remove or replace the `script/release.sh` script later.

**Pull request merged**
