### PR TITLE
0.0.1 Release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
This is part of automated release script / generated CHANGELOG. 

Once this is merged in / ACK'd, I'll continue with the Pypi release and update the README with the corresponding installation tutorial.

**Comment by sbstp** [comment]
Do you want the windows installer to be ready for this release?

**Comment by cdrage** [comment]
@sbstp Honestly I wouldn't. I'm doing this as a "base release". It'll be nice to have the Windows installer next release cause we can actually showcase it / blog post about it more explicitly.

**Comment by sbstp** [comment]
Could you make a shortlog of the commits that were merged since livestreamer's current master? That way we can point at nearly a year's worth of fixes.

**Comment by cdrage** [comment]
@sbstp DONE! Give me your LGTM after you've reviewed and we can get the release underway :)

**Comment by sbstp** [comment]
> Below is a complete shortlog of all past commits as well as the merged changes
Should probably be changed to match the new shortlog.

After that, all good.

**Comment by gravyboat** [comment]
This looks good to me.

**Comment by cdrage** [comment]
Done! Let's merge this and get a release out :)

**Comment by sbstp** [comment]
Is the version at the top supposed to be 0.0.0 in `CHANGELOG.md`?

**Comment by cdrage** [comment]
@sbstp ah poop, i've updated that in the master. thanks for the update

**Pull request merged**
