### PR TITLE
plugins.dlive: fix live playback

### PR DESCRIPTION
**Pull request by Billy2011**

### CODE REVIEW

**Comment by Billy2011** [comment]
@bastimeyer why did you remove the vod support?

**Comment by bastimeyer** [comment]
@Billy2011 Apologies, I was under the impression that it was broken for now and removed it without checking it. Re-implemented it now.

Also hope it's okay that I've pushed onto your PR branch, but I didn't want to add review comments for a proper rewrite. Squashing this PR will preserve the authors of all commits.

**Comment by Billy2011** [comment]
> Also hope it's okay that I've pushed onto your PR branch, but I didn't want to add review comments for a proper rewrite.

That wasn’t so good for me. I wanted to make a git rebase, but since I didn’t notice your commit, my local branch is now broken due to several failed attempts.

**Comment by bastimeyer** [comment]
There is no "broken" in git. Just fetch your fork's remote, and then [force your local branch to the commit ID](https://git-scm.com/docs/git-branch#Documentation/git-branch.txt---force) (`84cd2f0`) of the updated branch on the fork repo to re-align them.

**Comment by Billy2011** [comment]
> Just fetch your fork's remote,

I’ve tried that a few times, but your changes don’t appear in my commit history.

**Comment by bastimeyer** [comment]
Now you've pushed a merge commit onto the PR branch for some reason and it includes unrelated commits that disappear in the overall diff as those are already on the master branch. That's not how it's supposed to be. I don't understand why you'd want to rebase, as the PR will get squashed on merge anyway.

Just keep it as it is now, please.
And btw, the coverage status failure is caused by something else, so don't worry about it.

**Comment by Billy2011** [comment]
@bastimeyer I think it’s better if you do another force push.

**Comment by Robby-** [comment]
I'm [side-loading](https://streamlink.github.io/cli.html#sideloading-plugins) this fixed version of the plugin and testing it with live streams, and it seems to work nicely.

**Comment by Billy2011** [comment]
> However, the test link specified in test_dlive.py doesn't work:

This only checks the validity of the link.

But this link runs: [https://dlive.tv/p/pdp+3mTzOl4WR](https://dlive.tv/p/pdp+3mTzOl4WR)

**Pull request merged**
