### PR TITLE
[zdf] apiToken update

### PR DESCRIPTION
**Pull request by back-to**
Fixed streamlink/streamlink#1329

### CODE REVIEW

**Comment by gravyboat** [comment]
This looks good to me, have you confirmed that the API key won't be a problem as you noted here: https://github.com/streamlink/streamlink/issues/1329#issuecomment-343966308

**Comment by back-to** [comment]
it won't be a problem,
the plugin will always get the API key from the website.

**Comment by gravyboat** [comment]
Sounds good, wasn't sure if you were expecting them to change their methods again. Thanks!

**Comment by velvetant** [comment]
This problem seems to have appeared again. Still worked the day before yesterday.

```
streamlink https://www.zdf.de/sport/olympia/olympia-live-one-102.ht
ml
[cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/sport
/olympia/olympia-live-one-102.html
error: Unable to open URL: https://api.zdf.de/content/documents/olympia-live-one
-102.json?profile=player (403 Client Error: Forbidden for url: https://api.zdf.d
e/content/documents/olympia-live-one-102.json?profile=player)
```

**Pull request merged**
