### PR TITLE
docs: add basic development setup guide

### PR DESCRIPTION
**Pull request by bastimeyer**
As mentioned in #3244, this adds a **basic** guide for setting up a dev environment and running tests, etc. locally. In the future, this can be extended with guides on how to write plugins, but for now, this is enough.

And of course the pull request template with a link to the new docs section.

Happy to discuss any changes/improvements/additions...

### CODE REVIEW

**Comment by Billy2011** [comment]
> source ~/venvs/streamlink/bin/activate

For me (Win 10 PC) this works `source ~/venvs/streamlink/Scripts/activate`

> $ make --directory=docs clean html

```
make: Entering directory `C:/Users/kschm/Documents/GitHub/streamlink/docs'
rm -rf _build/*
sphinx-build -b html -d _build/doctrees  -W . _build/html
process_begin: CreateProcess(NULL, sphinx-build -b html -d _build/doctrees -W . _build/html, ...) failed.
make (e=2): Das System kann die angegebene Datei nicht finden.
make: *** [html] Fehler 2
make: Leaving directory `C:/Users/kschm/Documents/GitHub/streamlink/docs'
```

**Comment by Billy2011** [comment]
> pip install -r dev-dependencies.txt
> pip install -r docs-dependencies.txt

`dependencies` must be replaced by `requirements`

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-requests is basically the same,
might delete it there

**Comment by mkbloke** [comment]
Looks good.  I was thinking about trying to help with this aspect of the documentation also.  You could add (or I could do so after this has been merged) a table describing the matrix of files to update for different scenarios.  This is something I had in mind.

The idea was to describe for example:

- plugin modification: files and reasons to update: ```plugin.py```; ```test_plugin.py```; ```plugin_matrix.rst```
- plugin addition: files and reasons to create/update: ```plugin.py```; ```test_plugin.py```; ```plugin_matrix.rst```
- plugin removal: files and reasons to delete/update: ```plugin.py```; ```test_plugin.py```; ```plugin_matrix.rst```; ```.removed```

**Comment by gravyboat** [comment]
Looks good to me, merging.

**Pull request merged**
