### PR TITLE
[Douyutv] fix API

### LINKED ISSUE #1102: July 17 Douyu.com error
0.7.0
streamlink https://www.douyu.com/17732 source -o "PATH & FILENAME"
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/17732
error: Unable to open URL: https://www.douyu.com/lapi/live/getPlay/17732 (500 Server Error: Internal Server Error for url: https://www.douyu.com/lapi/live/getPlay/17732)
@fozzysec @steven7851

### LINKED ISSUE #1370: Douyu Client error 403 after 1hour +
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Douyu streams links are expiring i believe and that gives 403 client error or it can be related to something else too
...

### Expected / Actual behavior

Not expiring stream.

### Reproduction steps / Explicit stream URLs to test

1. .Start Douyu Stream
2. Wait 1h + 
3. Stream stops and the error appears

### Environment details

Operating system and version: Win10
Streamlink and Python version: 0.9.0 , Python 3.6.1

### Comments, logs, screenshots, etc.

Printscreen. https://i.imgur.com/8J96NjG.png

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### LINKED ISSUE #1393: Error Douyu
error: Unable to validate JSON: Unable to validate key 'data': u'' does not equal None or Type of u'' should be 'dict' but is 'unicode'
help me, pls.

### PR DESCRIPTION
**Pull request by steven7851**
fix #1393, fix #1370, fix #1102

### CODE REVIEW

**Comment by meesudzu** [comment]
hey, it doesn't fix. I still have this error. 
screenshot from 2017-12-29 20-44-52

**Comment by steven7851** [comment]
I have tried 71017 and it's working fine.
You should copy [this file](https://raw.githubusercontent.com/steven7851/streamlink/6f23c7f840dc3f151f42baacdba1614ae3eb7217/src/streamlink/plugins/douyutv.py) into ```/streamlink/plugins```.

**Comment by meesudzu** [comment]
thanks, it working.

**Comment by gravyboat** [comment]
Thanks @steven7851!

**Pull request merged**
