### PR TITLE
plugins.tvplayer: small update to channel id extraction

### LINKED ISSUE #1059: tvplayer plugin broken
https://tvplayer.com/watch/bbcone
Unable to open URL: http://api.tvplayer.com/api/v2/stream/live (400 Client Error: Bad Request for url: http://api.tvplayer.com/api/v2/stream/live)

### PR DESCRIPTION
**Pull request by beardypig**
Should fix #1059.

### CODE REVIEW

**Comment by Vangelis66** [comment]
Many thanks, but where exactly has https://github.com/streamlink/streamlink/issues/1059 gone ???

**Comment by unlocKing** [comment]
Looks like #1059 and #1067 have both been deleted

**Comment by beardypig** [comment]
Oops forgot to update the tests too...

**Comment by beardypig** [comment]
Perhaps the user that created them has been blocked by github for posting URLs...

**Comment by gravyboat** [comment]
Good stuff, thanks @beardypig!

**Pull request merged**
