### PR TITLE
Release 0.14.1

### PR DESCRIPTION
**Pull request by beardypig**

### CODE REVIEW

**Comment by cdrage** [comment]
LGTM

**Comment by gravyboat** [comment]
Looks good to me as well, merging.

**Comment by beardypig** [comment]
@gravyboat just the tag.

**Comment by back-to** [comment]
this changelog is now outdated

**Comment by beardypig** [comment]
Merged in the wrong order :)

**Comment by gravyboat** [comment]
@back-to Yeah there have been other merged PRs since then which is a problem. @beardypig What do we want to do in situations like this? Seems like we should generate a new updated changelog, but will that break things? I should have merged this first but opened about 20 things in my notifications and just went through them in order.

**Comment by beardypig** [comment]
Well, I guess we could skip 0.14.1 and just have 0.14.2 with the changes from both.

**Comment by beardypig** [comment]
@gravyboat are you able to jump on gitter for 10 mins?

**Pull request merged**
