### PR TITLE
[zattoo] New plugin for zattoo.com / tvonline.ewe.de / nettv.netcologne.com

### LINKED ISSUE #804: Plugin for zattoo.com
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Could You please add a plugin for https://zattoo.com, a livestreaming platform on which many TV stations are streamed. There are about 70 channels on the free version and about 90 channels in the premium version.

Sorry for grammatic mistakes if done and thanks a lot.
...

### PR DESCRIPTION
**Pull request by back-to**
**New plugin for zattoo**

- zattoo.com
- tvonline.ewe.de
- nettv.netcologne.com

Should work fine. I tested it over the last weeks.

---

Some part of this code is is not necessary, but it's **easier to debug if something fails**.
like this one, you can see what channels are available in your country.

```py
zattoo_list = []
for c in c_list:
    zattoo_list.append(c['display_alias'])
    if c['display_alias'] == channel:
        cid = c['cid']

self.logger.debug('Available zattoo channels in this country: {0}'.format(', '.join(sorted(zattoo_list))))
```

---

For every login it will **cache** the cookies for **24h**.
If you want to use a different Account you need to wait 24h or delete `plugin-cache.json`

---

Fixed #804

### CODE REVIEW

**Comment by beardypig** [comment]
Looks good, you could add a `--purge-credentials` option, similar to the crunchyroll plugin - a bit better than deleting the plugin cache.

**Comment by back-to** [comment]
**I don't have an interest in adding a purge option**

the 24h cache in `plugin-cache.json` was just **an information** **not an instruction**

normally there is no point in deleting it,

only if someone wants to use a different account,
but the same again there is no point in having two accounts.

**Comment by karlo2105** [comment]
@back-to 
Thanks for making this plugin. 
May I ask what was the reason of your plugins repository removal ?

**Comment by back-to** [comment]
I had a typo in the file,
```diff
-        if self._expires:
+        if self._authed:
```
since **--zattoo-purge-credentials** was just some lines I added it with it.

You can now remove your session ids with

```
streamlink https://zattoo.com/watch/sport1 --zattoo-purge-credentials
```

**Comment by karlo2105** [comment]
Thanks very much.
May i ask know a link to your streamlink plugins?

**Comment by back-to** [comment]
I don't have a link,
i host my custom plugins locally, so there is no access from the internet.

I wanted to delete zattoo from it, since it hase login args and thats easier if its in streamlink itself.

@karlo2105

**Comment by karlo2105** [comment]
I hope you will pull requests from your local git too. ;)

**Comment by gravyboat** [comment]
I let this fall through the cracks, sorry @back-to. Talk about a complicated plugin! I appreciate you adding tests and getting the matrix updated.

**Pull request merged**
