### PR TITLE
plugins.dogan: find direct HLS URL

### LINKED ISSUE #5297: plugins.dogan: CnnTurk and KanalD doesn't show live TV
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

stulluk ~ $  streamlink --version
streamlink 5.4.0
stulluk ~ $

Thank you very much for this plugin. it works beautifully with "teve2" as follows: 

`streamlink https://www.teve2.com.tr/canli-yayin best`

And it shows the live TV show.

However, it doesn't show liveTV streams of CnnTurk and KanalD.

To reproduce, one can compare played streams by checking live TV from the corresponding website via web browser.

I provide debug log below, but I am not sure if this is helpful at all, because below debug log is just fine, however played video is not live TV (some other advertisement is being played)

### Debug log

```text
stulluk ~ $  streamlink https://www.kanald.com.tr/canli-yayin best -l all
[13:14:12.746759][cli][debug] OS:         Linux-6.2.10-060210-generic-x86_64-with-glibc2.35
[13:14:12.746857][cli][debug] Python:     3.10.6
[13:14:12.746898][cli][debug] Streamlink: 5.4.0
[13:14:12.747355][cli][debug] Dependencies:
[13:14:12.749140][cli][debug]  certifi: 2020.6.20
[13:14:12.749491][cli][debug]  isodate: 0.6.1
[13:14:12.749835][cli][debug]  lxml: 4.8.0
[13:14:12.750241][cli][debug]  pycountry: 20.7.3
[13:14:12.750469][cli][debug]  pycryptodome: 3.17
[13:14:12.751129][cli][debug]  PySocks: 1.7.1
[13:14:12.751392][cli][debug]  requests: 2.28.2
[13:14:12.753761][cli][debug]  urllib3: 1.26.5
[13:14:12.754057][cli][debug]  websocket-client: 1.2.3
[13:14:12.754299][cli][debug]  importlib-metadata: 4.6.4
[13:14:12.754439][cli][debug] Arguments:
[13:14:12.754480][cli][debug]  url=https://www.kanald.com.tr/canli-yayin
[13:14:12.754517][cli][debug]  stream=['best']
[13:14:12.754558][cli][debug]  --loglevel=all
[13:14:12.754722][cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
[13:14:12.864279][plugins.dogan][debug] Loading content: 542410a361361f36f4c3fcf1
[13:14:12.951559][utils.l10n][debug] Language code: en_US
[13:14:13.319823][stream.hls_playlist][all] #EXT-X-VERSION:3
[13:14:13.319996][stream.hls_playlist][all] #EXT-X-STREAM-INF:BANDWIDTH=510400,RESOLUTION=640x360,CODECS="avc1.42c01e,mp4a.40.2"
[13:14:13.320122][stream.hls_playlist][all] kanald-v0/playlist.m3u8?live=true&app=com.kanald&min=0&max=1250
[13:14:13.320311][stream.hls_playlist][all] #EXT-X-STREAM-INF:BANDWIDTH=1445400,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2"
[13:14:13.320415][stream.hls_playlist][all] kanald-v1/playlist.m3u8?live=true&app=com.kanald&min=0&max=1250
[13:14:13.321506][cli][info] Available streams: 360p (worst), 720p (best)
[13:14:13.321740][cli][info] Opening stream: 720p (hls)
[13:14:13.321884][cli][info] Starting player: /usr/bin/vlc
[13:14:13.322923][stream.hls][debug] Reloading playlist
[13:14:13.323106][cli][debug] Pre-buffering 8192 bytes
[13:14:13.511675][stream.hls_playlist][all] #EXT-X-VERSION:3
[13:14:13.511825][stream.hls_playlist][all] #EXT-X-TARGETDURATION:8
[13:14:13.511903][stream.hls_playlist][all] #EXT-X-MEDIA-SEQUENCE:593337
[13:14:13.511969][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.512038][stream.hls_playlist][all] kanald_2023_04_17_11_49_07_593337.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.512150][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.512224][stream.hls_playlist][all] kanald_2023_04_17_11_49_15_593338.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.512323][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.512392][stream.hls_playlist][all] kanald_2023_04_17_11_49_23_593339.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.512481][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.512547][stream.hls_playlist][all] kanald_2023_04_17_11_49_31_593340.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.512635][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.512707][stream.hls_playlist][all] kanald_2023_04_17_11_49_39_593341.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.512816][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.512887][stream.hls_playlist][all] kanald_2023_04_17_11_49_47_593342.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.512978][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.513043][stream.hls_playlist][all] kanald_2023_04_17_11_49_55_593343.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.513133][stream.hls_playlist][all] #EXTINF:8.000000,
[13:14:13.513183][stream.hls_playlist][all] kanald_2023_04_17_11_50_03_593344.ts?live=true&app=com.kanald&min=0&max=1250
[13:14:13.513240][stream.hls_playlist][all] #EXT-X-ENDLIST
[13:14:13.513309][stream.hls][debug] First Sequence: 593337; Last Sequence: 593344
[13:14:13.513355][stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 593337; End Sequence: 593344
[13:14:13.513394][stream.hls][debug] Adding segment 593337 to queue
[13:14:13.513671][stream.hls][debug] Adding segment 593338 to queue
[13:14:13.513793][stream.hls][debug] Adding segment 593339 to queue
[13:14:13.513853][stream.hls][debug] Adding segment 593340 to queue
[13:14:13.513918][stream.hls][debug] Adding segment 593341 to queue
[13:14:13.513999][stream.hls][debug] Adding segment 593342 to queue
[13:14:13.514133][stream.hls][debug] Adding segment 593343 to queue
[13:14:13.514324][stream.hls][debug] Adding segment 593344 to queue
[13:14:13.515244][stream.segmented][debug] Closing worker thread
[13:14:17.113485][stream.hls][debug] Writing segment 593337 to output
[13:14:17.114717][stream.hls][debug] Segment 593337 complete
[13:14:17.114984][cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format https://www.kanald.com.tr/canli-yayin -
[13:14:17.617393][cli][debug] Writing stream to output
[13:14:19.328000][stream.hls][debug] Writing segment 593338 to output
[13:14:19.328587][stream.hls][debug] Segment 593338 complete
[13:14:22.449293][stream.hls][debug] Writing segment 593339 to output
[13:14:22.450269][stream.hls][debug] Segment 593339 complete
[13:14:27.685175][stream.hls][debug] Writing segment 593340 to output
[13:14:27.686156][stream.hls][debug] Segment 593340 complete
[13:14:29.403924][stream.hls][debug] Writing segment 593341 to output
[13:14:29.404655][stream.hls][debug] Segment 593341 complete
[13:14:30.516949][stream.hls][debug] Writing segment 593342 to output
[13:14:30.517549][stream.hls][debug] Segment 593342 complete
[13:14:31.776268][stream.hls][debug] Writing segment 593343 to output
[13:14:31.777112][stream.hls][debug] Segment 593343 complete
[13:14:33.022958][stream.hls][debug] Writing segment 593344 to output
[13:14:33.023646][stream.hls][debug] Segment 593344 complete
[13:14:33.023785][stream.segmented][debug] Closing writer thread
[13:14:33.024727][cli][info] Stream ended
[13:14:33.525547][cli][info] Closing currently open stream...
stulluk ~ $
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Fixes #5297 

The HLS stream URL is read from the `data-url` attribute of the DOM node with the `data-live=true` attribute, so an API query is not needed in this case.

Plugin now finds the correct stream URL on kanald. Other sites are not affected by this change.

```
$ echo -e 'from tests.plugins.test_dogan import TestPluginCanHandleUrlDogan as A\n[print(s) for s in A.should_match]' | python | xargs -n1 -P1 streamlink
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/canli-yayin
Available streams: 410k (worst), 570k, 850k, 1100k, 1400k (best)
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/action/embedvideo/5fa56d065cf3b018a8dd0bbc
Available streams: 300k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/tv-cnn-turk/belgeseller/bir-zamanlar/bir-zamanlar-90lar-belgeseli
Available streams: 300k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.cnnturk.com/video/turkiye/polis-otomobiliyle-tur-atan-sahisla-ilgili-islem-baslatildi-video
Available streams: 300k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.dreamturk.com.tr/canli-yayin-izle
Available streams: 330k (worst), 490k, 780k, 1000k, 1600k (best)
[cli][info] Found matching plugin dogan for URL https://www.dreamturk.com.tr/dream-turk-ozel/radyo-d/ilyas-yalcintas-radyo-dnin-konugu-oldu
Available streams: 300k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.dreamturk.com.tr/programlar/dream-10
Available streams: 750k (worst), 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.dreamtv.com.tr/dream-ozel/konserler/acik-sahne-dream-ozel
Available streams: 300k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.teve2.com.tr/canli-yayin
Available streams: 330k (worst), 490k, 780k, 1000k, 1300k (best)
[cli][info] Found matching plugin dogan for URL https://www.teve2.com.tr/diziler/guncel/oyle-bir-gecer-zaman-ki/bolumler/oyle-bir-gecer-zaman-ki-1-bolum
Available streams: 350k (worst), 750k, 1000k, 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.teve2.com.tr/embed/55f6d5b8402011f264ec7f64
Available streams: 750k (worst), 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.teve2.com.tr/filmler/guncel/yasamak-guzel-sey
Available streams: 750k (worst), 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.teve2.com.tr/programlar/guncel/kelime-oyunu/bolumler/kelime-oyunu-800-bolum-19-12-2020
Available streams: 750k (worst), 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/embed/5fda41a8ebc8302048167df6
Available streams: 750k (worst), 1200k, 1800k, 2800k (best)
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/sadakatsiz/fragmanlar/sadakatsiz-10-bolum-fragmani
Available streams: 750k (worst), 1200k, 1800k, 2800k (best)
```

### CODE REVIEW

**Comment by bastimeyer** [comment]
@stulluk please check. Install from the branch of this PR or side-load the plugin changes

https://streamlink.github.io/install.html#pypi-package-and-source-code
https://streamlink.github.io/cli/plugin-sideloading.html

**Comment by stulluk** [comment]
@bastimeyer  thank you very much. I confirm that it now can display LIVE on KanalD. However, due to my lack of knowledge, I can't find why it can't play the URL via MPV or VLC by using "--stream-url". See below:

```bash
stulluk ~/streamlink $  git clone https://github.com/bastimeyer/streamlink/
Cloning into 'streamlink'...
remote: Enumerating objects: 32604, done.
remote: Counting objects: 100% (375/375), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 32604 (delta 188), reused 312 (delta 153), pack-reused 32229
Receiving objects: 100% (32604/32604), 37.58 MiB | 7.09 MiB/s, done.
Resolving deltas: 100% (21594/21594), done.
stulluk ~/streamlink $  
stulluk ~/streamlink $  cd streamlink/
stulluk ~/streamlink/streamlink (master) $  
stulluk ~/streamlink/streamlink (master) $  git checkout plugins/dogan/find-direct-hls-url 
Branch 'plugins/dogan/find-direct-hls-url' set up to track remote branch 'plugins/dogan/find-direct-hls-url' from 'origin'.
Switched to a new branch 'plugins/dogan/find-direct-hls-url'
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $ 
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  mkdir -p  ~/.local/share/streamlink/plugins
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  cp src/streamlink/plugins/dogan.py ~/.local/share/streamlink/plugins/
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  streamlink https://www.kanald.com.tr/canli-yayin
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
Available streams: 360p (worst), 480p, 720p, 1080p (best)
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  streamlink https://www.kanald.com.tr/canli-yayin 720p
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  streamlink https://www.kanald.com.tr/canli-yayin 720p --stream-url
https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?&sid=5bqmdtbknpjj&app=da2109ea-5dfe-4107-89ab-23593336ed61&ce=3
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  mpv https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?&sid=5bqmdtbknpjj&app=da2109ea-5dfe-4107-89ab-23593336ed61&ce=3
[1] 39332
[2] 39333
[3] 39334
[2]-  Done                    sid=5bqmdtbknpjj
[3]+  Done                    app=da2109ea-5dfe-4107-89ab-23593336ed61
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  [ffmpeg] https: HTTP error 404 Not Found
Failed to open https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?.
[ytdl_hook] ERROR: [generic] None: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 
[ytdl_hook] youtube-dl failed: unexpected error occurred 

Exiting... (Errors when loading file)

[1]+  Exit 2                  mpv https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  vlc https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?&sid=5bqmdtbknpjj&app=da2109ea-5dfe-4107-89ab-23593336ed61&ce=3
[1] 39358
[2] 39359
[3] 39360
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
[2]-  Done                    sid=5bqmdtbknpjj
[3]+  Done                    app=da2109ea-5dfe-4107-89ab-23593336ed61
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  [0000564b00fc8640] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007fde74001680] access stream error: HTTP 404 error
[00007fde74001680] http stream error: local stream 1 error: Cancellation (0x8)
QObject::~QObject: Timers cannot be stopped from another thread

[1]+  Done                    vlc https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?
stulluk ~/streamlink/streamlink (plugins/dogan/find-direct-hls-url) $  
```

Could you please guide me, how can I play direct URL via MPV or VLC ?

**Comment by mkbloke** [comment]
You need to put the streaming URL in single quotes to escape the shell special characters.  E.g.:
```
mpv 'https://demiroren.daioncdn.net/kanald/kanald_720p.m3u8?&sid=5bqmdtbknpjj&app=da2109ea-5dfe-4107-89ab-23593336ed61&ce=3'
```
However, this is often not a good idea because parameters within the URL could change over time and cookies and/or HTTP headers that may be required are not set.  These are all things that are taken care of when streaming via the plugin and then piping the video into the player.

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli/tutorial.html#shell-syntax

**Pull request merged**
