### PR TITLE
0.8.0 release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by gravyboat** [comment]
That looks good to me @cdrage!

**Comment by cdrage** [comment]
@gravyboat Argh. This is a piss-off. I ran into an issue with PyPi and I'm unable to re-upload the correct version, see: https://github.com/pypa/packaging-problems/issues/74 I'm going to have to release a different version number...

Let's skip 0.8.0 and go straight to 0.9.0 (it doesn't really matter TBH).

**Comment by cdrage** [comment]
Error:
```
copying setup.cfg -> streamlink-0.8.0
Writing streamlink-0.8.0/setup.cfg
Creating tar archive
removing 'streamlink-0.8.0' (and everything under it)
running upload
Submitting dist/streamlink-0.8.0.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): This filename has previously been used, you should use a different version.
error: Upload failed (400): This filename has previously been used, you should use a different version.
```

**Comment by gravyboat** [comment]
@cdrage Do you just want to release as 0.8.1?

**Comment by cdrage** [comment]
@gravyboat Or we could do that :+1: Yup. Less confusing.

**Pull request closed without merging**
