### PR TITLE
plugins.twitch: support for different clips URL

### LINKED ISSUE #2533: twitch clips still try to use the v2 api
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Downloading twitch clips does not work. It looks like this is something that was missed when you moved away from the v2 APIs - https://github.com/streamlink/streamlink/issues/1982 etc. - or just something I don't understand.

### Reproduction steps / Explicit stream URLs to test

$ streamlink -o test-clip https://www.twitch.tv/day9tv/clip/AmazonianEnchantingKangarooAsianGlow
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/day9tv/clip/AmazonianEnchantingKangarooAsianGlow
error: Unable to open URL: https://clips.twitch.tv/api/v2/clips/clip/status (404 Client Error: Not Found for url: https://clips.twitch.tv/api/v2/clips/clip/status?as3=t)

### Log output

```
[cli][debug] OS:         Linux-5.0.16-100.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
[cli][debug] Python:     3.6.8
[cli][debug] Streamlink: 1.1.1+34.g0a38762
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/day9tv/clip/AmazonianEnchantingKangarooAsianGlow
error: Unable to open URL: https://clips.twitch.tv/api/v2/clips/clip/status (404 Client Error: Not Found for url: https://clips.twitch.tv/api/v2/clips/clip/status?as3=t)
```

### PR DESCRIPTION
**Pull request by beardypig**
Props to @back-to for noticing the behaviour :)

Fixes #2533

### CODE REVIEW

**Comment by gravyboat** [comment]
Nice catch @back-to and thanks @beardypig.

**Comment by beardypig** [comment]
Ah damn, I was going to add a test to this PR...

**Comment by gravyboat** [comment]
Oh sorry @beardypig. Was just cleaning things up a bit this morning and thought it was ready to go. My bad.

**Comment by beardypig** [comment]
Yeah, I was going to leave a comment - but I drank a beer and forgot :|

**Pull request merged**
