### PR TITLE
plugins.soop: rewrite authentication

### LINKED ISSUE #6320: plugins.soop: Cached credentials not working after logging in with username/password
### Checklist

- [x] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 7.0.0

### Description

Relevant Discussion: _https://github.com/streamlink/streamlink/discussions/6318_

I noticed when viewing SOOP's plugin log that it was constantly attempting (was successful) log in using the username and password specified within my global config. Apparently there is support for caching credentials after being pointed to the [relevant code](https://github.com/streamlink/streamlink/blob/7.0.0/src/streamlink/plugins/soop.py#L280-L287) within the discussion; however, the plugin didn't seem to be using the saved cookies after successfully logging in with the credentials - instead, it kept trying to login over and over again with the username and password.

I would like to assume this isn't intended behavior since there is checks for using previously saved cookies. I guess the problem is `self._authed` is false when the plugin class is initialized. More specifically, this is due to the cookies keys being no longer valid,

```py
  self._authed = (
      self.session.http.cookies.get("PdboxBbs")
      and self.session.http.cookies.get("PdboxSaveTicket")
      and self.session.http.cookies.get("PdboxTicket")
      and self.session.http.cookies.get("PdboxUser")
      and self.session.http.cookies.get("RDB")
  )
```
[Source](https://github.com/streamlink/streamlink/blob/77e5e1fcf7029db8fe0fe88280f7b87f56f9dcec/src/streamlink/plugins/soop.py#L146-L152)

You can confirm this with the debug log of the saved cookies where all the keys **except for `RDB`** are missing from the snippet above. If I had to guess, these are the new cookies:

| Old Key | New Key |
|--------|--------|
| PdboxBbs | BbsTicket |
| PdboxSaveTicket  | _unknown_ |
| PdboxTicket | AuthTicket |
| PdboxUser | UserTicket |
| RDB | RDB | 

Although, it would be appreciated if someone else can test and confirm these new key values.

As of December 3rd 2024:
`[plugins.soop][debug] Saved cookies: RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, UserTicket`
From [February 5th 2021](https://github.com/streamlink/streamlink/issues/3538#issuecomment-774385665):
`[plugins.afreeca][debug] Saved cookies: AbroadChk, AbroadVod, PdboxBbs, PdboxSaveTicket, PdboxTicket, PdboxUser, RDB, _au, _ausa, _ausb, isBbs`

### Debug log

```text
A:\folder>streamlink --no-config --version
streamlink 7.0.0

A:\folder>streamlink --loglevel=debug --output "{author} {id}.ts" --retry-streams 3 --retry-max 0 --hls-live-restart https://play.sooplive.co.kr/cooksuxtv best
[session][debug] Loading plugin: soop
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.0.15 3 Sep 2024
[cli][debug] Streamlink: 7.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.sooplive.co.kr/cooksuxtv
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
[cli][debug]  --output={author} {id}.ts
[cli][debug]  --retry-streams=3.0
[cli][debug]  --retry-max=0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --soop-username=********
[cli][debug]  --soop-password=********
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth <redacted>')]
[plugins.soop][debug] Restored cookies: RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, UserTicket
[cli][info] Found matching plugin soop for URL https://play.sooplive.co.kr/cooksuxtv
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, UserTicket
[plugins.soop][info] Login was successful
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, UserTicket
[plugins.soop][info] Login was successful
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, UserTicket
[plugins.soop][info] Login was successful
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, UserTicket
[plugins.soop][info] Login was successful
Interrupted! Exiting...
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Resolves #6320 

@Infinitay please give this PR a quick test and report back with the results. This site requires a phone number when trying to register a new account, so I'm not able to test this myself as I'm surely not going to give them any of my personal data. Please also try purging the stored credentials, logging back in, and checking the stored auth credentials again. Thank you.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback

----

Instead of checking a list of specific/hardcoded cookies, this PR rewrites the auth logic by checking whether any cookies are available on the HTTP session (restored from the plugin cache) for the `.sooplive.co.kr` domain, and if that's the case, then it attempts to verify the cookies on `GET https://afevent2.sooplive.co.kr/api/get_private_info.php`, which apparently is what their website uses as API endpoint. If the JSON response includes an empty `LOGIN_ID` field, then the user is not authenticated. The endpoint apparently seems to always return status 200, but I'm not fully sure.

### CODE REVIEW

**Comment by Infinitay** [comment]
Thanks for working on this. I'm facing an issue:

```txt
(sl-6321) A:\folder>streamlink --loglevel=debug --output "{author} {id}.ts" --retry-streams 3 --retry-max 0 --hls-live-restart https://play.sooplive.co.kr/cooksuxtv best
[session][debug] Loading plugin: soop
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.0.15 3 Sep 2024
[cli][debug] Streamlink: 7.0.0+25.gc4f58582
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.sooplive.co.kr/cooksuxtv
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
[cli][debug]  --output={author} {id}.ts
[cli][debug]  --retry-streams=3.0
[cli][debug]  --retry-max=0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --ffmpeg-ffmpeg=C:\ProgramData\chocolatey\bin\ffmpeg.exe
[cli][debug]  --soop-username=********
[cli][debug]  --soop-password=********
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth <redacted>')]
[plugins.soop][debug] Restored cookies: AbroadVod, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, UserTicket, RDB, isBbs
[cli][info] Found matching plugin soop for URL https://play.sooplive.co.kr/cooksuxtv
[cli][error] Unable to validate response text: ValidationError(dict):
  Key 'LOGIN_ID' not found in <{'CHANNEL': {'IS_LOGIN': 1, 'LOGIN_ID': '<redacted_username>',...>
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[cli][error] Unable to validate response text: ValidationError(dict):
  Key 'LOGIN_ID' not found in <{'CHANNEL': {'IS_LOGIN': 1, 'LOGIN_ID': '<redacted_username>',...>
[cli][error] Unable to validate response text: ValidationError(dict):
  Key 'LOGIN_ID' not found in <{'CHANNEL': {'IS_LOGIN': 1, 'LOGIN_ID': '<redacted_username>',...>
Interrupted! Exiting...
```

Guess it's because of [this line](https://github.com/streamlink/streamlink/pull/6321/files#diff-7752c883ef56aafd2478313b9f42a779469bd8a31b62c3f72d4bd9f39b290718R236) and how `LOGIN_ID` is the _inner property_ of the `CHANNEL` object.

**Comment by Infinitay** [comment]
```txt
[plugins.soop][debug] Restored cookies: AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, UserTicket, RDB, isBbs, AbroadVod, _ausa, _ausb
[cli][info] Found matching plugin soop for URL https://play.sooplive.co.kr/cooksuxtv
[plugins.soop][debug] Authentication using stored credentials was successful
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[plugins.soop][debug] Authentication using stored credentials was successful
[plugins.soop][debug] Authentication using stored credentials was successful
[plugins.soop][debug] Authentication using stored credentials was successful
[plugins.soop][debug] Authentication using stored credentials was successful
Interrupted! Exiting...
```

LGTM Thank you

**Comment by bastimeyer** [comment]
> Please also try purging the stored credentials, logging back in, and checking the stored auth credentials again. Thank you.

**Comment by Infinitay** [comment]
> > Please also try purging the stored credentials, logging back in, and checking the stored auth credentials again. Thank you.

Sorry I completely skipped over that part. My mistake.

```txt
(sl-6321) A:\folder>streamlink --loglevel=debug --output "{author} {id}.ts" --retry-streams 3 --retry-max 0 --hls-live-restart --soop-purge-credentials https://play.sooplive.co.kr/cooksuxtv best
[session][debug] Loading plugin: soop
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.0.15 3 Sep 2024
[cli][debug] Streamlink: 7.0.0+25.g5b241da9
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.sooplive.co.kr/cooksuxtv
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
[cli][debug]  --output={author} {id}.ts
[cli][debug]  --retry-streams=3.0
[cli][debug]  --retry-max=0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --ffmpeg-ffmpeg=C:\ProgramData\chocolatey\bin\ffmpeg.exe
[cli][debug]  --soop-username=********
[cli][debug]  --soop-password=********
[cli][debug]  --soop-purge-credentials=True
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth <redacted>')]
[plugins.soop][debug] Restored cookies: UserTicket, RDB, isBbs, _ausa, _ausb, AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod
[cli][info] Found matching plugin soop for URL https://play.sooplive.co.kr/cooksuxtv
[plugins.soop][info] All credentials were successfully removed
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: AbroadChk, AbroadVod, _au, _au3rd, _ausa, _ausb, AuthTicket, BbsTicket, UserTicket, isBbs, RDB, BbsSaveTicket
[plugins.soop][info] Login was successful
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[plugins.soop][info] All credentials were successfully removed
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: AbroadChk, AbroadVod, _au, _au3rd, _ausa, _ausb, AuthTicket, BbsTicket, UserTicket, isBbs, RDB, BbsSaveTicket
[plugins.soop][info] Login was successful
[plugins.soop][info] All credentials were successfully removed
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: AbroadChk, AbroadVod, _au, _au3rd, _ausa, _ausb, AuthTicket, BbsTicket, UserTicket, isBbs, RDB, BbsSaveTicket
[plugins.soop][info] Login was successful
Interrupted! Exiting...
```

Seems to be working fine. It's up to you on how you want to implement the credentials purging while waiting for a stream - whether you want to to keeping purging the credentials as it's doing currently or not. Although, I expected passing in `--soop-purge-credentials` to work alone without a URL given this behavior, but that wasn't the case.

<details><summary>Just Purge</summary>
<p>

```txt
(sl-6321) A:\>streamlink --loglevel=debug --output "{author} {id}.ts" --retry-streams 3 --retry-max 0 --hls-live-restart --soop-purge-credentials
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.0.15 3 Sep 2024
[cli][debug] Streamlink: 7.0.0+25.g5b241da9
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
[cli][debug]  --output={author} {id}.ts
[cli][debug]  --retry-streams=3.0
[cli][debug]  --retry-max=0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --ffmpeg-ffmpeg=C:\ProgramData\chocolatey\bin\ffmpeg.exe
[cli][debug]  --soop-username=********
[cli][debug]  --soop-password=********
[cli][debug]  --soop-purge-credentials=True
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth <redacted>')]
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io/
```

</p>
</details> 

To add on to what I was saying, I assumed that since the combination of `--soop-purge-credentials --retry-max 0` will always purge credentials on each retry, that `--soop-purge-credentials` without a specified URL would work as is. Although, I guess this isn't expected behavior and would rather be better suited as a feature request.

**Comment by bastimeyer** [comment]
> credentials purging while waiting for a stream

This is a one-time operation which doesn't make sense when retrying streams. I've moved it to the plugin constructor now, so that it's actually only run once. You can give this update a try if you want, otherwise I'm going to merge later. Thanks.

> that `--soop-purge-credentials` without a specified URL would work as is

No, a plugin first has to be matched/resolved in order for any plugin-arguments to be relevant. Without an input URL, no plugins are resolved and initialized.

**Comment by Infinitay** [comment]
Went ahead and tested it before I removed my conda env and it worked fine. Thanks again for your time and effort on this issue.

```txt
(sl-6321) A:\folder>streamlink --loglevel=debug --output "{author} {id}.ts" --retry-streams 3 --retry-max 0 --hls-live-restart --soop-purge-credentials https://play.sooplive.co.kr/cooksuxtv best
[session][debug] Loading plugin: soop
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.0.15 3 Sep 2024
[cli][debug] Streamlink: 7.0.0+25.g7dc98cc3
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.sooplive.co.kr/cooksuxtv
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
[cli][debug]  --output={author} {id}.ts
[cli][debug]  --retry-streams=3.0
[cli][debug]  --retry-max=0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --ffmpeg-ffmpeg=C:\ProgramData\chocolatey\bin\ffmpeg.exe
[cli][debug]  --soop-username=********
[cli][debug]  --soop-password=********
[cli][debug]  --soop-purge-credentials=True
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth <redacted>')]
[plugins.soop][debug] Restored cookies: AbroadChk, _au, _au3rd, AuthTicket, BbsTicket, AbroadVod, RDB, isBbs, _ausa, _ausb
[plugins.soop][info] All credentials were successfully removed
[cli][info] Found matching plugin soop for URL https://play.sooplive.co.kr/cooksuxtv
[plugins.soop][debug] Attempting to login using username and password
[plugins.soop][debug] Saved cookies: AbroadChk, AbroadVod, _au, _au3rd, _ausa, _ausb, AuthTicket, BbsTicket, UserTicket, isBbs, RDB, BbsSaveTicket
[plugins.soop][info] Login was successful
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[plugins.soop][debug] Authentication using stored credentials was successful
[plugins.soop][debug] Authentication using stored credentials was successful
[plugins.soop][debug] Authentication using stored credentials was successful
Interrupted! Exiting...
```

**Pull request merged**
