### PR TITLE
plugins.mjunoon: rewrite/fix

### PR DESCRIPTION
**Pull request by mkbloke**
This was broken, as mentioned in: https://github.com/streamlink/streamlink/pull/1857#issuecomment-777771116

### CODE REVIEW

**Comment by mkbloke** [comment]
I might update this in the near future to see if it works with the cricket matches on `/psl` if I can remember to keep checking for them to air...

**Comment by worldmediaman** [comment]
can anyone merged it?

**Comment by gravyboat** [comment]
@worldmediaman When someone has time to review it they will. If you want the commit manually merge it to your own fork. Please stop spamming with so many issues and comments.

**Comment by mkbloke** [comment]
The live cricket is on `/psl-live`.  It works, but it's geo-restricted, so I've updated the plugin matrix too.  All the other content I've tested with so far does not seem to be geo-restricted.

**Pull request merged**
