### PR TITLE
release: fix release notes manual install url

### PR DESCRIPTION
**Pull request by beardypig**
As reported by @cdrage https://github.com/streamlink/streamlink/pull/1855#issuecomment-400693776. 

Tested with `--dry-run`.

### CODE REVIEW

**Comment by bastimeyer** [comment]
Suggesting to do `sudo pip install streamlink` is probably also not the wisest idea...

**Comment by beardypig** [comment]
The best option is to use a `virtualenv`, but that's too long winded to explain ;) Second is `--user` install, but that requires modifying your `$PATH`. 

I think it might be better to remove that section and to just refer to the [installation documentation](https://streamlink.github.io/install.html#source-code).

**Comment by cdrage** [comment]
This LGTM :+1: Thanks for the quick fix!

**Comment by gravyboat** [comment]
I'm going to merge this just to get it in. We can still discuss the installation documentation.

**Comment by beardypig** [comment]
@cdrage are you able to do a quick 0.14.1 release? Although a plugin has been removed now...

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/releases/edit/0.14.0

you can just edit the URL ? why would you need a new release

**Comment by beardypig** [comment]
That too, but to make sure it works and test the bot user and new release key. (I’m looking for an excuse to test that out)

**Comment by gravyboat** [comment]
Agreed @bastimeyer. There are too many systems that depend on a release being an actual bump, some of which we may not know about so I'd rather just bump it.

**Comment by beardypig** [comment]
@gravyboat want to do a 0.14.1 release? I have prepped this: https://github.com/beardypig/streamlink/tree/release-0.14.1

**Comment by cdrage** [comment]
@beardypig Do you or @gravyboat want to try it? I'd like to give someone else the chance to do it haha

**Comment by gravyboat** [comment]
Whoops sorry @beardypig, wasn't around in the afternoon/evening yesterday.

**Pull request merged**
