### PR TITLE
installer: drop Windows installer build config

### LINKED ISSUE #4390: installer: move to separate repo, build multiple Python versions and archs
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I'm thinking about moving Streamlink's Windows installer to a different repo, similar to the Linux Appimages. Let's discuss this.

----

The installer has been built here in this repo ever since the Livestreamer fork, because Livestreamer's installer was built in its own repo as well (using different libs), and it was the easiest solution of quickly implementing it. Since Streamlink already included Windows RTMPdump binaries on the master branch (via Livestreamer) and no external streamlink-assets repo existed, the very unfortunate mistake was made of merging a ~54MiB FFmpeg binary into the master branch, so it could be included in the installer. I wish I would've seen the PR in time to prevent this, but that can't be changed anymore, and the file will be included in the repo forever. In order to clean it all up a bit and prevent future mistakes like this, we've added the streamlink-assets repo where those 3rd party binaries could be hosted and included when building the installer. Recently we've dropped RTMPdump and switched to self-built FFmpeg binaries, so the streamlink-assets repo became obsolete. As a consequence of the old build-simplifications, Streamlink's Windows installer was always limited to x86-only.

Streamlink's installer is built via pynsist, and it downloads pre-built "embeddable" binaries for Python which are pulled from python.org. The big issue with that is that Python versions which have entered the "security" maintenance cycle don't get published as binaries anymore by the Python devs and are only distributed as source files, which means Python 3.8, the last version that still supports Windows 7, can't be included here via pynsist unless we're using old Python releases and sacrifice the security and performance for everyone else. This has been causing lots of confusion for W7 users when they need to install Python 3.8 on their own, and Streamlink via pip in this extra python environment. Some users have also gotten a bit frustrated when we announced the switch to Python 3.9 and the end of support for W7 via Streamlink's installer in the 2.4.0 release. In addition to all of that, the chocolatey and win-get packages are based on the installer, which they simply extract the files from, so the limitation also applies here. For W7 users of Streamlink Twitch GUI who obviously also need to install Streamlink, this has already caused lots of headaches, because most of them are more "casual users" and don't know how command line shells work.

We haven't switched to Python 3.10 yet, as 3.9 is still in its "bugfix" cycle, so it still has binary releases on python.org. We'll have to upgrade soon though, as the final bugfix release of 3.9 will be 3.9.12, which will be in May this year. This won't cause any compatibility issues though.

----

Now to the reason why I want to discuss switching the build- and release-config of Streamlink's Windows installer. As said, there are some unnecessary limitations which are quite simple to resolve if we change how we build and deploy the installer.

CPython 3.8 is still maintained, so it can safely be built and included in the installer, similar to what we're already doing with FFmpeg, and so are x86_64 binaries. I have already [created a test repo for building multiple CPython releases](https://github.com/bastimeyer/python-windows-embed) (3.8 and 3.10) via GitHub actions, for both x86 and x86_64. The resulting file structure differs a bit and the binaries are obviously not signed by the Python devs, but that shouldn't be a problem. One issue I had was building 3rd party libs from source too. Since I haven't managed to fix the build errors with libffi, I did what the official releases are doing as well and included pre-built 3rd party libs (Tcl/Tk, OpenSSL and libffi) which are hosted in a repo on python's GitHub orga. This is all part of the regular CPython build process on Windows.

I haven't built an installer with these custom CPython releases yet, but I will do that over the next couple of days and see if there are any issues. Building x86_64 binaries for FFmpeg is just one small switch (plus a rebase to the latest version - 5.0).

So what I'd like to do is building four or maybe only three installers, x86 + x86_64 with Python 3.10, and x86 + optionally x86_64 with Python 3.8, in a custom repo. That would mean that the installers would not be deployed via GitHub releases here in this repo. Nightly builds would also be hosted there. These can be limited to only one flavor, though.

One benefit of moving the installer is that we can publish releases with upgraded dependencies, as those are pinpointed, without having to create a new Streamlink release. One recent example is the charset-normalizer dependency of python-requests, which caused issues when parsing HLS playlists without content-type HTTP headers. The AppImages could be upgraded immediately after the charset-normalizer fix, whereas the installer could not.

The only issues I see with this is the extra work and maintenance (not a big issue), potential problems with the included CPython builds, and the move to a different repo which will probably confuse users and will require chocolatey and win-get maintainers to update.

Thoughts?

### PR DESCRIPTION
**Pull request by bastimeyer**
Drop installer build config in favor of the external build config at:
https://github.com/streamlink/windows-installer

- remove installer build scripts+configs
- remove Streamlink config file in win32 subdirectory
- remove windows-installer CI job
  - update steps of the release CI job
- remove removed-plugins file
  - remove src/streamlink/plugins/.removed
  - update package manifest
  - update tests
  - update developing docs
- rewrite install docs

----

Resolves #4390 

Merging this will break @scowalt's chocolatey package (due to the new download location) and @beardypig's portable builds (due to the removed config file).

Now the important question, do we already want to remove the build config, or should we wait and do it after the next release? As you can see, I've published the `3.2.0-1` installer release, but we could keep both versions, the one here and the installers at the other repo, for a short while:
https://github.com/streamlink/windows-installer/releases/tag/3.2.0-1

This `3.2.0-1` installer release doesn't mean though that I'm 100% confident with it. I've only tested it in my W10 VM and didn't touch anything W7 related. The custom Python embedded builds are all working, but they are different from the official ones, as mentioned [here](https://github.com/streamlink/streamlink/issues/4390#issuecomment-1073001230), so there's lots of potential for unknown issues. And on top of that, the FFmpeg builds are new, the removed plugins file got replaced with a `RMDir /r "$INSTDIR\pkgs"` command before unpacking/copying files in the installer, and the default install path got changed in the x86_64 installers.

The reviews I've got so far were quick "It's working for me" comments, without any code / build setup reviews. Since I don't want to cause any issues for Windows users in the next release with the switch of the build config, I would really appreciate if one could at least take a deeper look and preferably build it themselves once. Also please see if something's unclear in the installer repo's readme and the docs changes here.

Btw, even though we're not building the nightly installer anymore, I've kept the scheduled CI runs, so that dependency release issues can be caught.

### CODE REVIEW

**Comment by bastimeyer** [comment]
https://deploy-preview-4405--streamlink.netlify.app/install.html

**Comment by gravyboat** [comment]
> Now the important question, do we already want to remove the build config, or should we wait and do it after the next release? As you can see, I've published the 3.2.0-1 installer release, but we could keep both versions, the one here and the installers at the other repo, for a short while:

Let's see if anyone else you've tagged weighs in, but my vote is to leave it for one more release with a deprecation note then drop it.

> I've only tested it in my W10 VM and didn't touch anything W7 related. 

I've been using it on Windows 10 since you released it without issue. W7 is not our concern, it's EoL software. If it breaks for someone that's their problem for running an outdated OS. We're not taking on the maintenance burden for an operating system the the creators no longer support.

In terms of other bugs we can add a release note requesting people try the new installer potentially? I'm not sure how many users will do that though.

> Since I don't want to cause any issues for Windows users in the next release with the switch of the build config, I would really appreciate if one could at least take a deeper look and preferably build it themselves once. Also please see if something's unclear in the installer repo's readme and the docs changes here.

I will try to make time for this.

**Comment by bastimeyer** [comment]
A bit sad that there hasn't been a review yet... I'd really like to see this resolved, especially since the current stable release does include an older Python build with a vulnerable OpenSSL version, whereas the ones on streamlink/windows-installer do not. There has been a Python 3.10.4 release already, but this is just a minor bugfix for building on RHEL and is thus irrelevant for the Windows installer builds.

The "Windows installer" CI job is currently set as a requirement for merging, so this will have to be updated first. The rest should be fine now. I forgot to remove one job dependency in my initial push and it didn't trigger a CI run because of that. I thought that this was caused by the GH actions outage at this time, but I was wrong (hence my first force-push without any code changes).

**Once again, I'd kindly ask anyone of you to give this a thorough review whenever you have the time.**

Remember that this will remove the removed-plugins file, so any other PRs with plugin removals will cause merge conflicts as long as this PR here hasn't been merged yet.

**Comment by gravyboat** [comment]
@bastimeyer I didn't have a chance to build the installer this weekend, planning on doing it tonight. After that I will mark as approved.

**Review by gravyboat — APPROVED** [review]
@bastimeyer Alright I went through this tonight and it built fine on a linux VM that I spun up. I tried building it on a Mac as well to try and build on some real hardware but it was too big of a pain in the ass to get everything linked up so I gave up. It might be worth updating the docs to note you can run https://github.com/streamlink/windows-installer/blob/master/install-build-dependencies.sh manually if needed.

**Comment by bastimeyer** [comment]
> It might be worth updating the docs to note you can run [https://github.com/streamlink/windows-installer/blob/master/install-build-dependencies.sh](https://github.com/streamlink/windows-installer/blob/master/install-build-dependencies.sh?rgh-link-date=2022-03-29T03%3A48%3A28Z) manually if needed.

It's meant for the CI, because it installs packages via apt, hence why it checks for the `CI` env var. I didn't put it into `/.github`, because it also installs pip dependencies, so people who want to build it themselves can see it deps. They should probably be put into a requirements file or pipenv lockfile though.

> I tried building it on a Mac as well to try and build on some real hardware but it was too big of a pain in the ass to get everything linked up so I gave up.

All the build dependencies are on homebew:

- https://formulae.brew.sh/formula/makensis#default
- https://formulae.brew.sh/formula/gawk#default
- https://formulae.brew.sh/formula/jq#default
- https://formulae.brew.sh/formula/imagemagick#default
- https://formulae.brew.sh/cask/inkscape#default

**Comment by gravyboat** [comment]
> All the build dependencies are on homebew

I know. Setting up the proper version of Python and getting it linked up properly (pip, virtualenv, etc.) was the worst part. I don't care much about building it on mac any way. I just tried that first since I didn't want to spin up a linux VM. This can be merged if you're ready. Doesn't seem like anyone else is going to weigh in.

**Comment by gravyboat** [comment]
@bastimeyer I don't think anyone else is going to look at this. What's left blocking this from a merge if the check is rerun?

**Comment by bastimeyer** [comment]
There's nothing left. Merging this will break @scowalt's chocolatey package and @beardypig's portable build, for the reasons mentioned above.

I was hoping for a review from at least @back-to, but there hasn't been any activity in the past days. I'm also not sure if you've reviewed the docs changes here, because of your previous comments.

Also, as said, I would appreicate if the streamlink/windows-installer repo could be added to your (plural) watch list, so I don't have to respond to issues on this repo there alone.

**Comment by gravyboat** [comment]
> I'm also not sure if you've reviewed the docs changes here, because of your previous comments.

Are you talking about the install.rst doc changes? I already looked at those. They're pretty minimal and seem fine, I wouldn't have approved if I hadn't looked at them.

> Also, as said, I would appreicate if the streamlink/windows-installer repo could be added to your (plural) watch list, so I don't have to respond to issues on this repo there alone.

Done.

**Review by back-to — APPROVED** [review]

**Comment by bastimeyer** [comment]
I've updated the branch protection rules of the master branch and removed the "Windows installer" requirement. It now also requires passing tests for py310 instead of py39.

Going to merge now...

**Pull request merged**
