### PR TITLE
plugins.pandatv: use Pandatv API v3

### PR DESCRIPTION
**Pull request by steven7851**
Old API still work in most channels,
but some channels which have a lot of viewers need new API to get the verified stream URL.
I think it will apply to all channels soon.

### CODE REVIEW

**Comment by Erk-** [comment]
Maybe you should use the v2 api, then you don't need to download the whole page to get the room_key.

**Comment by beardypig** [comment]
It would probably be better not to call `http.get` multiple time for the same page, you might make more requests than necessary.

**Comment by prech** [comment]
I'm afraid I'm not familiar with the v2 or v3 APIs, but may I ask if the Pandatv plugin is working? I'm using the latest 0.2.0 Streamlink release

Every Pandatv stream gives me this error:
> streamlink http://www.panda.tv/415164
[cli][info] Found matching plugin pandatv for URL http://www.panda.tv/415164
error: No streams found on this URL: http://www.panda.tv/415164

Some streams for testing:
[http://www.panda.tv/cate/lol](http://www.panda.tv/cate/lol)

Thank you!

**Comment by xkbd** [comment]
@prech i'm tried open http://www.panda.tv/415164 and it works.
Try to install latest nightly build: https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe

**Comment by prech** [comment]
@xkbd Thanks for checking it on your side.

Very odd, I've tried the nightly release, containing the pandatv.py file updated ~3 days ago (Jan 13), and unfortunately every stream I attempt is showing the same "No streams found" error...

I've tried Streamlink for several other streams (M3U8s, Afreeca, Youtube) and all are fine... I use MPC and my streamlinkrc file is basically otherwise blank/commented out.

Some other Pandatv streams I've tested:
http://www.panda.tv/60995
http://www.panda.tv/507538
http://www.panda.tv/507540

All show
>[cli][info] Found matching plugin pandatv for URL http://www.panda.tv/60995
error: No streams found on this URL: http://www.panda.tv/60995

**Comment by steven7851** [comment]
Old API still work in in most channels, 
but some channels which have a lot of viewers need new API to get verified stream URL.
I think it will apply to all channels soon.

**Comment by fozzysec** [comment]
The new code does not work with some room like [http://www.panda.tv/lpl](http://www.panda.tv/lpl), in the old version from page source get the room id then `streamlink www.panda.tv/<room id>` works. But these room seems not have `room_key`.

**Comment by Erk-** [comment]
@fozzysec the correct url to use is http://www.panda.tv/7000 whih is the room id. nut it need to be able figure that out.

**Comment by steven7851** [comment]
Event pages still use v2 API ...

**Comment by gravyboat** [comment]
Thanks for the recent changes @steven7851! Things look good to me so I'm going to merge. If people want to propose other enhancements they can do so. Thanks for your input everyone.

**Pull request merged**
