### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by bastimeyer**
If there are PRs which should be merged before the release, please tell.

### CODE REVIEW

**Comment by mkbloke** [comment]
I don't know if it's fair to say they *should be* in this release, but there are a couple of plugin fix PRs of mine that are currently outstanding which, from a user perspective might be nice to include in the release.  There could be perfectly good reasons why these PRs have yet to be merged of course.

- #3116 has been around for quite some time now and seems to be in a state of limbo
- #3155 has been sitting for 2 weeks now with review requested changes having been made

I realise both of these plugins present their own issues with regard to independent testing, but I'm not sure what else can be done in that regard.

It's not important to my usage of streamlink that these fixes are available in this release, but perhaps for users it would be nice?

**Comment by bastimeyer** [comment]
Fair points. It's no problem discussing this here.

> #3155

I have reviewed it, but since it's a geo-blocked site, I can't fully validate it. Also the mux-subtitles parameter story, but that's a different issue. I guess we can merge this.

> #3116

Requires an account and can't test it either. There have been some last minute changes though. If you feel confident enough, then this could be merged too, considering that it's been tested by other users as well.

**Comment by mkbloke** [comment]
> > #3155
> 
> I have reviewed it, but since it's a geo-blocked site, I can't fully validate it. Also the mux-subtitles parameter story, but that's a different issue. I guess we can merge this.

Yes, the ```mux-subtitles``` issue is something that can be dealt with at a later date.  If a decision is made on it, I'm happy to submit a PR fixing all the plugins currently using a local parameter which will update them to use a global one instead.

> > #3116
> 
> Requires an account and can't test it either. There have been some last minute changes though. If you feel confident enough, then this could be merged too, considering that it's been tested by other users as well.

I very recently pushed some insignificant changes that don't affect the overall logic or operation too much at all.  I removed the unnecessary ```re.VERBOSE``` in ```url_re``` and modified the cookies to expire with ```time_now + 1 year```.  I'm as confident about it as I can be, given that although I have an account, I do not have a subscription package, so I cannot test as fully as would be preferable either.

Cheers.

**Comment by gravyboat** [comment]
We should get https://github.com/streamlink/streamlink/pull/3139 in as well. I don't think the other ones are ready to go, and many are waiting for the python2 retirement.

**Comment by bastimeyer** [comment]
After #3194 has been merged, I will update the changelog, so we can continue here.

**Comment by bastimeyer** [comment]
Updated the changelog. Anything else, @gravyboat? Is the checklist okay as it is or should it be changed? I find this a better way to describe changes than writing blocks of text. Do you want linked PRs / issues in there?

**Comment by gravyboat** [comment]
@bastimeyer I think we're good. Checklist looks good and I prefer it as well. I do think we should link the PRs/issues just for ease of reference.

**Comment by bastimeyer** [comment]
Let me quickly add the links, after that I'll be offline. If you want to merge it afterwards, don't forget to tag the new release.

**Comment by bastimeyer** [comment]
Double checked the list and fixed / added some stuff. Should be good now.

**Comment by gravyboat** [comment]
@bastimeyer Okay merged.

**Comment by mkbloke** [comment]
Tagged?

**Pull request merged**
