### PR TITLE
fix livestream thanks to @intact

### LINKED ISSUE #182: Plugin for Livestream.com not working right?  exit's quickly for hls and not at all for normal streams
I am trying to get a live stream on livestreamer.com to work and i can't get it to play more then about 35 seconds...

When I run this command:
streamlink "http://livestream.com/Miraclenet/events/5004281" 270p --fifo --player omxplayer

it gives me an error about an swf being needed.  When I run this command:
streamlink "http://livestream.com/Miraclenet/events/5004281" 270p_hls --fifo --player omxplayer

it will play the stream but just for about 35 seconds or so...  I kinda don't want to have to restart it every 35 seconds to watch this stream...  I'd like it to run until I stop it myself...

Any help for this non-python, non-linux guy would be very helpful...

btw, this is running on a Raspberry Pi.  Just got a nice little 7 inch lcd for it and set it up on my desk to be able to watch it while I work, but can't get it to play for long at a time...

(edited to correct commands used)

### PR DESCRIPTION
**Pull request by Brainzyy**
Just need @intact 's blessing

fixes #182

### CODE REVIEW

**Comment by beardypig** [comment]
For future reference you can set the author of a commit by doing `git commit --author "name <email>"` :-)

**Comment by Brainzyy** [comment]
@beardypig Thanks for the info, but I'm a noob when it comes to command line git. I just commited this with github web.

**Comment by gravyboat** [comment]
Are we good to merge this in? Any concerns past what @intact brought up? I would rather have it work most of the time than die all of the time.

**Comment by beardypig** [comment]
As @intact pointed out, this reverts a previous fix for the naming of stream qualities in py2 vs. py3 (#96).

**Comment by beardypig** [comment]
I created a separate PR with the commit from @intact which doesn't squash the previous fix in #96.

**Comment by Brainzyy** [comment]
Thank you @beardypig, I'll close this now, sorry for my failure.

**Comment by beardypig** [comment]
Hardly a failure :) Easy to miss :D

**Pull request closed without merging**
