### PR TITLE
plugins.pluto: new plugin for https://pluto.tv/

### PR DESCRIPTION
**Pull request by back-to**
https://pluto.tv/live-tv/

- Livestreams will break during commercials without the `self.session.set_option('ffmpeg-fout', 'mpegts')` option enabled.
- VODs might work without it, but I did not test it.

closes https://github.com/streamlink/streamlink/issues/854
closes https://github.com/streamlink/streamlink/pull/2747
closes https://github.com/streamlink/streamlink/issues/3156

Co-authored-by: calculon-jr <54852718+calculon-jr@users.noreply.github.com>

### CODE REVIEW

**Review by bastimeyer — COMMENTED** [review]
Just some minor code suggestions. Tested all three URL types and they seem to work well.

**Comment by WayoshiM** [comment]
When trying to run streamlink with a live-tv link, regardless of the channel (slug_live) given it defaults to newsy (this incidentally has no stitched and fails, but regardless the main issue is it seems the given slug is not being processed properly somewhere).

```
streamlink https://pluto.tv/live-tv/pluto-tv-007
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/pluto-tv-007
error: Unable to validate JSON: Key 'stitched' not found in {'_id': '5459795fc9f133a519bc0bef', 'slug': 'newsy', 'name': 'Top Stories by Newsy', 'hash': '#Newsy', 'number': 232, 'summary': 'Be informed — not influenced — with Newsy’s opinion-free approach to news. For people who aren’t satisfied with only the loudest part of the story, Newsy 
Top Stories delivers honest, in-depth context on stories that matter.', 'visibility': 'everyone', 'onDemandDescription': '', 'category': 'News + Opinion', 'plutoOfficeOnly': False, 'directOnly': True, 'chatRoomId': -1, 'onDemand': False, 'cohortMask': 1023, 'featuredImage': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/featuredImage.jpg?w=1600&h=900&fm=jpg&q=75&fit=fill&fill=blur'}, 'thumbnail': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/thumbnail.jpg?w=660&h=660&fm=jpg&q=75&fit=fill&fill=blur'}, 'tile': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/tile.jpg'}, 'logo': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/logo.png?w=280&h=80&fm=png&fit=fill'}, 'colorLogoSVG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/colorLogoSVG.svg'}, 'colorLogoPNG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/colorLogoPNG.png'}, 'solidLogoSVG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/solidLogoSVG.svg'}, 'solidLogoPNG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/solidLogoPNG.png'}, 'featured': False, 'featuredOrder': 
-1, 'favorite': False, 'isStitched': False, 'tmsid': '115371'}
```

**Comment by gravyboat** [comment]
@WayoshiM run with `-l debug` so we can see some debug output. Did you update the plugin manually from the master branch or use the nightly build version of Streamlink?

**Comment by WayoshiM** [comment]
> @WayoshiM run with `-l debug` so we can see some debug output. Did you update the plugin manually from the master branch or use the nightly build version of Streamlink?

I installed with pip with the latest .git version.

````streamlink https://pluto.tv/live-tv/pluto-tv-007 -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.7.0+92.gfd1affa
[cli][debug] Requests(2.25.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/pluto-tv-007
error: Unable to validate JSON: Key 'stitched' not found in {'_id': '5459795fc9f133a519bc0bef', 'slug': 'newsy', 'name': 'Top Stories by Newsy', 'hash': '#Newsy', 'number': 232, 'summary': 'Be informed — not influenced — with Newsy’s opinion-free approach to news. For people who aren’t satisfied with only the loudest part of the story, Newsy Top Stories delivers honest, in-depth context on stories that matter.', 'visibility': 'everyone', 'onDemandDescription': '', 'category': 'News + Opinion', 'plutoOfficeOnly': False, 'directOnly': True, 'chatRoomId': -1, 'onDemand': False, 'cohortMask': 1023, 'featuredImage': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/featuredImage.jpg?w=1600&h=900&fm=jpg&q=75&fit=fill&fill=blur'}, 'thumbnail': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/thumbnail.jpg?w=660&h=660&fm=jpg&q=75&fit=fill&fill=blur'}, 'tile': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/tile.jpg'}, 'logo': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/logo.png?w=280&h=80&fm=png&fit=fill'}, 'colorLogoSVG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/colorLogoSVG.svg'}, 'colorLogoPNG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/colorLogoPNG.png'}, 'solidLogoSVG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/solidLogoSVG.svg'}, 'solidLogoPNG': {'path': 'https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/solidLogoPNG.png'}, 'featured': False, 'featuredOrder': -1, 'favorite': False, 'isStitched': False, 'tmsid': '115371'}```

I think the issue might be that `stitched` is in fact an optional part of this JSON. Maybe use 'isStitched' == True as the filter

**Comment by emveepee** [comment]
Correct newsy doesn't have stitched.  so isStitched is false

```
    {
        "_id": "5459795fc9f133a519bc0bef",
        "slug": "newsy",
        "name": "Top Stories by Newsy",
        "hash": "#Newsy",
        "number": 232,
        "summary": "Be informed � not influenced � with Newsy�s opinion-free approach to news. For people who aren�t satisfied with only the loudest part of the story, Newsy Top Stories delivers honest, in-depth context on stories that matter.",
        "visibility": "everyone",
        "onDemandDescription": "",
        "category": "News + Opinion",
        "plutoOfficeOnly": false,
        "directOnly": true,
        "chatRoomId": -1,
        "onDemand": false,
        "cohortMask": 1023,
        "featuredImage": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/featuredImage.jpg?w=1600\u0026h=900\u0026fm=jpg\u0026q=75\u0026fit=fill\u0026fill=blur"
        },
        "thumbnail": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/thumbnail.jpg?w=660\u0026h=660\u0026fm=jpg\u0026q=75\u0026fit=fill\u0026fill=blur"
        },
        "tile": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/tile.jpg"
        },
        "logo": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/logo.png?w=280\u0026h=80\u0026fm=png\u0026fit=fill"
        },
        "colorLogoSVG": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/colorLogoSVG.svg"
        },
        "colorLogoPNG": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/colorLogoPNG.png"
        },
        "solidLogoSVG": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/solidLogoSVG.svg"
        },
        "solidLogoPNG": {
            "path": "https://images.pluto.tv/channels/5459795fc9f133a519bc0bef/solidLogoPNG.png"
        },
        "featured": false,
        "featuredOrder": -1,
        "favorite": false,
        "isStitched": false,
        "tmsid": "115371"
    },
```

**Comment by Leatherface75** [comment]
Would be nice with support for closed captions/subtitles in this plugin.

**Pull request merged**
