### PR TITLE
plugins.huya: fix _hls_re

### LINKED ISSUE #3001: huya.com plugin - error message:  Unable to open URL: http://b''/
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
Huya.com plugin suddenly stop working and throws always an error like
`Could not open stream: Unable to open URL: http://b''/ `
It seems the URL of the video cannot be extracted correctly.

### Reproduction steps / Explicit stream URLs to test

1. Go to huya.com and get an ID of active stream
2. Start streamlink recording like streamlink -f -o test.mpg https://www.huya.com/503376 best

### Log output

```
streamlink -f -o test.mpg https://www.huya.com/503376  best
[cli][info] Found matching plugin huya for URL https://www.huya.com/503376
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream("http://b''/")> (Could not open stream: Unable to open URL: http://b''/ (HTTPConnectionPool(host="b''", port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe6633a4bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))))
error: Could not open stream <HLSStream("http://b''/")>, tried 1 times, exiting

```

### PR DESCRIPTION
**Pull request by Billy2011**
- fixes #3001
- update _hls_schema

### CODE REVIEW

**Comment by Billy2011** [comment]
@bastimeyer,
maybe it's because of your changes.

**Comment by bastimeyer** [comment]
> @bastimeyer,
> maybe it's because of your changes.

?

**Comment by Billy2011** [comment]
I was referring to the bug in the **install dependencies**.

**Comment by bastimeyer** [comment]
I'm still not sure what you're referring to, but if you're talking about the build failure, then it's because of a network timeout, as you can see here:
https://github.com/streamlink/streamlink/pull/3007/checks?check_run_id=737881980#step:5:176

The "Install dependencies" step on the "Windows installer" job installs dependencies via pip and apt:
https://github.com/streamlink/streamlink/blob/master/.github/workflows/main.yml#L80-L85

Just trigger a rebuild...

**Pull request merged**
