### PR TITLE
plugins.pluzz: fix magneto player XPath query

### LINKED ISSUE #5355: plugins.pluzz: La 1ere subdomain from francetvinfo.fr is not supported
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

VODs and 24/7 live from the La 1ere francetvinfo.fr subdomain (https://la1ere.francetvinfo.fr) are not supported by the Pluzz plugin. Find the original .m3u8 works for the live, but the link changes every (at least) 2 hours.

First log with VOD : https://la1ere.francetvinfo.fr/programme-video/la1ere_mitterrand-et-l-outre-mer/diffusion/2976069-espoir-et-promesses.html

Second log with live 24/7 : https://la1ere.francetvinfo.fr/info-en-continu-24-24 (HTTP referer needed for playing it)

French IP needed for playing both.

### Debug log

```text
streamlink --loglevel=debug https://la1ere.francetvinfo.fr/programme-video/la1ere_mitterrand-et-l-outre-mer/diffusion/2976069-espoir-et-promesses.html best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 5.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.29.0
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.5.1
[cli][debug] Arguments:
[cli][debug]  url=https://la1ere.francetvinfo.fr/programme-video/la1ere_mitterrand-et-l-outre-mer/diffusion/2976069-espoir-et-promesses.html
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="D:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
[cli][debug]  --ffmpeg-ffmpeg=C:\Users\Orion\AppData\Local\Programs\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin pluzz for URL https://la1ere.francetvinfo.fr/programme-video/la1ere_mitterrand-et-l-outre-mer/diffusion/2976069-espoir-et-promesses.html
[plugins.pluzz][debug] Country: FR
error: No playable streams found on this URL: https://la1ere.francetvinfo.fr/programme-video/la1ere_mitterrand-et-l-outre-mer/diffusion/2976069-espoir-et-promesses.html

streamlink --loglevel=debug --http-header "Referer= https://la1ere.francetvinfo.fr" https://la1ere.francetvinfo.fr/info-en-continu-24-24 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 5.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.29.0
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.5.1
[cli][debug] Arguments:
[cli][debug]  url=https://la1ere.francetvinfo.fr/info-en-continu-24-24
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="D:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
[cli][debug]  --ffmpeg-ffmpeg=C:\Users\Orion\AppData\Local\Programs\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --http-header=[('Referer', 'https://la1ere.francetvinfo.fr')]
[cli][info] Found matching plugin pluzz for URL https://la1ere.francetvinfo.fr/info-en-continu-24-24
[plugins.pluzz][debug] Country: FR
error: No playable streams found on this URL: https://la1ere.francetvinfo.fr/info-en-continu-24-24
```

### PR DESCRIPTION
**Pull request by bastimeyer**
Fixes #5355 

```
$ HTTPS_PROXY=socks5h://localhost:1920 python ./script/test-plugin-urls.py pluzz
:: Finding streams for URL: https://france3-regions.francetvinfo.fr/bourgogne-franche-comte/direct/franche-comte
:: Found streams: 216p, 360p, 540p, 720p, worst, best
:: Finding streams for URL: https://la1ere.francetvinfo.fr/info-en-continu-24-24
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://la1ere.francetvinfo.fr/programme-video/france-3_outremer-ledoc/diffusion/2958951-polynesie-les-sages-de-l-ocean.html
:: Found streams: 216p, 360p, 540p, 720p, worst, best
:: Finding streams for URL: https://www.france.tv/france-2/direct.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.france.tv/france-2/journal-20h00/141003-edition-du-lundi-8-mai-2017.html
:: Found streams: 144p, 180p, 288p, 396p, 576p, worst, best
:: Finding streams for URL: https://www.france.tv/france-3/direct.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.france.tv/france-4/direct.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.france.tv/france-5/direct.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.france.tv/franceinfo/direct.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.francetvinfo.fr/en-direct/tv.html
:: Found streams: 144p, 216p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.francetvinfo.fr/meteo/orages/inondations-dans-le-gard-plus-de-deux-mois-de-pluie-en-quelques-heures-des-degats-mais-pas-de-victime_4771265.html
:: Found streams: 216p, 360p, 540p, 720p, worst, best
```

@Facy5 please check and see if anything else isn't working that I might have missed

### CODE REVIEW

**Comment by bastimeyer** [comment]
> ```
> File "C:\Users\Orion\AppData\Roaming\streamlink\plugins\pluzz\test_pluzz.py", line 2, in <module>
>     from tests.plugins import PluginCanHandleUrl
> ModuleNotFoundError: No module named 'tests'
> ```

Why are you trying to side-load the plugin test file? This doesn't belong there and it has nothing to do with the actual plugin bugfixes.

Delete `test_pluzz.py` from your `C:\Users\Orion\AppData\Roaming\streamlink\plugins\` directory.

----

https://streamlink.github.io/cli/plugin-sideloading.html
> If one of the sideloaded plugins fails to load, eg. due to a SyntaxError being raised by the parser, this exception will not get caught by Streamlink and the execution will stop, even if the input stream URL does not match the faulty plugin.

**Comment by bastimeyer** [comment]
> I also check others France TV related

These are not supported by the plugin, as you can see here:
https://streamlink.github.io/plugins.html#pluzz

**Comment by Facy5** [comment]
Oh sorry, so as I said, I was my fault 😅 (first time I sideload a plugin)
Now it's ok

```
PS C:\Users\Orion> streamlink --plugin-dir C:\Users\Orion\AppData\Roaming\streamlink\plugins\pluzz https://la1ere.francetvinfo.fr/saintpierremiquelon/programme-video/la1ere_saint-pierre-et-miquelon_ca-vaut-le-detour/diffusion/4892719-emission-du-jeudi-18-mai-2023.html best
[cli][info] Found matching plugin pluzz for URL https://la1ere.francetvinfo.fr/saintpierremiquelon/programme-video/la1ere_saint-pierre-et-miquelon_ca-vaut-le-detour/diffusion/4892719-emission-du-jeudi-18-mai-2023.html
[cli][info] Available streams: 216p (worst), 360p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls-multi)
[cli][info] Starting player: "D:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
[utils.named_pipe][info] Creating pipe streamlinkpipe-45616-1-8184
[utils.named_pipe][info] Creating pipe streamlinkpipe-45616-2-7404
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

PS C:\Users\Orion> streamlink --plugin-dir C:\Users\Orion\AppData\Roaming\streamlink\plugins\pluzz https://la1ere.francetvinfo.fr/info-en-continu-24-24 best
[cli][info] Found matching plugin pluzz for URL https://la1ere.francetvinfo.fr/info-en-continu-24-24
[cli][info] Available streams: 144p (worst), 216p, 360p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: "D:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

> 
> These are not supported by the plugin, as you can see here: https://streamlink.github.io/plugins.html#pluzz

Ok, I see. So Even if those websites are France TV related, and use the same player as france.tv, they won't be added, right ?

**Comment by bastimeyer** [comment]
> they won't be added, right

No, because there are no live streams and the plugin would require further modifications in order to support those sites.

**Comment by Facy5** [comment]
Ok !

**Pull request merged**
