### PR TITLE
plugins.bigo: reflect recent changes in server API

### PR DESCRIPTION
**Pull request by trodiz**
Bigo Live's web api, which this plugin relies on, has changed some of its server endpoints and terminologies. This is the underlying reason for this issue: https://github.com/streamlink/streamlink/issues/3626. This patch solves it.

### CODE REVIEW

**Comment by unnutricious** [comment]
This change itself looks fine, but I don't think it has any real effect. Both the old and new API still work, but from my quick tests as of today, both still do not work for many rooms. The hls_src field is missing in the new API just as the videoSrc field is missing in the old. I did observe that bigo.tv now seems to only show a small number of rooms compared to the app, so it seems the site/API is still just broken on the bigo server side.

**Comment by back-to** [comment]
@unnutricious 

> both still do not work for many rooms. 

share the links

**Comment by unnutricious** [comment]
> > 
> 
> share the links

It's not specific rooms, it's random per broadcast, so I can't share a link that would be of any use unless we are debugging this in real-time. To easily see the problem with the website now:
1. Go to bigo.tv and click LIVE and select a country.
2. Compare the result to the Android/Apple app for the same country. Only a small number of streams will show up. The ones that do show up will work in browser and if you query the API endpoint, hls_src will be present and populated.
2. Select a broadcast randomly from the app that does not show up on bigo.tv and query the API with siteId={bigo_id}. You will see the metadata is returned correctly, but most of the time (but not all the time), hls_src will be missing.

I observed that hls_src seems to be present when a stream first starts and then disappears after a few minutes in some cases. In other cases, I don't think it shows up at all, but it's hard to tell since I have no way to trigger on a broadcast.

**Comment by back-to** [comment]
> Select a broadcast randomly from the app that does not show up on bigo.tv

If it doesn't work on there website, it won't work with Streamlink.

---

closing

The old API still works as expected, this PR is currently not needed.

**Comment by eccccco** [comment]
My recent observation about this issue:

 I successfully used streamlink to open a BIGO stream (with username not ID). The Stream was live in the App.
 after 15 minutes i made the following tests (the stream was still playing over streamlink):

- stream was offline on the bigo website
- stream was online in the app and listed in the country list in the app (not private/premium or something like that)
- opening a new streamlink instance did NOT open the stream a second time (the initial stream was still working with streamlink)
- using the API request "...OInterface/getVideoParam?bigoId= " returned "code=0" msg "success" but NO values for wsUrl and videoSrc
- using the newer API request ".../studio/getInternalStudioInfo?siteId= " did NOT return the hlsUrl

**Comment by trodiz** [comment]
> * using the newer API request ".../studio/getInternalStudioInfo?siteId= " did NOT return the hlsUrl

Do make sure that this new format of request is using POST method and not GET.

**Comment by unnutricious** [comment]
> > * using the newer API request ".../studio/getInternalStudioInfo?siteId= " did NOT return the hlsUrl
> 
> Do make sure that this new format of request is using POST method and not GET.

I did try both POST and GET, I get the same issue and everything else shows as if the user is offline, 'alive' is 0. If you browse to the bigo.tv url, it will show the room as offline, and it is querying the API itself. Let me know if you want to discuss more details of if you are seeing different behavior. I was looking at supporting the bigo app protocol, but my progress has been slow, as it is all binary. This module used to support it, but I removed it a few years ago because the video was coming out corrupted. Since then, there is no way to get the ip/port info for the app stream from the website now that flash support has been removed.

**Pull request closed without merging**
