### PR TITLE
installer: build a Windows XP compatible installer

### PR DESCRIPTION
**Pull request by beardypig**
Uses a bundled Python 3.4.4 installer.
A new build of ffmpeg 3.2.4 has been included which supports Windows XP+.

I have tested the new ffmpeg.exe on Windows XP Professional SP3, Windows Vista Enterprise SP2, Windows 7 Enterprise SP1, and Windows 10 Home 1607.

Could do with some eyeballs :)

If anyone need me to build an XP version of the installer to test, just ask!

### CODE REVIEW

**Comment by bastimeyer** [comment]
It's not a bad idea of you supporting WinXP with a separate installer. Maybe there's one or the other Windows user who's still using XP, who knows.

There's one big concern by me, though:
We shouldn't be pushing several large binaries to the repo. I'm not talking about the installers, but the new ffmpeg executable instead. There are already 4 revisions of the rtmpdump exe and dll files and one revision of the 50MiB sized ffmpeg exe. Cloning the repo becomes a pain by updating and adding new large binaries after a certain time. The overall (compressed) size of the repo and its master branch is already 33MiB. Cloning your streamlink fork with just the winxp-installer branch already results in a 66MiB sized repo, and this was just one change to the ffmpeg binary.
The binaries either should be hosted in a different repo or somewhere else. Maybe git LFS could be a solution, although I haven't used it before and don't know exactly how it works with a github repo (large files become pointers to the real data which is stored somewhere else).

**Comment by gravyboat** [comment]
What's the reasoning behind wanting to support XP? It's EoL at this point. Did we have some users specifically requesting this? I also agree with @bastimeyer regarding trying to keep the repo small, if we need to make another repo and use submodules (which I would definitely prefer NOT to do because submodules are :thumbsdown:) we can do so if we absolutely must.

**Comment by beardypig** [comment]
Git LFS would be ideal, just means an extra step when cloning but maybe it's OK if you don't want to touch the big files :) We can always prune the files from the history, rewrite the history a bit ... I don't mind sorting that out :)

While XP is EoL, there are a few of people still using it (for some reason). If you read through the Livestream issues to see people are still using XP and cannot switch to Streamlink. 

Gotta catch 'em all...

**Comment by karlo2105** [comment]
I am not against Win Xp version for streamlink. Personally i installed streamlink development on xp from source code, only ffmpeg made problem. 
I think it would be better to make it on separate branch and maybe portable version made on development builds.
Xp is still used between 5 to 8 % of users.

**Comment by gyvess** [comment]
@beardypig I'd like an XP build to test.

With regards to including binaries in the repo, from the perspective of a user I wouldn't worry about it too much.  I also use youtube-dl and its inclusion of avconv/ffmpeg as noted requirements for some functions was enough for me to search them out and install them myself.  As long as you guys include separate arguments to point to the directories for these files, just as you have for player and rtmpdump, as well as hinting at the binaries on the documentation page everything should be fine.

**Comment by gravyboat** [comment]
Are we done discussing this? I don't feel like we've come to a conclusion but I would like to get this merged in, we've got way too many open PRs and I don't want to lose the context.

**Comment by beardypig** [comment]
I wanted to take a look at git LFS first, I agree with @bastimeyer about the large files :-)

**Comment by vadosnaprimer** [comment]
Thanks for considering this guys. While XP is a vanishing minority, those who want to stick to it for whatever reason are gonna stick to it. And when backward compatibility is lost, it's justified if it's due to some modern features. But when it's a matter of swapping some files and still getting all the features of the stock version, dropping XP doesn't look like a real requirement.

**Comment by beardypig** [comment]
The XP installer is a bit larger than the regular installer and required some changes to the ffmpeg build options. It's more work to support XP, it doesn't come for free :-)

**Comment by beardypig** [comment]
@gyvess here is a link to the [Windows XP Installer](https://s3.amazonaws.com/streamlink-builds/beardypig/streamlink-0.5.0-winxp-4624db4.exe).

**Comment by beardypig** [comment]
The `ffmpeg.exe` and `rtmpdump.exe` are now stored in Git LFS, they still exist in the history - removing them would mean rewriting the history which would cause a few problems :)

**Comment by gyvess** [comment]
Sorry for being a little slow in testing this.

Downloaded and installed.  Immediately tested youtube and 60FPS videos are working, however being able to skip through video no longer works.  I double checked to make sure my player-passthrough was set to HTTP, which is what allowed this functionality in the original livestreamer, and it was set.

I went on to try twitch.tv and openrec.tv, both spit out similar text without opening the stream.

> C:\Program Files\Streamlink\bin>streamlink.exe twitch.tv/vinesauce
[cli][info] Found matching plugin twitch for URL twitch.tv/vinesauce
Traceback (most recent call last):
  File "C:\Program Files\Streamlink\bin\streamlink-script.py", line 12, in <module>
    main()
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 1024, in main
    handle_url()
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugin\plugin.py", line 325, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugin\plugin.py", line 234, in streams
    ostreams = self._get_streams()
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugins\twitch.py", line 617, in _get_streams
    return self._get_hls_streams("live")
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugins\twitch.py", line 581, in _get_hls_streams
    force_restart=not stream_type == "live")
  File "C:\Program Files\Streamlink\pkgs\streamlink\stream\hls.py", line 288, in parse_variant_playlist
    locale = session_.localization
  File "C:\Program Files\Streamlink\pkgs\streamlink\session.py", line 474, in localization
    return Localization(self.get_option("locale"))
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\l10n.py", line 115, in __init__
    self.language_code = language_code
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\l10n.py", line 140, in language_code
    self.language, self.country = self._parse_locale_code(language_code)
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\l10n.py", line 125, in _parse_locale_code
    return self.get_language(parts[0]), self.get_country(parts[1])
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\l10n.py", line 168, in get_language
    return Language.get(language)
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\l10n.py", line 75, in get
    l = languages.get(alpha2=language)
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 265, in get
    return getattr(self, key)[value]
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 132, in __getattr__
    'alpha2': self.part1,
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 105, in __get__
    val = self.f(instance)
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 198, in part1
    return dict((x.part1, x) for x in self.languages if x.part1)
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 105, in __get__
    val = self.f(instance)
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 174, in languages
    l, i, m, p5, p2, p1 = _fabtabular()
  File "C:\Program Files\Streamlink\pkgs\iso639\iso639.py", line 20, in _fabtabular
    from pkg_resources import resource_filename
  File "C:\Program Files\Streamlink\pkgs\pkg_resources\__init__.py", line 48, in <module>
    import six
ImportError: No module named 'six'

I don't want to take up too much space with this so I'll move on to say I tried Periscope as well, but I received an error saying no plugin can handle the URL.  Uninstalled and reinstalled just in case, same thing in each case.

**Comment by beardypig** [comment]
@gyvess thanks for testing it. Should be simple to fix the error. 
For the 60 fps and very high quality videos on YouTube you won't be able to seek, they are made up of 2 separate streams that are combined: one video and one audio stream. Ffmpeg is used to combine (mux) them and pipe the output to your video player, it is not possible to use the pass through options for those videos.

**Comment by beardypig** [comment]
@gravyboat @bastimeyer I have updated the PR with a possible alternative, the `ffmpeg.exe`, `rtmpdump.exe`, and `librtmp.dll` files are stored in a separate repo (`streamlink-assets`) and pulled down with wget from the `master` branch. Seems to work well enough. (NB: currently it's pointing to _my_ fork of the `streamlink-assets` repo). 

Another alternative would be submodules, but @gravyboat said they are 🗑 .

**Comment by beardypig** [comment]
@gyvess here's an update [Windows XP Installer](https://s3.amazonaws.com/streamlink-builds/beardypig/streamlink-0.5.0-winxp-215d9d6.exe).

**Comment by gyvess** [comment]
Youtube: Live streams work.
Openrec.tv: Working.

Periscope: Error once again reports that no plugin was found.  I can see that periscope.py exists within the pkgs\streamlink\plugins directory so I don't know.

Twitch: Streamlink launches the player but neither video or sound plays.  Outcome is the same regardless of live stream or VOD.

I'm using the latest nightly of MPC-HC just in case that's relevant.

**Comment by beardypig** [comment]
Periscope could be a separate issue unrelated to the XP-ness. I don't know much about the periscope plugin :)

Strange that the twitch streams do not work, could say give an example VOD link that does not work?

**Comment by Vangelis66** [comment]
@beardypig wrote: 

> Uses a bundled Python 3.3.4 installer.

... Just being pedantic, but it actually is 
**python-3.4.4.msi** 
so a Python 3.4.4 (win32) installer! 

Cheers

**Comment by beardypig** [comment]
@Vangelis66 it sure does! Nice to see you back.

**Comment by gyvess** [comment]
Tried VLC and it opened up fine, albeit choppy but I assumed that could be due to VLC being a worse performer.  Bummer, I quite like MPC-HC.

Good news though,  in switching the player to VLC though my streamlinkrc.twitch config file I found the culprit.  I'd had player-passthrough set to HLS to allow seeking on twitch vods.  Changing it to rtmp allows smooth playback in VLC and better yet allows playback in MPC-HC.

I switched to see if http would work on a VOD and it did.  So then I tried HLS again then that worked with seeking on a VOD.  Then I tried HLS on a livestream and it went back to not working.  Tried the same VOD from before with HLS still on, and it failed to work this time.  Confusing but it does work with rtmp fine so there is that.

**Comment by Vangelis66** [comment]
@beardypig wrote: 

> it sure does! 

... but there's still mention of version 3.3.4 in https://github.com/streamlink/streamlink/pull/680/commits/d60279d6bb1e7c9b30f34a34e79093331ade6f6b 's description... :-(

> Nice to see you back.

... Well, real life issues, an extremely harsh winter, frail health, hay fever currently, focus shifting onto other projects, my OS (Vista) being EOL'd and what have you meant I stopped following streamlink's development in early January; I have 2 or 3 bugs queued for reporting, but if I am to really "come back" would need me studying commits pushed/issues opened-closed/PRs submitted after Jan 8th, so some time to digest new things... 
I see you had your hands quite full in the meantime, just as well I wasn't around adding to that :smile: 
BTW, many thanks for the Vista compatible FFmpeg-3.2.4-win32 binary!

Regards

**Comment by vadosnaprimer** [comment]
I thought XP users were a dying breed, only to learn some are still on Vista...

**Comment by gravyboat** [comment]
So do we want to put the binaries over in https://github.com/streamlink/streamlink-assets or what are we doing for this now?

**Comment by Vangelis66** [comment]
@beardypig 

Hello :-) 
I have recently compiled an FFmpeg-3.3-win32 binary with most needed 
external libs (audio codecs, video codecs, filters) that should be more than 
enough for streamlink requirements...
This is a native compile on Windows Vista SP2 32bit, using 
https://github.com/jb-alvarado/media-autobuild_suite
This is a distributable GPLv3 executable that runs fine on Vista SP2 32bit 
and SHOULD run on Windows XP SP3 32bit (not able to test currently ;-( ).

Size of the executable is just 36.4 MiB, so ca. 20 MB less than the one currently offered 
inside streamlink's Windows installers (standard & the XP-compat this PR is about). 

I have uploaded this (together with source and lics) to 

http://www.datafilehost.com/d/3ddcd138

(7-zip needed to decompress)
 
Can you kindly check if it works OK in your VMs and if it indeed 
does and meets with other streamlink requirements, perhaps it 
could be adopted in a more general manner...

I have read recent issues pertaining to the increased size of 
the FFmpeg binary, a reduced size one surely can't harm... 

Regards

**Comment by beardypig** [comment]
Sounds good. Do you have the settings that you used to build the binary? I'd like to be able to recreate it too. Thanks :-)

**Comment by Vangelis66** [comment]
@beardypig wrote: 

> Do you have the settings that you used to build the binary? 
> I'd like to be able to recreate it too.

...Err, it isn't as simple as it might appear... 
**media-autobuild_suite** only supports building the latest snapshot 
from the master branch, currently at n3.4-dev. 
 Since I am on Vista x86, I have only installed the 32bit toolchain 
(and built only win32 executables); plus, cmake provided by the MSYS2 toolchain 
is Win7+ only, so I had to do [this](https://github.com/jb-alvarado/media-autobuild_suite/issues/507#issuecomment-296303081). 
The 64bit toolchain can also build 32bit binaries, possibly quicker...

I first built all the needed external libs (see Configuration.txt inside my package) 
by running the suite via media-autobuild_suite.bat; 
the "build/media-autobuild_suite.ini" config file is created according to user's selections 
when first executing that .bat, before subsequent runs it can be edited accordingly... 
Be sure to select the 32bit architecture and WinXP compat flags.
A custom [ffmpeg_options.txt](https://github.com/streamlink/streamlink/files/990679/ffmpeg_options.txt) was put inside build dir; you can add/subtract libs as desired...

When all needed libs were successfully compiled and installed 
and the suite proceeded to check for ffmpeg-git updates, I killed 
the minnty console (or you can leave it running to compile the 
latest ffmpeg-git version). 

1. 3.3 source was extracted to build/ffmpeg-3.3
2. A new folder was created, build/ffmpeg-3.3/build-static-32bit
Compilation of 3.3 was done purely via minnty console, manually:  
3. Remove ffmpeg stuff (if it exists) from prior compilations:
```
rm -rf $LOCALDESTDIR/include/libavutil
rm -rf $LOCALDESTDIR/include/libavcodec
rm -rf $LOCALDESTDIR/include/libpostproc
rm -rf $LOCALDESTDIR/include/libswresample
rm -rf $LOCALDESTDIR/include/libswscale
rm -rf $LOCALDESTDIR/include/libavdevice
rm -rf $LOCALDESTDIR/include/libavfilter
rm -rf $LOCALDESTDIR/include/libavformat
rm -f $LOCALDESTDIR/lib/libavutil.a
rm -f $LOCALDESTDIR/lib/libswresample.a
rm -f $LOCALDESTDIR/lib/libswscale.a
rm -f $LOCALDESTDIR/lib/libavcodec.a
rm -f $LOCALDESTDIR/lib/libavdevice.a
rm -f $LOCALDESTDIR/lib/libavfilter.a
rm -f $LOCALDESTDIR/lib/libavformat.a
rm -f $LOCALDESTDIR/lib/libpostproc.a
rm -f $LOCALDESTDIR/lib/pkgconfig/libavcodec.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libavutil.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libpostproc.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libswresample.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libswscale.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libavdevice.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libavfilter.pc
rm -f $LOCALDESTDIR/lib/pkgconfig/libavformat.pc
```
4. cd build/ffmpeg-3.3/build-static-32bit
5. Run the following ffmpeg configure (see Configuration.txt): 
```
../configure --arch=x86 --target-os=mingw32 --prefix=$LOCALDESTDIR --bindir=$LOCALDESTDIR/bin-video --pkg-config-flags=--static --enable-fontconfig --enable-libass --enable-libbs2b --enable-libfreetype --enable-libfribidi --enable-libsoxr --enable-libmp3lame --enable-libvorbis --disable-encoder=vorbis --enable-libspeex --enable-libopus --enable-libgsm --enable-libilbc --enable-libtwolame --enable-libwavpack --enable-libxvid --enable-libtheora --enable-libvpx --enable-libx264 --enable-libopenh264 --enable-libx265 --enable-libxavs --enable-libkvazaar --enable-libzvbi --enable-libopenjpeg --enable-libwebp --enable-gnutls --enable-libssh --enable-librtmp --enable-gpl --enable-version3 --disable-ffplay --disable-sdl2 --disable-ffprobe --disable-debug --disable-shared --enable-doc --extra-libs='-lgomp -lpng' --extra-cflags='-DLIBTWOLAME_STATIC -DLIBSSH_STATIC -DKVZ_STATIC_LIB -fopenmp -msse -mfpmath=sse' --optflags='-O2 -finline-functions' --extra-ldflags='-Wl,--allow-multiple-definition'
```
6. Apply some "cosmetics" 
`sed -i "s|--target-os=mingw32 --prefix=$LOCALDESTDIR --bindir=$LOCALDESTDIR/bin-video --pkg-config-flags=--static ||g" config.h`
7. Start compiling: 
`make`
(you may want to reduce CPU cores by one, say `make -j1` for a 2 Core CPU)
8. Install things: 
`make install`
9. You'll find (hopefully) the compiled ffmpeg.exe binary inside "/local32/bin-video" dir.

Hope it's now clear to you...

**Comment by Vangelis66** [comment]
> and SHOULD run on Windows XP SP3 32bit (not able to test currently ;-( ).

... Just tested it on a friend's old Windows XP SP2 Pro desktop (not connected 
to the Internet currently) and it sure does run there fine...

**Comment by back-to** [comment]
you want to support people with XP,
microsoft doesn't even want to support them.

**I wouldn't support XP users**, i would just drop it.

---

I would remove every win xp reference

_like here_

https://streamlink.github.io/install.html#windows-binaries

**Nobody should expect** that something will work on XP or 95, 98, ME, VISTA etc. in **2017**

**Comment by gravyboat** [comment]
@beardypig I'm going to close this, everyone has been really busy lately and it's clear we don't have time to deal with any bugs or issues that might arise with XP, it's a dead OS people should upgrade.

**Pull request closed without merging**
