### PR TITLE
plugins.mjunoon: support for live and vod streams on mjunoon.tv

### LINKED ISSUE #1834: plugin rerquest for mjunoon
https://www.mjunoon.tv/

streamlink https://www.mjunoon.tv/a-tv-live
[cli][info] streamlink is running as root! Be careful!
error: No plugin can handle URL: https://www.mjunoon.tv/a-tv-live

### PR DESCRIPTION
**Pull request by beardypig**
Support for both live and VOD streams from mjunoon.tv. 

Would be nice to have someone test it out. 

Fixes #1834

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks @beardypig.

**Comment by maanich** [comment]
cheers mates all is ok with the plugin except certificate verification.

**Comment by amjiddader** [comment]
Just checked.. 

Its not working tried few channels. 
no playable link.. 
any expected fix?

**Comment by gravyboat** [comment]
@amjiddader Open a new bug issue and fill out all the template requirements.

**Pull request merged**
