### PR TITLE
Changed the twitch plugin to use https instead of http

### PR DESCRIPTION
**Pull request by Erk-**
as discussed in #103

### CODE REVIEW

**Comment by gravyboat** [comment]
Were you able to build this and confirm everything worked correctly locally?

**Comment by Erk-** [comment]
Yes it worked with the streams I tried I could not get the audio option to work but, it does not work in the normal version either.

**Comment by gravyboat** [comment]
I'll merge this for now then, thanks!

**Comment by stevek123** [comment]
Audio only also works great for me with:
`streamlink https://www.twitch.tv/monstercat audio`

**Comment by Erk-** [comment]
It must be something with my setup then.

**Pull request merged**
