### PR TITLE
Update for major tvplayer.com site change

### PR DESCRIPTION
**Pull request by mkbloke**
Fix site login token in authenticate() and login_token_re
Fix attributes parsing in _get_stream_attrs()
Fix return of correct stream URL in _get_stream_data()
Fix DRM checking in _get_streams()

closes https://github.com/streamlink/streamlink/issues/2456

### CODE REVIEW

**Comment by mkbloke** [comment]
Some of the coding, particularly the stuff around schema validation is probably a bit of an atrocity, but I really do not understand any of that.  Mostly, I think it's probably OK.

One thing I have noticed is that this seems to expose a stream quality of 75k when the plugin is used.  I'm not sure where that comes from, but it does not work if you attempt to use that value.  All the other stream qualities work.

**Comment by mkbloke** [comment]
By the way, do the tests need a little fix?  tvplayer.com has not been streaming Dave for quite some time now...

**Comment by back-to** [comment]
> By the way, do the tests need a little fix? 

this is most important

https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/tests/plugins/test_tvplayer.py#L16-L30

the other tests are nice to have, but not important and can be removed.

---

However, I cannot test your changes.

> Sorry, This website is not not available in your country.

**Comment by mkbloke** [comment]
OK.  I sort of get it now.  I needed to change the mock page data in the test.  Now I get:
```
_____________________ TestPluginTVPlayer.test_get_streams ______________________

self = <tests.plugins.test_tvplayer.TestPluginTVPlayer testMethod=test_get_streams>
hlsstream = <MagicMock name='HLSStream' id='139992977406288'>
mock_get_stream_data = <MagicMock name='_get_stream_data' id='139992976996624'>

    @patch('streamlink.plugins.tvplayer.TVPlayer._get_stream_data')
    @patch('streamlink.plugins.tvplayer.HLSStream')
    def test_get_streams(self, hlsstream, mock_get_stream_data):
        mock_get_stream_data.return_value = {
            "stream": "http://test.se/stream1"
        }
    
        page_resp = Mock()
        page_resp.text = u"""
                    data-player-library="videojs"
                                            data-player-id="ILWmaLKV41Ql8kF"
                                        data-player-key="2Pw1Eg0Px3Dy9Jm3Ly8Dr5Bi5Vc5Nk"
                    data-player-uvid="739"
                    data-player-token="294c808a378a09d6e36d0253ab3765af"
                    data-player-expiry="1581958189"
                    data-player-poster=""
        """
    
        self.session.http.get.return_value = page_resp
        hlsstream.parse_variant_playlist.return_value = {"test": HLSStream(self.session, "http://test.se/stream1")}
    
        TVPlayer.bind(self.session, "test.tvplayer")
        plugin = TVPlayer("http://tvplayer.com/watch/dave")
    
>       streams = plugin.streams()

tests/plugins/test_tvplayer.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../streamlink/local/lib/python2.7/site-packages/streamlink/plugin/plugin.py:317: in streams
    ostreams = self._get_streams()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <streamlink.plugins.tvplayer.TVPlayer object at 0x7f52a7cc9150>

    def _get_streams(self):
        if self.get_option("email") and self.get_option("password"):
            self.logger.debug("Logging in as {0}".format(self.get_option("email")))
            if not self.authenticate(self.get_option("email"), self.get_option("password")):
                self.logger.warning("Failed to login as {0}".format(self.get_option("email")))
    
        # find the list of channels from the html in the page
        self.url = self.url.replace("https", "http")  # https redirects to http
        res = self.session.http.get(self.url)
    
        if "enter your postcode" in res.text:
            self.logger.info("Setting your postcode to: {0}. "
                             "This can be changed in the settings on tvplayer.com", self.dummy_postcode)
            res = self.session.http.post(self.update_url,
                            data=dict(postcode=self.dummy_postcode),
                            params=dict(return_url=self.url))
    
        stream_attrs = self._get_stream_attrs(res)
        if stream_attrs:
            stream_data = self._get_stream_data(**stream_attrs)
            if stream_data:
                if stream_data.get("drm"):
                    self.logger.error("This stream is protected by DRM can cannot be played")
                    return
                else:
>                   return HLSStream.parse_variant_playlist(self.session, stream_data["response"]["stream"])
E                   KeyError: 'response'

../../streamlink/local/lib/python2.7/site-packages/streamlink/plugins/tvplayer.py:112: KeyError
```

Any pointers or help on how to fix it would be much appreciated.

Thanks.

**Comment by mkbloke** [comment]
I'll close this PR while I try to sort things out, then open a new one...

**Pull request closed without merging**
