### PR TITLE
plugins.ard_live: updated to new site layout

### PR DESCRIPTION
**Pull request by beardypig**
As reported by @karlo2105 in #660 the `ard_live` was no longer working.

Updated the plugin to support the new site layout, also added support for VOD streams.

### CODE REVIEW

**Comment by karlo2105** [comment]
Muy bien. ;)

**Comment by back-to** [comment]
You should **change the regex** for `ard_live`
it should
**only works for** `http://www.daserste.de`
or
**not for** `http://mediathek.daserste.de`

`http://mediathek.daserste.de` is the same as the plugin **ard_mediatheak**

`ardmediathek.de` has more videos but all videos from `mediathek.daserste.de` are there.

They have the _same_ urls, just a bit different regex
```
http://www.ardmediathek.de/tv/extra-3/Automobil-Lobbyist-Maxi-Schafroth-zum-Th/Das-Erste/Video?bcastId=23817212&documentId=41101758

http://mediathek.daserste.de/extra-3/Automobil-Lobbyist-Maxi-Schafroth-zum-Th/Video?bcastId=23817212&documentId=41101758
```
 and here the same video for `www.daserste.de` but this works with `ard_live`
```
http://www.daserste.de/unterhaltung/comedy-satire/extra-3/videosextern/automobil-lobbyist-maxi-schafroth-zum-thema-stickoxide-100.html
```

New regex for `ard_mediatheak` something like this
```py
_url_re = re.compile(r"http(s)?://(?:(\w+\.)?ardmediathek.de/tv|mediathek.daserste.de/)")
```

**Comment by beardypig** [comment]
True that. I've updated the regex :)

**Comment by gravyboat** [comment]
Thanks @beardypig and thanks for weighing in @back-to!

**Pull request merged**
