### PR TITLE
ecanlitvizle.net changed url to ecanlitvizle.tv

### PR DESCRIPTION
**Pull request by Rotarum**

### CODE REVIEW

**Comment by Rotarum** [comment]
ecanlitvizle.net is not working!

Please change .net to .tv

Why has the check failed??

**Comment by bastimeyer** [comment]
> Why has the check failed??

https://travis-ci.org/streamlink/streamlink/jobs/331219757#L1642

You also have to change the tests (which try to match the plugin's URLs):
https://github.com/streamlink/streamlink/blob/0.10.0/tests/test_plugin_canlitv.py#L21

**Comment by dreamboxco** [comment]
on the page e canli no picture is reproduced I think that is because of the side

**Comment by beardypig** [comment]
Closing this PR as we are removing the ecanlitvizle plugin, most of the channels are covered by other plugins - if there are channels that are not covered, please open an issue to support that channel's  *official* site.

**Pull request closed without merging**
