### PR TITLE
Release 1.1.1

### PR DESCRIPTION
**Pull request by bastimeyer**
If there are more changes which should be included in this patch release, let me know. :smiley: 
Otherwise, just go ahead and merge+tag. Thanks!

### CODE REVIEW

**Comment by beardypig** [comment]
I'd say merge/tag this one with just that change.

**Comment by bastimeyer** [comment]
Merged, tagged and fingers crossed...
https://travis-ci.org/streamlink/streamlink/builds/514899015

**Comment by bastimeyer** [comment]
https://travis-ci.org/streamlink/streamlink/jobs/514899020#L3643
https://pypi.org/project/streamlink/#files
:+1:

**Comment by gravyboat** [comment]
Thanks for tagging the release @bastimeyer!

**Pull request merged**
