### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by hicrop**

### CODE REVIEW

**Comment by back-to** [comment]
looks good,
but it might make other PR's incompatible or this PR will be incompatible

so some rebase will be required, depends on what get merged first.

**Comment by beardypig** [comment]
All sensible PEP8 fixes :)

**Comment by gravyboat** [comment]
Le's merge some of the other PRs first since they have more critical changes and this should be easier to rebase instead of getting a bunch of different users to do so.

**Comment by gravyboat** [comment]
@hicrop Let me try to get what we can merged tonight then you shouldn't have to rebase multiple times.

**Pull request merged**
