### PR TITLE
HLS "Seeking" support

### PR DESCRIPTION
**Pull request by beardypig**
It's not really seeking because you can only skip the beginning and end of the streams, but it should go some way to bridging the gap between no seeking and full seeking support. The seeking support is also added to the HLSStream API - which I added for forthcoming plugins. 

I don't expect this to be merged right away, but rather I'm opening it now because it's been in the works and on-hold for a while and I'd like some feedback.

### CODE REVIEW

**Comment by back-to** [comment]
if `--hls-duration` is not set on python2.7

```
streamlink -l debug https://www.twitch.tv/videos/187938112 worst --hls-start-offset 01:44:12
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/187938112
[plugin.twitch][debug] Getting video HLS streams for reckful
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60_alt, 720p60 (best)
[cli][info] Opening stream: 160p (hls)
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.8.1', 'console_scripts', 'streamlink')()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 1056, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 506, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 388, in handle_stream
    success = output_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 254, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 229, in open_stream
    stream_fd = stream.open()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink/stream/hls.py", line 305, in open
    reader.open()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink/stream/segmented.py", line 185, in open
    self.worker = self.__worker__(self)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink/stream/hls.py", line 127, in __init__
    self.duration_limit = int(self.session.options.get("hls-duration") or self.stream.duration) or None
TypeError: int() argument must be a string or a number, not 'NoneType'
```

---

`streamlink -l debug https://www.twitch.tv/videos/187938112 worst --hls-start-offset 01:44:12 --hls-duration 00:01:00`

There is a ~10 sec difference
https://www.twitch.tv/videos/187938112?t=01h44m12s

`--hls-start-offset 01:44:12` is https://www.twitch.tv/videos/187938112?t=01h44m22s

the website will start at **633.ts** and streamlink at **634.ts**

**Comment by beardypig** [comment]
Ah yeah, thanks @back-to forgot to push that :) I'll take a look at that off-by-one bug...

**Comment by beardypig** [comment]
Looks like a difference in rounding-up or rounding-down, my current implementation picks the next segment - so might actually miss your desired offset. Should be the other way around... nice find @back-to thanks.

**Comment by back-to** [comment]
hls streams are broken now

- Start offset: 0;
`00:00:00` will close after some seconds
- Start offset: 1
`00:00:01` will work

```
streamlink https://www.zdf.de/nachrichten/heute-journal/heute-journal-vom-12-november-2017-100.html 720p -l debug --hls-start-offset 00:00:00
[cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/nachrichten/heute-journal/heute-journal-vom-12-november-2017-100.html
[cli][info] Available streams: 96k (worst), 215k, 136p, 452k, 176p_alt, 176p, 735k, 272p, 360p, 480p, 1389k, 576p, 720p, 2129k, 3067k (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1; Last Sequence: 96
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 96; End Sequence: 96
[stream.hls][debug] Adding segment 96 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Closing worker thread
[cli][info] Starting player: /usr/bin/vlc
[stream.hls][debug] Download of segment 96 complete
[stream.hls][debug] Closing writer thread
[cli][debug] Writing stream to output
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

```
streamlink https://www.zdf.de/nachrichten/heute-journal/heute-journal-vom-12-november-2017-100.html 720p -l debug --hls-start-offset 00:00:01
[cli][info] Found matching plugin zdf_mediathek for URL https://www.zdf.de/nachrichten/heute-journal/heute-journal-vom-12-november-2017-100.html
[cli][info] Available streams: 96k (worst), 215k, 136p, 452k, 176p_alt, 176p, 735k, 272p, 360p, 480p, 1389k, 576p, 720p, 2129k, 3067k (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1; Last Sequence: 96
[stream.hls][debug] Start offset: 1; Duration: None; Start Sequence: 1; End Sequence: 96
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Adding segment 22 to queue
[cli][info] Starting player: /usr/bin/vlc
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Adding segment 23 to queue
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 2 complete
[stream.hls][debug] Adding segment 24 to queue
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Adding segment 25 to queue
[stream.hls][debug] Download of segment 4 complete
[stream.hls][debug] Adding segment 26 to queue
[stream.hls][debug] Download of segment 5 complete
[stream.hls][debug] Adding segment 27 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 6 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by gravyboat** [comment]
How are you feeling on this now?

**Comment by back-to** [comment]
since the **basic functions** for hls-vods **are working,**
maybe merge it so more people can test it without dealing with `git`

**Comment by beardypig** [comment]
Yeah maybe can merge this and get people to test it out, not sure before or after 0.10.0 though.

**Comment by gravyboat** [comment]
@beardypig I say we do it, it's not going to break anything and it's not a 1.0.0 release so it's not a big deal. I'm going to merge it.

**Comment by vadosnaprimer** [comment]
Thank you so much, I've been waiting for this feature for years!

**Pull request merged**
