### PR TITLE
plugins.picarto: updated the plugin to use the new javascript

### LINKED ISSUE #199: picarto updated streamlink no longer works
Hey guys picarto no longer works because they said they updated the player so html5 can be default soon.
when you run  the program it says found matching plugin picarto for url https:// https://picarto.tv/picknamehere
then the it says error: no stream on this URL: https://picarto.tv/picknamehere.
thanks guys for the awesome program hopefully it gets solved soon!

### PR DESCRIPTION
**Pull request by beardypig**
Some streams are available as HLS, which is now supported. Now gives a warning when the stream is offline. 

Fixes #199

### CODE REVIEW

**Comment by bluesaphiresky** [comment]
I'm sorry I've never tried one of these fixes do I have to wait  for streamlink to be updated? Or can I manually edit something?

**Comment by beardypig** [comment]
@bluesaphiresky You can manually replace your `picarto.py` file with the one here [picarto.py](https://raw.githubusercontent.com/beardypig/streamlink/cb0f744a55e0a750997421450e77578837e75f3f/src/streamlink/plugins/picarto.py). How exactly you do that depends on which OS you are using and how you install `streamlink`.

**Comment by bluesaphiresky** [comment]
@beardypig ah I see I use windows and I used the .exe to install streamlink

**Comment by beardypig** [comment]
OK cool. Assuming you installed it to the default location, you can download the file and copy it to here `%ProgramFiles%\Streamlink\pkgs\streamlink\plugins`. You will have to download it somewhere else, then copy it to the plugins directory as you need Administrator privileges to replace the file, and it probably won't work from the web browser. Make sure the old file is replaced, and that the file extension remains `.py` :)

**Comment by bluesaphiresky** [comment]
@beardypig ah ok sorry I'm not sure how to download the file, I tried changing the file to be read by notepad and tried copy pasting whats in there but ya I get a access denied. I was going to copy paste picarto.py and edit that but still got a access denied.

**Comment by beardypig** [comment]
You can just right click and save the [picarto.py](https://raw.githubusercontent.com/beardypig/streamlink/cb0f744a55e0a750997421450e77578837e75f3f/src/streamlink/plugins/picarto.py) file.

**Comment by bluesaphiresky** [comment]
@beardypig ah awesome got it to work thank you so much sir!

**Comment by beardypig** [comment]
@bluesaphiresky you're quite welcome.

**Comment by gravyboat** [comment]
Thanks @beardypig!

**Pull request merged**
