### PR TITLE
[ufctv] updated to capture 4500k streams

### PR DESCRIPTION
**Pull request by jgilf**
Fixed issues discussed in streamlink/streamlink#1029

### CODE REVIEW

**Comment by beardypig** [comment]
Cool, are there any live streams on UFC? - I don't remember :)

**Comment by jgilf** [comment]
Yes there are, they often stream their prelims and smaller shows live.

**Comment by beardypig** [comment]
I'd want to make sure the live streams still work with this change before merging, or if higher qualities are now (or could be made) available for live streams too.

**Comment by jgilf** [comment]
I will check it with their 24/7 stream then :)

**Comment by jgilf** [comment]
You were right to check the live stream as it was still only pulling the 1600k stream.

This was due to the the live stream having a slightly different url:

> http://nlds67.cdnak.neulion.com/nlds/ufc/ufcepg1/as/live/ufcepg1_hd_iphone.m3u8

To access the 4500k stream, this needs to be changed to:

> http://nlds67.cdnak.neulion.com/nlds/ufc/ufcepg1/as/live/ufcepg1_hd.m3u8

My new commit should cover both VOD and live streams now.

**Comment by beardypig** [comment]
Cool 👍

**Comment by gravyboat** [comment]
Thanks for the fix @jgilf and thanks for the review @beardypig!

**Comment by DanStealth** [comment]
Anyway to get the 4k stream? it's only available on sony tv's via the ufc.tv app but id imaigne they share similarities.

**Pull request merged**
