### PR TITLE
refactor: test_session, move testplugin files

### PR DESCRIPTION
**Pull request by bastimeyer**
- move testplugin and its related files into their own `tests/plugin`
  directory, so that tests don't have to unnecessarily import regular
  plugin test files
- refactor test_session
  - don't initialize session in `setUp`
  - add test cases for ImportError and SyntaxError
  - add assertion for plugin override debug log call
  - rename "load_plugins" test cases
  - rename some confusing variable names
- fix remaining tests in regards to the testplugin path changes

### CODE REVIEW

**Comment by bastimeyer** [comment]
Btw, while changing the plugin path in `test_cmdline` and seeing whether the tests pass, I noticed that this test file has some serious issues and can't be run independently.

That's because `test_cmdline` and some other test modules related to `streamlink_cli` don't properly mock the interfaces they need for testing and thus pollute the namespace of the imported modules, which results in tests not being properly isolated, which they should be.

**Comment by bastimeyer** [comment]
This has however nothing to do with these changes. Just wanted to point it out.

Check it yourself by running
```sh
python -m pytest -ra tests/test_cmdline.py
```

**Comment by beardypig** [comment]
@bastimeyer maybe I'm tired, but I didn't see anything obvious when just running the cmdline test, can you spell it out for me? :)

**Comment by bastimeyer** [comment]
```
$ pytest -q --tb=no tests/test_cmdline.py
FFFFFssssss                                                                                                                              [100%]
=========================================================== short test summary info ============================================================
FAILED tests/test_cmdline.py::TestCommandLinePOSIX::test_open_player_extra_args_in_player - TypeError: expected string or bytes-like object
FAILED tests/test_cmdline.py::TestCommandLinePOSIX::test_open_player_extra_args_in_player_pass_through - TypeError: expected string or bytes-...
FAILED tests/test_cmdline.py::TestCommandLinePOSIX::test_open_regular_path_player - TypeError: expected string or bytes-like object
FAILED tests/test_cmdline.py::TestCommandLinePOSIX::test_open_space_path_player - TypeError: expected string or bytes-like object
FAILED tests/test_cmdline.py::TestCommandLinePOSIX::test_single_hyphen_extra_player_args_971 - TypeError: expected string or bytes-like object
5 failed, 6 skipped in 0.23s

$ pytest -q --tb=no tests/test_cmdline_title.py 
FFFFFFssssssss                                                                                                                           [100%]
=========================================================== short test summary info ============================================================
FAILED tests/test_cmdline_title.py::TestCommandLineWithTitlePOSIX::test_open_player_with_default_title_vlc - TypeError: expected string or by...
FAILED tests/test_cmdline_title.py::TestCommandLineWithTitlePOSIX::test_open_player_with_default_title_vlc_args - TypeError: expected string ...
FAILED tests/test_cmdline_title.py::TestCommandLineWithTitlePOSIX::test_open_player_with_title_mpv - TypeError: expected string or bytes-like...
FAILED tests/test_cmdline_title.py::TestCommandLineWithTitlePOSIX::test_open_player_with_title_vlc - TypeError: expected string or bytes-like...
FAILED tests/test_cmdline_title.py::TestCommandLineWithTitlePOSIX::test_open_player_with_unicode_author_vlc - TypeError: expected string or b...
FAILED tests/test_cmdline_title.py::TestCommandLineWithTitlePOSIX::test_unicode_title_2444 - TypeError: expected string or bytes-like object
6 failed, 8 skipped in 0.25s
```

**Pull request merged**
