### PR TITLE
plugins.radiko: faster download api

### PR DESCRIPTION
**Pull request by iucario**
radiko: use faster download api

### CODE REVIEW

**Comment by bastimeyer** [comment]
This was just changed by #3394. Your PR would revert this.
Can you please explain your reasoning? If this keeps getting changed back and forth, then there needs to be a better solution.

**Comment by iucario** [comment]
Because this api downloads much faster. 

The old one `tf-rpaa.smartstream.ne.jp`  takes 2 hours to download a 2 hour stream, while this one takes minutes.

Also some stations on radiko.jp only use `radiko.jp/v2/api/ts` for timefree, e.g. HOUSOU-DAIGAKU. So the current version of streamlink won't work on those station's timefree stream.

**Comment by gravyboat** [comment]
This has been hanging for a while now. I'm going to need some data that the changes here actually improve the plugin since #3394 was recently merged. Can you please show how this is faster with some benchmarks?

**Comment by iucario** [comment]
OK I'll compare the 2 APIs in speed and availability.

1. **Speed**
- `tf-rpaa.smartstream.ne.jp` takes N minutes to download a N-minute audio. It's like live streaming. Every 5 seconds you get a 5-second-long piece. This API is used both in `live` and `timefree`, maybe that's why they stream in the same way.
- `radiko.jp/v2/api/ts`
I tested it on a 2-hour audio, and got result `Written 41.2 MB (52s @ 809.9 KB/s)`.

    Apparently `radiko.jp/v2/api/ts` is much faster.

2. **Availability**
    There are 15 stations on radiko.jp. `tf-rpaa.smartstream.ne.jp` doesn't work on RN1, JOAK-FM, JOAK, HOUSOU-DAIGAKU the 4 stations. While `radiko.jp/v2/api/ts` works on all 15 stations.

Conclusion. I think we can safely merge this change.

**Comment by gravyboat** [comment]
Is `tf-rpaa.smartstream.ne.jp` only serving live content or can you get the same live content off of `radiko.jp/v2/api/ts`? I don't really care about people downloading video/audio in a timely manner if it's been recorded previously. Streamlink is designed for watching/listening to LIVE streams, not pre-recorded content so the performance of that content isn't something that matters to me.

**Comment by iucario** [comment]
`radiko.jp/v2/api/ts` can only be used for `timefree` not `live`.

There are 2 functions for `live` and `timefree` respectively in the code with different URLs. I only suggest changing the URL of `timefree`. No influence on `live`.

**Comment by bastimeyer** [comment]
I don't mind changing it back to the old URL, but according to this comment

> [Old m3u8 url has been invaild when I used steamlink for radiko site on 12/6 first.](https://github.com/streamlink/streamlink/pull/3394#issuecomment-741604793)

the old URL was invalid at some point, which is the reason why it got changed in #3394.

Your only reasoning is that it downloads faster, which is legitimate, but considering that it already has been "invalid"/offline/inaccessible once doesn't make it sound very future-proof. As said, changing it back-and-forth is not a solution here, so if it's indeed "unstable", then there should at least be a check for availability of the faster endpoint before falling back to the current one, if it's possible.

**Comment by iucario** [comment]
Asked someone who has been using radiko.jp for years, he said that `radiko.jp/v2/api/ts` had been available all the time. 
I guess @smallbomb couldn't access the URL was because of geo-blocking instead of invalid URL.

**Comment by smallbomb** [comment]
@iucario
My situation:
I can access `tf-rpaa.smartstream.ne.jp`  instead of `radiko.jp/v2/api/ts`  using the same IP  at the time. :(

I have an idea.
When `radiko.jp/v2/api/ts` can't be access first, change to try `tf-rpaa.smartstream.ne.jp` 
Keep speed and availability.

These are my idea. what do you think?

**Comment by iucario** [comment]
@smallbomb 
As long as we can keep `radiko.jp/v2/api/ts` I'm OK with that.

**Comment by kikuyan** [comment]
Sorry for my sudden intrusion.

I'm facing just the same problems as @iucario and expecting them to be solved, but the situation seems to have not changed recently. I did some research and found that `radiko.jp/v2/api/ts` should be available to all 110 radio stations. `tf-rpaa.smartstream.ne.jp` is available to 39, only about 1/3, radio stations.

May I ask @smallbomb how you run streamlink to listen to radiko streams? Using VPN or proxy? You don't seem to be in Japan from your profile.
Do you remember which radio station did error occur? What specific error?

**Comment by smallbomb** [comment]
@kikuyan 

> May I ask @smallbomb how you run streamlink to listen to radiko streams?

VPN (sever list from VPN Gate)

> Do you remember which radio station did error occur? What specific error?

step1: 
I used streamlink tool to download audio by 2~3 vpn server but still failed.
step2:
I open browser debug mode, then I observed it access `tf-rpaa.smartstream.ne.jp`  (I could listen radio using gerneral browser.)
step3:
I tried to get `radiko.jp/v2/api/ts` playlist data by browser but the response was `404 not found`.
However, I could get  `tf-rpaa.smartstream.ne.jp` playlist data by browser.
Finally:
I changed to `tf-rpaa.smartstream.ne.jp` from `radiko.jp/v2/api/ts`, then I could normally download audio by tool.

**Comment by kikuyan** [comment]
Thank you for your quick reply and sorry for my late response.

I know VPN Gate, but when I use one, I still can use `radiko.jp/v2/api/ts` without problems for the streams which `tf-rpaa.smartstream.ne.jp` is used by the web browser. (I don't need vpn and usually don't use it, I live in Japan.)
For example, for these streams:
https://radiko.jp/#!/ts/QRR/20210327090000
https://radiko.jp/#!/ts/YFM/20210327090000

I'm wondering what's the difference, where the cause resides. `radiko.jp/v2/api/ts` should  be accessible to everyone.

Could you please try the stream below with your web browser? This is the stream for which only `radiko.jp/v2/api/ts` is supposed to be provided. 
https://radiko.jp/#!/ts/RN1/20210327090000

Do you see `radiko.jp/v2/api/ts` is used by the web browser when played? If so, could you please try it with streamlink with radiko plugin modified to use `radiko.jp/v2/api/ts`? Can it be played?

**Comment by smallbomb** [comment]
@kikuyan 

> Do you see radiko.jp/v2/api/ts is used by the web browser when played? If so, could you please try it with streamlink with radiko plugin modified to use radiko.jp/v2/api/ts? Can it be played?

Thank you for providing urls.

Now, I can download audio using `radiko.jp/v2/api/ts`. 
I can't reproduce the same problem... 
Sorry. :(

**Comment by kikuyan** [comment]
Thank you very much!

Do you mean that you can now download audio from QRR and/or YFM, too?
If yes, that's strange but a good news.
If no, that's still strange because it means that you can use it for some radio stations but cannot for other ones. While we, @iucario and I, can use it for every radio stations.

**Comment by smallbomb** [comment]
> Do you mean that you can now download audio from QRR and/or YFM, too?

Yes. :)

**Comment by kikuyan** [comment]
Thank you again!
But I should have waited a little longer... #3655
Sorry to have troubled you.

**Comment by gravyboat** [comment]
I'm going to close this since https://github.com/streamlink/streamlink/pull/3655 exists and will address this issue going forward.

**Pull request closed without merging**
