### PR TITLE
plugins.vaughnlive: Updated server map

### LINKED ISSUE #1456: Vaughnlive changed IP's to break Streamlink
This will be a very brief bug report... As of tonight the head vaughnlive.py references IPs which were disconnected by vaughn to thwart streamlinking. I've observed vaughn serving video now from "66.90.93.44","66.90.93.35" and have personally gotten it to work overwriting the IP's in rtmp_server_map with those two alternating. I would submit the commit but I think some more testing is needed as I only use streamlink with one occasional stream and don't know how far those IPs will get more frequent SL users.

 #1187 contains lengthy discussion on the history of the war vaughn has waged against streamlink, this is probably not the last time the IPs will change.

### PR DESCRIPTION
**Pull request by beardypig**
Bit slow in creating this PR... fixes #1456.

### CODE REVIEW

**Comment by gravyboat** [comment]
@beardypig I think vaughnlive should be added to our potential list of chopping block plugins. It's mostly stolen content and maintaining the plugin is a pain in the butt.

**Comment by fadster** [comment]
@gravyboat I must disagree. A vast majority of the content on that site and its secondary sites is legitimate. Any channel broadcasting "stolen" content is promptly shutdown by the site owners as they are very responsive to DMCA complaints. This is a very popular plugin and once the site stabilizes after the transition it's going through, keeping it updated shouldn't be too much of an issue.

**Comment by gravyboat** [comment]
@fadster It would be nice to go onto the site for once when this comes up and to not see half a dozen TV shows, anime, UFC fights, and various news stations being rebroadcast but that really isn't the main issue, it's just a convenient secondary concern. The site maintainer purposefully changes configuration to try and block us (https://github.com/streamlink/streamlink/issues/1034#issuecomment-318326584), and you have also commented previously on the constantly changing configuration (https://github.com/streamlink/streamlink/issues/1187#issuecomment-333080247), how many years of configuration changes are okay? I probably should have eliminated the concern of illegal content from my comment entirely and focused on the annoyance of maintenance this plugin creates for us, but I'm not going to edit my comment for posterity's sake.

**Comment by fadster** [comment]
@gravyboat I'm sure you're aware of the reasons for using Streamlink to access the site. The built-in player has been notoriously buggy. Among other problems that have been plaguing it with every update, it doesn't handle buffering very well and forces a 16:9 aspect ratio on all streams, distorting the video in many cases. An external player such as vlc provides controls that resolve these issues entirely.

Regarding the shifting configurations, I believe they are mostly due to changes in hosting platforms, server software and data center locations, in particular over the past few months to accommodate the migration to HTML5. As such, I doubt they are explicitly targeted at blocking Streamlink. I'm confident the plugin won't require frequent updates once the site stabilizes.

**Comment by gravyboat** [comment]
@fadster Yeah their player is... yeesh. I'm going to merge this, if the configuration keeps being swapped around for yet another year we'll have to reconsider support but we'll push it off till then.

**Pull request merged**
