### PR TITLE
Feature/france.tv sport

### PR DESCRIPTION
**Pull request by yhel**
Hello,

Just like last year, the French Open (Roland Garros) is currently airing, Pluzz plugin wasn't working anymore on the dedicated website "sport.francetvinfo.fr".

This commit just fixes the ability to retrieve the stream URL correctly.

Before:
`streamlink https://sport.francetvinfo.fr/roland-garros/direct/ best --player mpv`
`[cli][info] Found matching plugin pluzz for URL https://sport.francetvinfo.fr/roland-garros/direct/`
`error: Unable to open URL: https://ftvensport04hls-i.akamaihd.net/hls/live/664098/SPORT_LV1/master.m3u8 (403 Client Error: Forbidden for url: https://ftvensport04hls-i.akamaihd.net/hls/live/664098/SPORT_LV17/master.m3u8)`

After:
`streamlink https://sport.francetvinfo.fr/roland-garros/direct/ best --player mpv`
`[cli][info] Found matching plugin pluzz for URL https://sport.francetvinfo.fr/roland-garros/direct/`
`[cli][info] Available streams: 216p (worst), 360p, 432p, 540p, 720p (best)`
`[cli][info] Opening stream: 720p (hls)`
`[cli][info] Starting player: mpv`

Best regards.

### CODE REVIEW

**Comment by beardypig** [comment]
Thanks for the contribution @yhel. Could you not just add `or 'sport.francetvinfo.fr' in self.url` here: https://github.com/yhel/streamlink/blob/dbff10cc30488d49e5c05692d883d9ae6167a8a1/src/streamlink/plugins/pluzz.py#L169?

To keep all the token url stuff together, and to keep it dry :)

**Comment by yhel** [comment]
I just pushed the change. I was too focused on the condition related to the extension and the initial error that I had not seen this token logic before.

**Comment by beardypig** [comment]
@yhel, thanks for updating it 👍

**Comment by gravyboat** [comment]
Looks good, thanks @yhel, and thanks for the review @beardypig.

**Pull request merged**
