### PR TITLE
Added tigerdile.com support.

### PR DESCRIPTION
**Pull request by thatlinuxfur**
Credit to skulblakka for original implementation in livestreamer. See: https://github.com/skulblakka/livestreamer/commit/ec9ff879d06dd7db089a22234202a0f48daf9970

### CODE REVIEW

**Comment by beardypig** [comment]
FYI I haven't seen an online stream for this yet so I haven't been able to test it, but I think there are a couple of possible issues :-)

**Comment by thatlinuxfur** [comment]
I took a stab at regex-ifying it. Was that what you had in mind?

**Comment by beardypig** [comment]
Yep :-) I did pretty much the same, e040a808100c3ef24dec1fab139527f6fa675ddc. I also noticed that the subdomain can be swf, so I modified the regex to match any subdomain :-)

**Comment by thatlinuxfur** [comment]
Cool. Anything else jump out at you that needs fixing?

**Comment by beardypig** [comment]
Only to support the SFW urls, eg. https://sfw.tigerdile.com/stream/zannah/ 

The other changes I made were mostly just style changes.

**Comment by thatlinuxfur** [comment]
Oh, OK. I misunderstood what you meant with the sfw URLs. I hadn't seen those before. Updated to match either www. or sfw.

**Comment by beardypig** [comment]
Nice :)

I've still never seen a stream online though :)

**Comment by beardypig** [comment]
@thatlinuxfur yeah, I made a typo :D swf vs sfw ... looks very similar ;)

**Comment by thatlinuxfur** [comment]
Cool, I didn't know about that non-capturing group trick.

And yes, it's quite a small site. I think there are only ~100 members or so.

**Comment by beardypig** [comment]
:) Well I'm happy to merge this. It would be nice to test it... but if it doesn't work, you can fix it :p

**Comment by thatlinuxfur** [comment]
Thanks!

**Comment by beardypig** [comment]
You're welcome. Thanks for your work :-)

**Pull request merged**
