### PR TITLE
 tests.plugins: Test that each plugin has a test file

### PR DESCRIPTION
**Pull request by back-to**
#### tests.plugins: Added URL tests for every plugin

- broken plugins might have only negative tests
- some URLs are only derived from the _url_re

#### tests.plugins: New test if a plugin has a test file

- errors when there is no test file for a plugin
  (New Plugin without Tests)
- errors when there is a test file but no plugin
  (Removed old Plugin, but not the tests)

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me @back-to, I'll leave it open in case anyone else wants to weigh in. My only concern is over the naming of `tests/test_tests_plugins.py` but I also don't have a better suggestion at this time.

**Comment by beardypig** [comment]
I’d say test_plugins_meta, maybe the tests for the docs could be moved there too ;)

**Comment by back-to** [comment]
I will move it to `test_plugins_meta`

**Comment by gravyboat** [comment]
Thanks @back-to, this is a great addition.

**Pull request merged**
