### PR TITLE
plugins.okru: Fixed Plugin

### PR DESCRIPTION
**Pull request by back-to**
- renamed plugin from `ok_live` to `okru`
- use a better version of this plugin
- added support for `HTTP` + `RTMP`

Fixed https://github.com/streamlink/streamlink/issues/2364

### CODE REVIEW

**Comment by karlo2105** [comment]
@back-to 
Thanks for fix. ;-)

**Comment by Bluebuster116** [comment]
@back-to Installation instructions for this update?. Just deleting the old file in plugins directory and replacing it with the current? I did just that and it works. The file which I deleted was ok_live.py and replaced it with okru.py I think this change should be included in the nigthly build.

**Comment by beardypig** [comment]
@Bluebuster116 it own't be in the nightly build, until it's merged in to master. 

@back-to, can you rebase on to master and push it again - I tried to resolve the conflict, but GitHub make terrible commit messages :D

**Comment by Bluebuster116** [comment]
@beardypig Okay. But how do I know that its been merged in the master?. Sorry I don't know where to follow those updates.
@back-to I had confused a bit in the beginning for why there were two different filenames for ok.ru plugin?. ok_live.py and okru.py wouldn't be much better to just update the first one?. Anyways I'm hoping this gets merged in the master as it is difficult to catch up with changes every time issues arisen in the log.

**Comment by beardypig** [comment]
@Bluebuster116 once this PR is merged it will be closed as "merged", it will say at the bottom of the feed. Something like this:
merged

**Pull request merged**
