### PR TITLE
Add support for replay.gulli.fr

### PR DESCRIPTION
**Pull request by melmorabity**
This plugin add support for the French TV channel Gulli (for children). It supports both VOD and live streams. Streams are geo-restricted to France, Belgium and Switzerland.

The live stream is available at http://replay.gulli.fr/Direct

### CODE REVIEW

**Comment by karlo2105** [comment]
I get this error with working French and Swiss proxies. 
In Belgium I get same result without proxy. The latest development has been used. 

`[Streamlink for Windows v0.2.0 - Git 5035b69]
[cli][info] Found matching plugin gulli for URL http://replay.gulli.fr/Direct
error: Unable to open URL: http://lagardere-gulli-hls-live-10641.scdn.arkena.com
/c3RhcnRfdGltZT0yMDE3MDEyMzAwMDAwMCZlbmRfdGltZT0yMDE3MDEyNTAwMDAwMCZkaWdlc3Q9ODJ
kNTc3NmZjNWUyYjdiOTIyZDEyOTYxZGIyOWViYjI0MzRkZWEyMA==/gulli.isml/master.m3u8 (40
3 Client Error: Forbidden for url: http://lagardere-gulli-hls-live-10641.scdn.ar
kena.com/c3RhcnRfdGltZT0yMDE3MDEyMzAwMDAwMCZlbmRfdGltZT0yMDE3MDEyNTAwMDAwMCZkaWd
lc3Q9ODJkNTc3NmZjNWUyYjdiOTIyZDEyOTYxZGIyOWViYjI0MzRkZWEyMA==/gulli.isml/master.
m3u8)
[End of Streamlink for Windows]`

**Comment by melmorabity** [comment]
@karlo2105 are you using a public French proxy? If yes, could you tell me which one?

**Comment by karlo2105** [comment]
OK I managed to open it with public proxy from [here](http://spys.ru/free-proxy-list/FR/).

**Comment by melmorabity** [comment]
@karlo2105 Since you're in Belgium, do you have access in your browser to the live TV on gulli.fr?

**Comment by karlo2105** [comment]
No it doesn't work in Belgium. It displays "Cannot load m3u8, crossdomain access denied".

**Comment by melmorabity** [comment]
@karlo2105 Thanks for your comments. Seems like Gulli is geo-restricted to France only (checked today with working proxies for these two countries).
I updated documentation on my branch, and improved as well logging messages.

**Comment by gravyboat** [comment]
Thanks @melmorabity!

**Pull request merged**
