### PR TITLE
Add support for 9anime.to

### PR DESCRIPTION
**Pull request by beardypig**
This PR adds support for the site 9anime.to as requested by @Victolabs in #202 :)

### CODE REVIEW

**Comment by beardypig** [comment]
@Victolabs If you are able to test this, that would be great. I tested quite a few episodes, but I didn't try every episode so some might not work. If you find any that don't work, let me know and I'll try and fix them.

**Comment by Victolabs** [comment]
@beardypig How would I go about downloading the file itself? And once I do that, does it go in this directory? `C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins`

**Comment by beardypig** [comment]
@Victolabs Here's a link to the [nineanime.py](https://github.com/beardypig/streamlink/blob/e81977dee466c6eb8b0b4d6a890ed6f3ed74a2c6/src/streamlink/plugins/nineanime.py) file. Yep that's where you need to copy it to :)

**Comment by Victolabs** [comment]
@beardypig thats just the code. Not the actual file itself. Nevertheless I got the file by downloading the "master" if you will (I'm still new to github. Sorry) and extracting the .py file there. 

So I have played around with it and it seems to be working perfectly! I just cant believe that you actually went ahead and made the plugin for me/everyone else! This has definitely hooked me on board with streamlink. 

And for a simple answer: Yes, the plugin works perfectly.

**Comment by gravyboat** [comment]
Thanks @beardypig!

**Comment by beardypig** [comment]
True @Victolabs, there is a raw button that will send you to actual file https://raw.githubusercontent.com/beardypig/streamlink/e81977dee466c6eb8b0b4d6a890ed6f3ed74a2c6/src/streamlink/plugins/nineanime.py :-)

**Pull request merged**
