### PR TITLE
plugins.nimotv: fix livestream stopping after couple of seconds

### LINKED ISSUE #5114: plugins.nimotv: live stream stops after couple of seconds
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

try any live streams of nimo.tv, the live stream will stop in couple of seconds.

### Debug log

```text
c:\temp>streamlink --loglevel debug https://www.nimo.tv/live/97747608 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.8
[cli][debug] Streamlink: 5.1.2
[cli][debug] Dependencies:
[cli][debug]  certifi: 2018.11.29
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.6.4
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodome: 3.7.3
[cli][debug]  PySocks: 1.6.8
[cli][debug]  requests: 2.26.0
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.2.1
[cli][debug]  importlib-metadata: 3.10.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.nimo.tv/live/97747608
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin nimotv for URL https://www.nimo.tv/live/97747608
[plugins.nimotv][debug] URL=http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 1674443953; Last Sequence: 1674443955
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1674443953; End Sequence: None
[stream.hls][debug] Adding segment 1674443953 to queue
[stream.hls][debug] Adding segment 1674443954 to queue
[stream.hls][debug] Adding segment 1674443955 to queue
[stream.hls][debug] Writing segment 1674443953 to output
[stream.hls][debug] Segment 1674443953 complete
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format https://www.nimo.tv/live/97747608 -
[cli][debug] Writing stream to output
[stream.hls][debug] Writing segment 1674443954 to output
[stream.hls][debug] Segment 1674443954 complete
[stream.hls][debug] Writing segment 1674443955 to output
[stream.hls][debug] Segment 1674443955 complete
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8?appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000 (403 Client Error: Forbidden for url: http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8?appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000&appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8?appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000 (403 Client Error: Forbidden for url: http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8?appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000&appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8?appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000 (403 Client Error: Forbidden for url: http://tx.hls.nimo.tv/live/su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7.m3u8?appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000&appid=81&id=su1629530778249rea7ea30592d8ab7ce78a1a13e3037be7&tp=1674443951824&u=0&t=100&needwm=0&ratio=6000)
```

### PR DESCRIPTION
**Pull request by TaoziDB**
Fixes #5114

Add wsSecret and wsTime to the stream url.

### CODE REVIEW

**Comment by bastimeyer** [comment]
Thanks, this seems to work.

As a side note, the plugin is still setting an Android user agent header. The site however now seems to require the user to download a mobile app when accessing it with any mobile phone user agent. HLSStream was used previously because of their old mobile site from what it looks like, which is much more preferred over progressive HTTPStreams that their main site is using (which is ridiculously bad). So if there is a way to request HLS streams again, which is probably what their mobile apps are still doing, then this should be implemented instead.

**Comment by TaoziDB** [comment]
The browser on pc uses flv, I tried m3u8 first, but adding wsSecret and wsTime to m3u8 can not fix the stopping bug.

> Thanks, this seems to work.
> 
> As a side note, the plugin is still setting an Android user agent header. The site however now seems to require the user to download a mobile app when accessing it with any mobile phone user agent. HLSStream was used previously because of their old mobile site from what it looks like, which is much more preferred over progressive HTTPStreams that their main site is using (which is ridiculously bad). So if there is a way to request HLS streams again, which is probably what their mobile apps are still doing, then this should be implemented instead.

**Comment by bastimeyer** [comment]
> adding wsSecret and wsTime to m3u8 can not fix the stopping bug

It's possible that those parameters need to get re-calculated / re-obtained for each playlist refresh, while the progressive stream with the single-HTTP request just keeps going without aborting. Subclassing the HLSStream class and implementing refresh logic is not worth the hassle though, so this seems fine.

You'll still need to fix the linting issues before this can get merged.

**Comment by TaoziDB** [comment]
Regarding PR: squash commits, is there anything I need to do?

**Comment by bastimeyer** [comment]
No, this is just added as a reminder for PRs with multiple commits that need to get squashed when merging.

**Comment by TaoziDB** [comment]
Thanks for your help.
> No, this is just added as a reminder for PRs with multiple commits that need to get squashed when merging.

**Pull request merged**
