### PR TITLE
Fix iframe detection for BTN/cdn.bg streams

### PR DESCRIPTION
**Pull request by beardypig**
As reported by @roshavagarga via email. 

Renamed `plugins.btn` to `plugins.cdnbg` and fixed the iframe detection for some of the sites.

### CODE REVIEW

**Comment by gravyboat** [comment]
@beardypig As a heads up apparently Appveyor had some issues over the weekend that froze up queued items so this will probably never complete. Apparently you can kill the queue to fix it next time it runs.

**Comment by beardypig** [comment]
Ha, I did try that about 6 hours ago but it didn't seems to work... I'll try again :-)

**Comment by gravyboat** [comment]
Sounds good, that's just what they said on Twitter for people who were asking so who knows! I'm going to squash and merge this as well.

**Comment by beardypig** [comment]
Cool, I cancelled and re started all the jobs that were still queued. Who knows if it'll work :-)

**Pull request merged**
