### PR TITLE
plugin.npo: rewrite of plugin to use the new API

### PR DESCRIPTION
**Pull request by beardypig**
As reported in #638 the NPO.nl plugin has stopped working. 

This is a mostly total rewrite of the existing plugin to use the updated API. 

Subtitles can be enabled on the stream (if available) by using the `--npo-subtitles` option.

### CODE REVIEW

**Comment by karlo2105** [comment]
Works great. Just to inform you not all streams are covered by plugin, so please add support for following channels : 

- NPO Zapp : `http://www.zapp.nl/nu-straks`
- NPO Zappelin : `http://www.zappelin.nl/tv-kijken`
- NPO 3 : `http://www.npo.nl/npo3`

Notice : NPO 3 has slightly different address than others and last time I checked up it wasn't covered by plugin. This address `http://www.npo.nl/live/npo-3` redirects to NPO 3 above. 
I can give a review to NPO 3 in the evening when it's aired online. 

;)

**Comment by sophof** [comment]
Can confirm it works as well.

**Comment by beardypig** [comment]
Thanks for the feedback dudes. 
Yeah, NPO3 I couldn't test cos it's off air at the moment. I was just going to look at zapp.nl and zappelin.nl as I know (@karlo2105 told me before :)) that they aren't covered

**Comment by beardypig** [comment]
@karlo2105 zapp.nl and zappelin.nl should work now, I would appreciate your help testing them :)

**Comment by karlo2105** [comment]
```
streamlink -l debug "http://www.zapp.nl/nu-straks"
[cli][info] Found matching plugin npo for URL http://www.zapp.nl/nu-straks
error: No playable streams found on this URL: http://www.zapp.nl/nu-straks
```

**Comment by beardypig** [comment]
@karlo2105 should be fixed now ... :)

**Comment by karlo2105** [comment]
```
streamlink "http://www.npo.nl/npo3" best
[cli][info] Found matching plugin npo for URL http://www.npo.nl/npo3
[cli][info] Available streams: 162p (worst), 234p, 306p, 342p (best)
[cli][info] Opening stream: 342p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
It could be merged to master branch. ;)

**Comment by beardypig** [comment]
NPO 3 works then?

**Comment by karlo2105** [comment]
Yes it works as you can see in the output. ;)

**Comment by beardypig** [comment]
Cool, thanks for testing it!

**Comment by karlo2105** [comment]
Thank you for maintenance. :+1:

**Comment by beardypig** [comment]
@gravyboat and now I rebased this one :)

**Comment by gravyboat** [comment]
Good stuff, thanks @beardypig!

**Pull request merged**
